# Generated by Django 6.0.3 on 2026-05-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("panda", "0002_remove_panda_master_panda_masters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("exam_number", models.IntegerField()),
                (
                    "listening_audio",
                    models.FileField(blank=True, null=True, upload_to="exam_audio/"),
                ),
                ("listening_minutes", models.IntegerField(default=60)),
                ("reading_minutes", models.IntegerField(default=70)),
                ("writing_minutes", models.IntegerField(default=50)),
                ("allow_audio_replay", models.BooleanField(default=True)),
                ("allow_audio_pause", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-exam_number"],
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_section",
                    models.CharField(
                        choices=[
                            ("listening", "Listening / 듣기"),
                            ("reading", "Reading / 읽기"),
                            ("writing", "Writing / 쓰기"),
                            ("completed", "Completed"),
                        ],
                        default="listening",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("listening_started_at", models.DateTimeField(blank=True, null=True)),
                ("reading_started_at", models.DateTimeField(blank=True, null=True)),
                ("writing_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("listening_score", models.IntegerField(blank=True, null=True)),
                ("reading_score", models.IntegerField(blank=True, null=True)),
                ("writing_score", models.IntegerField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exam.exam",
                    ),
                ),
                (
                    "panda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to="panda.panda",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("listening", "Listening / 듣기"),
                            ("reading", "Reading / 읽기"),
                            ("writing", "Writing / 쓰기"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number", models.IntegerField()),
                ("passage", models.TextField(blank=True)),
                (
                    "passage_image",
                    models.ImageField(blank=True, null=True, upload_to="exam_images/"),
                ),
                ("question_text", models.TextField()),
                (
                    "question_image",
                    models.ImageField(blank=True, null=True, upload_to="exam_images/"),
                ),
                ("is_writing", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("exam", "section", "number")},
            },
        ),
        migrations.CreateModel(
            name="ExamChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("text", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="exam_images/"),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="exam.examquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("written_answer", models.TextField(blank=True)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exam.examattempt",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam.examchoice",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam.examquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
