# Generated by Django 6.0.3 on 2026-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["language", "-exam_number"]},
        ),
        migrations.AlterModelOptions(
            name="examchoice",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="examchoice",
            name="image",
        ),
        migrations.RemoveField(
            model_name="examchoice",
            name="number",
        ),
        migrations.AddField(
            model_name="exam",
            name="language",
            field=models.CharField(
                choices=[
                    ("korean", "한국어 (Korean)"),
                    ("english", "English"),
                    ("japanese", "日本語 (Japanese)"),
                    ("chinese", "中文 (Chinese)"),
                ],
                default="korean",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examchoice",
            name="text",
            field=models.CharField(max_length=500),
        ),
    ]
