# Generated by Django 6.0.3 on 2026-09-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_drop_orphan_passage_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_format",
            field=models.CharField(
                choices=[("topik", "TOPIK II"), ("sat", "Digital SAT")],
                default="topik",
                help_text="Drives scoring and the on-screen layout.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="break_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="math_score",
            field=models.IntegerField(blank=True, help_text="SAT 200–800", null=True),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="rw_score",
            field=models.IntegerField(blank=True, help_text="SAT 200–800", null=True),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("break", "On break"),
                    ("completed", "Completed"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="total_score",
            field=models.IntegerField(blank=True, help_text="SAT 400–1600", null=True),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="accepted_answers",
            field=models.TextField(
                blank=True,
                help_text='Grid-in only: accepted answers, one per line (e.g. "2/3" or "0.667").',
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice"),
                    ("grid", "Student-produced response (grid-in)"),
                    ("essay", "Written / essay"),
                ],
                default="mcq",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Shown on the result page (Uzbek)."
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="skill",
            field=models.CharField(
                blank=True, help_text="Domain, for the score report", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="current_section",
            field=models.CharField(default="listening", max_length=20),
        ),
        migrations.AlterField(
            model_name="exampassage",
            name="section",
            field=models.CharField(
                choices=[
                    ("listening", "Listening / 듣기"),
                    ("reading", "Reading / 읽기"),
                    ("writing", "Writing / 쓰기"),
                    ("rw1", "SAT Reading and Writing — Module 1"),
                    ("rw2e", "SAT Reading and Writing — Module 2 (lower)"),
                    ("rw2h", "SAT Reading and Writing — Module 2 (upper)"),
                    ("math1", "SAT Math — Module 1"),
                    ("math2e", "SAT Math — Module 2 (lower)"),
                    ("math2h", "SAT Math — Module 2 (upper)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="section",
            field=models.CharField(
                choices=[
                    ("listening", "Listening / 듣기"),
                    ("reading", "Reading / 읽기"),
                    ("writing", "Writing / 쓰기"),
                    ("rw1", "SAT Reading and Writing — Module 1"),
                    ("rw2e", "SAT Reading and Writing — Module 2 (lower)"),
                    ("rw2h", "SAT Reading and Writing — Module 2 (upper)"),
                    ("math1", "SAT Math — Module 1"),
                    ("math2e", "SAT Math — Module 2 (lower)"),
                    ("math2h", "SAT Math — Module 2 (upper)"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ExamModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Matches ExamQuestion.section", max_length=20
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("listening", "Listening"),
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("rw", "Reading and Writing"),
                            ("math", "Math"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        default=1,
                        help_text="1 = everyone takes it, 2 = a routed branch",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("easy", "Lower"), ("hard", "Upper")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("label_uz", models.CharField(blank=True, max_length=120)),
                ("minutes", models.IntegerField(default=30)),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="Position of this kind in the sitting"
                    ),
                ),
                (
                    "route_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Stage-1 only: raw correct >= this routes to the upper module.",
                        null=True,
                    ),
                ),
                (
                    "break_minutes",
                    models.IntegerField(
                        default=0, help_text="Break AFTER this module finishes"
                    ),
                ),
                ("calculator", models.BooleanField(default=False)),
                ("reference_sheet", models.BooleanField(default=False)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="exam.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["exam", "order", "stage", "difficulty"],
                "unique_together": {("exam", "code")},
            },
        ),
        migrations.AddField(
            model_name="examattempt",
            name="current_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="exam.exammodule",
            ),
        ),
        migrations.CreateModel(
            name="ExamModuleAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_score",
                    models.IntegerField(
                        blank=True, help_text="Number correct", null=True
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_attempts",
                        to="exam.examattempt",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="exam.exammodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module__order", "module__stage"],
                "unique_together": {("attempt", "module")},
            },
        ),
    ]
