# Generated by Django 6.0.3 on 2026-10-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_seed_topik_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="break_used",
            field=models.BooleanField(
                default=False, help_text="GMAT: the optional break has been taken"
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="di_score",
            field=models.IntegerField(blank=True, help_text="GMAT 60–90", null=True),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="quant_score",
            field=models.IntegerField(blank=True, help_text="GMAT 60–90", null=True),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="section_order",
            field=models.CharField(
                blank=True,
                help_text='GMAT: module kinds in the chosen order, e.g. "verbal,quant,di"',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="verbal_score",
            field=models.IntegerField(blank=True, help_text="GMAT 60–90", null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_format",
            field=models.CharField(
                choices=[
                    ("topik", "TOPIK II"),
                    ("sat", "Digital SAT"),
                    ("gmat", "GMAT Focus Edition"),
                ],
                default="topik",
                help_text="Drives scoring and the on-screen layout.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="total_score",
            field=models.IntegerField(
                blank=True, help_text="SAT 400–1600 / GMAT 205–805", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exammodule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("listening", "Listening"),
                    ("reading", "Reading"),
                    ("writing", "Writing"),
                    ("rw", "Reading and Writing"),
                    ("math", "Math"),
                    ("quant", "Quantitative Reasoning"),
                    ("verbal", "Verbal Reasoning"),
                    ("di", "Data Insights"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exampassage",
            name="section",
            field=models.CharField(
                choices=[
                    ("listening", "Listening / 듣기"),
                    ("reading", "Reading / 읽기"),
                    ("writing", "Writing / 쓰기"),
                    ("rw1", "SAT Reading and Writing — Module 1"),
                    ("rw2e", "SAT Reading and Writing — Module 2 (lower)"),
                    ("rw2h", "SAT Reading and Writing — Module 2 (upper)"),
                    ("math1", "SAT Math — Module 1"),
                    ("math2e", "SAT Math — Module 2 (lower)"),
                    ("math2h", "SAT Math — Module 2 (upper)"),
                    ("quant", "GMAT Quantitative Reasoning"),
                    ("verbal", "GMAT Verbal Reasoning"),
                    ("di", "GMAT Data Insights"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="section",
            field=models.CharField(
                choices=[
                    ("listening", "Listening / 듣기"),
                    ("reading", "Reading / 읽기"),
                    ("writing", "Writing / 쓰기"),
                    ("rw1", "SAT Reading and Writing — Module 1"),
                    ("rw2e", "SAT Reading and Writing — Module 2 (lower)"),
                    ("rw2h", "SAT Reading and Writing — Module 2 (upper)"),
                    ("math1", "SAT Math — Module 1"),
                    ("math2e", "SAT Math — Module 2 (lower)"),
                    ("math2h", "SAT Math — Module 2 (upper)"),
                    ("quant", "GMAT Quantitative Reasoning"),
                    ("verbal", "GMAT Verbal Reasoning"),
                    ("di", "GMAT Data Insights"),
                ],
                max_length=20,
            ),
        ),
    ]
