# Generated by Django 6.0.3 on 2026-06-05 11:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short description shown on the track card.",
                        max_length=300,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-mortarboard",
                        help_text="Bootstrap-icons class, e.g. bi-mortarboard.",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color for card accent, e.g. #6366f1",
                        max_length=7,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("listening", "Listening"),
                            ("speaking", "Speaking"),
                            ("vocab", "Vocabulary"),
                            ("strategy", "Strategy"),
                        ],
                        default="reading",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short description shown on listing cards.",
                        max_length=300,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="examprep/thumbs/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examprep_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="examprep.examtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
                "unique_together": {("track", "slug")},
            },
        ),
        migrations.CreateModel(
            name="LessonBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image / book screenshot, shown at the top of the block.",
                        null=True,
                        upload_to="examprep/blocks/",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption under the image.",
                        max_length=300,
                    ),
                ),
                (
                    "rich_text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Explanation text, or the question prompt if this block has choices.",
                        null=True,
                    ),
                ),
                (
                    "explanation",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Shown after the student answers. Only used when the block has choices.",
                        null=True,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="examprep.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BlockChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="examprep.lessonblock",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
