# Generated by Django 6.0.3 on 2026-06-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonblock",
            name="block_type",
        ),
    ]
