# Generated by Django 6.0.3 on 2026-07-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0002_remove_lessonblock_block_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("reading", "Reading"),
                            ("writing", "Writing"),
                            ("listening", "Listening"),
                            ("speaking", "Speaking"),
                            ("vocab", "Vocabulary"),
                            ("strategy", "Strategy"),
                        ],
                        default="reading",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short description shown on the topic card.",
                        max_length=300,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-collection",
                        help_text="Bootstrap-icons class, e.g. bi-megaphone.",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="examprep.examtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("track", "skill", "slug")},
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional question-type group inside the skill.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="examprep.topic",
            ),
        ),
    ]
