# Generated by Django 6.0.3 on 2026-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0003_topic_lesson_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonblock",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="Optional audio clip (listening lessons), played above the text.",
                null=True,
                upload_to="examprep/audio/",
            ),
        ),
    ]
