# Generated by Django 6.0.3 on 2026-07-25 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0005_lessonprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WritingDrill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("51", "51 — 실용문 빈칸"),
                            ("52", "52 — 설명문 빈칸"),
                            ("53", "53 — 도표 분석 (200~300자)"),
                            ("54", "54 — 주제 글쓰기 (600~700자)"),
                            ("t1", "Task 1 — Report"),
                            ("t2", "Task 2 — Essay"),
                        ],
                        default="53",
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short card blurb in Uzbek.",
                        max_length=300,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The exam question, HTML — instruction text as it would appear on the test paper."
                    ),
                ),
                (
                    "chart",
                    models.TextField(
                        blank=True,
                        help_text="The graph/table as inline HTML/SVG (wp-chart markup).",
                    ),
                ),
                (
                    "template_body",
                    models.TextField(
                        blank=True,
                        help_text="Scaffold text with wp-blank gaps and cn-word marks.",
                    ),
                ),
                (
                    "model_answer",
                    models.TextField(
                        help_text="Full model answer, HTML, with cn-word marks."
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        blank=True,
                        help_text="Strategy notes in Uzbek, HTML (shown under the answer).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examprep_writing_drills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_drills",
                        to="examprep.examtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["qtype", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WritingDrillWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("translation", models.CharField(max_length=200)),
                (
                    "pos",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("verb", "Verb"),
                            ("adj", "Adjective"),
                            ("adv", "Adverb"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words",
                        to="examprep.writingdrill",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="WritingDrillProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_awarded", models.PositiveSmallIntegerField(default=8)),
                ("finished_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="examprep.writingdrill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examprep_writing_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "drill")},
            },
        ),
    ]
