# Generated by Django 6.0.3 on 2026-07-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0007_move_writing_drills_from_corner"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="The pattern itself, e.g. -(으)니까 or -기 때문에.",
                        max_length=120,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=160)),
                (
                    "reading",
                    models.CharField(
                        blank=True,
                        help_text="Optional romanization, e.g. -(eu)nikka.",
                        max_length=120,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("particle", "조사 — Qo‘shimchalar (kelishik/yuklama)"),
                            ("ending", "종결어미 — Tugallovchi qo‘shimchalar"),
                            ("connective", "연결어미 — Bog‘lovchi qo‘shimchalar"),
                            ("tense", "시제 — Zamon va nisbat"),
                            ("modifier", "관형형 — Aniqlovchi shakllar"),
                            ("expression", "문형 — Grammatik iboralar"),
                            ("voice", "피동·사동 — Majhul va orttirma"),
                            ("quotation", "인용 — Ko‘chirma gap"),
                            ("honorific", "높임 — Hurmat shakllari"),
                            ("adverb", "접속부사 — Bog‘lovchi ravishlar"),
                        ],
                        default="expression",
                        max_length=20,
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("reason", "Sabab — 이유·원인"),
                            ("contrast", "Qarama-qarshilik — 대조·반대"),
                            ("condition", "Shart — 조건·가정"),
                            ("concession", "Qarshi qo‘yish — 양보"),
                            ("time", "Vaqt — 시간·순서"),
                            ("purpose", "Maqsad — 목적"),
                            ("intention", "Niyat va reja — 의도·계획"),
                            ("guess", "Taxmin — 추측"),
                            ("ability", "Imkoniyat va qobiliyat — 가능·능력"),
                            ("obligation", "Majburiyat va ruxsat — 의무·허락"),
                            ("experience", "Tajriba va odat — 경험·습관"),
                            ("change", "O‘zgarish va holat — 변화·상태"),
                            ("comparison", "Taqqoslash — 비교"),
                            ("listing", "Sanash va qo‘shish — 나열·첨가"),
                            ("choice", "Tanlov — 선택"),
                            ("quote", "Ko‘chirma gap — 인용"),
                            ("feeling", "His-tuyg‘u va baho — 감정·평가"),
                            ("discovery", "Bilib qolish — 발견·깨달음"),
                            ("degree", "Daraja va miqdor — 정도·수량"),
                            ("case", "Gap bo‘lagi — 문장 성분"),
                            ("politeness", "Muomala darajasi — 높임·말투"),
                        ],
                        default="reason",
                        help_text="Meaning group — synonyms are grouped by this.",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="TOPIK level 1–6 where it first appears."
                    ),
                ),
                (
                    "meaning",
                    models.CharField(
                        help_text='Short Uzbek gloss shown in the table, e.g. "sabab — chunki".',
                        max_length=200,
                    ),
                ),
                (
                    "attach",
                    models.CharField(
                        blank=True,
                        help_text="Where it attaches, e.g. 동사/형용사 + -(으)니까.",
                        max_length=160,
                    ),
                ),
                (
                    "form_rule",
                    models.TextField(
                        blank=True, help_text="Conjugation rule in Uzbek, HTML allowed."
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Nuance / usage notes in Uzbek, HTML allowed.",
                    ),
                ),
                (
                    "mistake",
                    models.TextField(
                        blank=True, help_text="Common mistake in Uzbek, HTML allowed."
                    ),
                ),
                (
                    "register",
                    models.CharField(
                        choices=[
                            ("written", "Yozma / rasmiy — 문어·격식"),
                            ("formal", "Rasmiy nutq — 하십시오체"),
                            ("polite", "Muloyim — 해요체"),
                            ("casual", "Erkin — 반말"),
                            ("both", "Ikkalasi ham"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "freq",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How often it shows up in TOPIK: 1–3 stars.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_points",
                        to="examprep.examtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("track", "slug")},
            },
        ),
        migrations.CreateModel(
            name="GrammarExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean", models.CharField(max_length=400)),
                ("uz", models.CharField(blank=True, max_length=400)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="examprep.grammarpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GrammarSynonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=120)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Farqi — how it differs, in Uzbek.",
                        max_length=400,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="examprep.grammarpoint",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synonym_of",
                        to="examprep.grammarpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
