# Generated by Django 6.0.3 on 2026-07-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0008_grammarpoint_grammarexample_grammarsynonym"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grammarpoint",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True, max_length=160),
        ),
    ]
