# Generated by Django 6.0.3 on 2026-07-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0009_alter_grammarpoint_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=140),
                ),
                (
                    "hanja",
                    models.CharField(
                        blank=True,
                        help_text="Hanja spelling, e.g. 出口. Blank for native words.",
                        max_length=40,
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("noun", "명사 — Ot"),
                            ("verb", "동사 — Fe’l"),
                            ("adj", "형용사 — Sifat"),
                            ("adv", "부사 — Ravish"),
                            ("phrase", "표현 — Ibora"),
                            ("count", "수사·단위 — Son va o‘lchov"),
                        ],
                        default="noun",
                        max_length=10,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("daily", "Kundalik hayot — 일상생활"),
                            ("person", "Odamlar va munosabat — 사람·관계"),
                            ("emotion", "His-tuyg‘u va fe’l-atvor — 감정·성격"),
                            ("body", "Tana va sog‘liq — 신체·건강"),
                            ("food", "Ovqat — 음식"),
                            ("home", "Uy va turar joy — 집·주거"),
                            ("shopping", "Xarid va pul — 쇼핑·경제생활"),
                            ("transport", "Transport va harakat — 교통·이동"),
                            ("work", "Ish va kasb — 직장·업무"),
                            ("school", "Ta’lim — 학교·교육"),
                            ("society", "Jamiyat — 사회"),
                            ("economy", "Iqtisod — 경제"),
                            ("environment", "Tabiat va ekologiya — 환경·자연"),
                            ("science", "Fan va texnologiya — 과학·기술"),
                            ("culture", "Madaniyat va san’at — 문화·예술"),
                            ("media", "Axborot va OAV — 언론·정보"),
                            ("time", "Vaqt — 시간·날짜"),
                            ("place", "Joy va yo‘nalish — 장소·위치"),
                            ("abstract", "Mavhum tushunchalar — 추상 개념"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="TOPIK level 1–6."
                    ),
                ),
                (
                    "meaning",
                    models.CharField(
                        help_text="Short Uzbek gloss shown in the table.",
                        max_length=200,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Usage note in Uzbek, HTML allowed."
                    ),
                ),
                (
                    "collocation",
                    models.CharField(
                        blank=True,
                        help_text='Typical partners, e.g. "출근하다 · 출근길 · 출근 시간".',
                        max_length=300,
                    ),
                ),
                (
                    "freq",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How often it shows up in TOPIK: 1–3 stars.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_entries",
                        to="examprep.examtrack",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vocab entries",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VocabExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("korean", models.CharField(max_length=400)),
                ("uz", models.CharField(blank=True, max_length=400)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="examprep.vocabentry",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VocabRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("syn", "유의어 — Sinonim"),
                            ("ant", "반의어 — Antonim"),
                            ("rel", "관련어 — Bog‘liq so‘z"),
                        ],
                        default="syn",
                        max_length=3,
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Farqi — how it differs, in Uzbek.",
                        max_length=300,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="examprep.vocabentry",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_from",
                        to="examprep.vocabentry",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="VocabRoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "syllable",
                    models.CharField(
                        help_text="The shared syllable, e.g. 출.", max_length=10
                    ),
                ),
                (
                    "hanja",
                    models.CharField(
                        blank=True,
                        help_text="Its Hanja, e.g. 出. Blank for native-Korean roots.",
                        max_length=10,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=120),
                ),
                (
                    "meaning",
                    models.CharField(
                        help_text='Uzbek gloss, e.g. "chiqmoq — chiqish, tashqariga".',
                        max_length=200,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="How the root behaves / what to watch for, Uzbek HTML.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_roots",
                        to="examprep.examtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("track", "slug")},
            },
        ),
        migrations.AddField(
            model_name="vocabentry",
            name="roots",
            field=models.ManyToManyField(
                blank=True,
                help_text="Root morphemes this word is built from.",
                related_name="entries",
                to="examprep.vocabroot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vocabentry",
            unique_together={("track", "slug")},
        ),
    ]
