# Generated by Django 6.0.3 on 2026-07-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examprep", "0010_vocabentry_vocabexample_vocabrelation_vocabroot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grammarpoint",
            name="category",
            field=models.CharField(
                choices=[
                    ("particle", "조사 — Qo‘shimchalar (kelishik/yuklama)"),
                    ("ending", "종결어미 — Tugallovchi qo‘shimchalar"),
                    ("connective", "연결어미 — Bog‘lovchi qo‘shimchalar"),
                    ("tense", "시제 — Zamon va nisbat"),
                    ("modifier", "관형형 — Aniqlovchi shakllar"),
                    ("expression", "문형 — Grammatik iboralar"),
                    ("voice", "피동·사동 — Majhul va orttirma"),
                    ("quotation", "인용 — Ko‘chirma gap"),
                    ("honorific", "높임 — Hurmat shakllari"),
                    ("adverb", "접속부사 — Bog‘lovchi ravishlar"),
                    ("en_tense", "Zamonlar — Tenses & aspect"),
                    ("en_modal", "Modal fe’llar — Modals"),
                    ("en_clause", "Ergash gaplar — Clauses"),
                    ("en_condition", "Shart gaplar — Conditionals"),
                    ("en_passive", "Majhul nisbat va nominalizatsiya — Passive"),
                    ("en_article", "Artikl va aniqlovchilar — Articles & determiners"),
                    ("en_prep", "Predloglar — Prepositions"),
                    ("en_compare", "Qiyoslash shakllari — Comparison"),
                    ("en_verbpat", "Fe’l qoliplari — Gerunds & infinitives"),
                    ("en_cohesion", "Bog‘lash vositalari — Linking & cohesion"),
                    ("en_advanced", "Murakkab tuzilmalar — Advanced structures"),
                ],
                default="expression",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grammarpoint",
            name="function",
            field=models.CharField(
                choices=[
                    ("reason", "Sabab — 이유·원인"),
                    ("contrast", "Qarama-qarshilik — 대조·반대"),
                    ("condition", "Shart — 조건·가정"),
                    ("concession", "Qarshi qo‘yish — 양보"),
                    ("time", "Vaqt — 시간·순서"),
                    ("purpose", "Maqsad — 목적"),
                    ("intention", "Niyat va reja — 의도·계획"),
                    ("guess", "Taxmin — 추측"),
                    ("ability", "Imkoniyat va qobiliyat — 가능·능력"),
                    ("obligation", "Majburiyat va ruxsat — 의무·허락"),
                    ("experience", "Tajriba va odat — 경험·습관"),
                    ("change", "O‘zgarish va holat — 변화·상태"),
                    ("comparison", "Taqqoslash — 비교"),
                    ("listing", "Sanash va qo‘shish — 나열·첨가"),
                    ("choice", "Tanlov — 선택"),
                    ("quote", "Ko‘chirma gap — 인용"),
                    ("feeling", "His-tuyg‘u va baho — 감정·평가"),
                    ("discovery", "Bilib qolish — 발견·깨달음"),
                    ("degree", "Daraja va miqdor — 정도·수량"),
                    ("case", "Gap bo‘lagi — 문장 성분"),
                    ("politeness", "Muomala darajasi — 높임·말투"),
                    ("result", "Natija — 결과"),
                    ("hedging", "Ehtiyotkor fikr — Hedging"),
                    ("emphasis", "Ta’kid — Emphasis"),
                    ("example", "Misol keltirish — Exemplification"),
                    ("summary", "Umumlashtirish — Summarising"),
                    ("reference", "Ishora va o‘rin bosish — Reference"),
                ],
                default="reason",
                help_text="Meaning group — synonyms are grouped by this.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vocabentry",
            name="hanja",
            field=models.CharField(
                blank=True,
                help_text='Origin: Hanja (出口) or the English word’s build ("in + spect"). Blank for native words.',
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="vocabentry",
            name="level",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1–6 — TOPIK level or IELTS band, per the track (see banklabels).",
            ),
        ),
        migrations.AlterField(
            model_name="vocabentry",
            name="topic",
            field=models.CharField(
                choices=[
                    ("daily", "Kundalik hayot — 일상생활"),
                    ("person", "Odamlar va munosabat — 사람·관계"),
                    ("emotion", "His-tuyg‘u va fe’l-atvor — 감정·성격"),
                    ("body", "Tana va sog‘liq — 신체·건강"),
                    ("food", "Ovqat — 음식"),
                    ("home", "Uy va turar joy — 집·주거"),
                    ("shopping", "Xarid va pul — 쇼핑·경제생활"),
                    ("transport", "Transport va harakat — 교통·이동"),
                    ("work", "Ish va kasb — 직장·업무"),
                    ("school", "Ta’lim — 학교·교육"),
                    ("society", "Jamiyat — 사회"),
                    ("economy", "Iqtisod — 경제"),
                    ("environment", "Tabiat va ekologiya — 환경·자연"),
                    ("science", "Fan va texnologiya — 과학·기술"),
                    ("culture", "Madaniyat va san’at — 문화·예술"),
                    ("media", "Axborot va OAV — 언론·정보"),
                    ("time", "Vaqt — 시간·날짜"),
                    ("place", "Joy va yo‘nalish — 장소·위치"),
                    ("abstract", "Mavhum tushunchalar — 추상 개념"),
                    ("academic", "Akademik til — Academic language"),
                    ("data", "Grafik va raqamlar — Data & trends"),
                    ("health", "Sog‘liq — Health"),
                    ("crime", "Jinoyat va qonun — Crime & law"),
                    ("government", "Hukumat va siyosat — Government & politics"),
                    ("tourism", "Sayohat va turizm — Travel & tourism"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vocabroot",
            name="hanja",
            field=models.CharField(
                blank=True,
                help_text='Origin: Hanja (出) or Latin/Greek source ("specere, lat."). Blank for native roots.',
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="vocabroot",
            name="syllable",
            field=models.CharField(
                help_text="The shared morpheme, e.g. 출 or spect.", max_length=20
            ),
        ),
    ]
