# Generated by Django 6.0.3 on 2026-04-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_master_can_edit_master_category'),
        ('people', '0004_people_is_admin_people_is_assistant_people_is_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('purpose', models.CharField(choices=[('learning', 'Learning'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='learning', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pandas', to='masters.master')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pandas', to='people.people')),
            ],
        ),
    ]
