# Generated by Django 6.0.3 on 2026-04-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        ("people", "0006_people_is_cofounder_people_is_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Panda", max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        default="learning",
                        max_length=20,
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                (
                    "master",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panda",
                        to="masters.master",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panda",
                        to="people.people",
                    ),
                ),
            ],
        ),
    ]
