# Generated by Django 6.0.3 on 2026-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_alter_master_profile"),
        ("panda", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="panda",
            name="master",
        ),
        migrations.AddField(
            model_name="panda",
            name="masters",
            field=models.ManyToManyField(
                blank=True, related_name="pandas", to="masters.master"
            ),
        ),
    ]
