# Generated by Django 6.0.3 on 2026-04-21 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_specialty'),
        ('panda', '0001_initial'),
        ('people', '0004_people_is_admin_people_is_assistant_people_is_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panda',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panda', to='masters.master'),
        ),
        migrations.AlterField(
            model_name='panda',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panda', to='people.people'),
        ),
    ]
