# Generated by Django 6.0.3 on 2026-04-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panda", "0002_alter_panda_master_alter_panda_profile"),
        ("people", "0005_alter_people_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panda",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panda",
                to="people.people",
            ),
        ),
    ]
