# Generated by Django 6.0.3 on 2026-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panda", "0003_alter_panda_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="panda",
            name="age",
        ),
        migrations.AlterField(
            model_name="panda",
            name="name",
            field=models.CharField(default="Panda", max_length=100),
        ),
    ]
