# Generated by Django 6.0.3 on 2026-04-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0006_people_is_cofounder_people_is_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("subject", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("student_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="people.people"
                    ),
                ),
            ],
        ),
    ]
