# Generated by Django 6.0.3 on 2026-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
