# Generated by Django 6.0.3 on 2026-04-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0001_initial"),
        ("people", "0006_people_is_cofounder_people_is_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="people.people"
            ),
        ),
    ]
