# Generated by Django 6.0.3 on 2026-04-21 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_can_edit_master_category'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.subject'),
        ),
    ]
