# Generated by Django 6.0.3 on 2026-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_alter_master_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="master",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
