# Generated by Django 6.0.3 on 2026-04-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0003_master_specialty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="master",
            name="specialty",
        ),
    ]
