# Generated by Django 6.0.3 on 2026-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_master_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='can_edit',
        ),
        migrations.RemoveField(
            model_name='master',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='master',
            name='url',
        ),
        migrations.AddField(
            model_name='master',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='master',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
