# Generated by Django 6.0.3 on 2026-08-22 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0004_certificate_studentpayment_attendance_and_more"),
        ("panda", "0002_remove_panda_master_panda_masters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="master",
            options={
                "ordering": [
                    "-is_powerty",
                    "-weighted_rating",
                    "-contribution_score",
                    "name",
                ]
            },
        ),
        migrations.AddField(
            model_name="master",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Your story: how you started teaching, how you teach, what your pupils achieve.",
                verbose_name="About myself",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="accepting_students",
            field=models.BooleanField(
                default=True, verbose_name="Accepting new students"
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="content_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Published items this master has authored."
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="contribution_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="master",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text='One line under your name, e.g. "SAT Math tutor, 8 years in the classroom".',
                max_length=150,
                verbose_name="Headline",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="how_to_join",
            field=models.TextField(
                blank=True,
                help_text="The real steps: trial lesson, level test, when groups start, what it costs.",
                verbose_name="How to become my student",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="is_powerty",
            field=models.BooleanField(
                default=False,
                help_text="Set by admins only: this master is part of the Powerty education staff, not an independent teacher.",
                verbose_name="Powerty team member",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="languages",
            field=models.CharField(
                blank=True,
                help_text='Comma-separated, e.g. "Uzbek, English, Russian".',
                max_length=150,
                verbose_name="Languages of instruction",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="learner_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Distinct pupils who have worked through this master's content.",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="lesson_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("offline", "In person"),
                    ("hybrid", "Online and in person"),
                ],
                max_length=10,
                verbose_name="Lesson format",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="location",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Tashkent, Chilonzor" or "Online only".',
                max_length=120,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="master",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="A good, well-lit photo of you. Falls back to your profile picture.",
                null=True,
                upload_to="master_photos/",
                verbose_name="Portrait",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="powerty_role",
            field=models.CharField(
                blank=True,
                help_text='e.g. "English Department", "Co-founder". Shown next to the Powerty badge.',
                max_length=100,
                verbose_name="Role at Powerty",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="public_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Public email"
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="master",
            name="stats_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="master",
            name="teaching_since",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The year you started teaching — anywhere, not just here.",
                null=True,
                verbose_name="Teaching since (year)",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="telegram",
            field=models.CharField(
                blank=True,
                help_text="Username without the @, or a t.me link.",
                max_length=100,
                verbose_name="Telegram",
            ),
        ),
        migrations.AddField(
            model_name="master",
            name="website",
            field=models.URLField(blank=True, verbose_name="Website or channel"),
        ),
        migrations.AddField(
            model_name="master",
            name="weighted_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="master",
            name="avg_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.CreateModel(
            name="MasterCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("diploma", "Diploma"),
                            ("certificate", "Certificate"),
                            ("award", "Award"),
                            ("experience", "Experience"),
                        ],
                        default="diploma",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "IELTS 8.0", "Bachelor in Linguistics".',
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        blank=True,
                        help_text="University, exam board or employer.",
                        max_length=200,
                        verbose_name="Issued by",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=250, verbose_name="Note"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="master_credentials/",
                        verbose_name="Scan or photo",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="masters.master",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-year", "id"],
            },
        ),
        migrations.CreateModel(
            name="MasterSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Subject")),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Beginner to IELTS 7.5", "5-9 sinf".',
                        max_length=100,
                        verbose_name="Levels",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="One line on how you teach this subject.",
                        max_length=200,
                        verbose_name="Note",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="masters.master",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MasterReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Review")),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Untick to hide an abusive review."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="masters.master",
                    ),
                ),
                (
                    "panda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_reviews",
                        to="panda.panda",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("master", "panda")},
            },
        ),
    ]
