# Generated by Django 6.0.3 on 2026-08-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0004_classroom_subject_classroomresource"),
        ("masters", "0005_alter_master_options_master_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="classroom.classroom",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="classroom.classroom",
            ),
        ),
        migrations.AddField(
            model_name="studentpayment",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="classroom.classroom",
            ),
        ),
    ]
