# Generated by Django 6.0.3 on 2026-08-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0004_classroom_subject_classroomresource"),
        ("masters", "0006_attendance_classroom_certificate_classroom_and_more"),
        ("panda", "0002_remove_panda_master_panda_masters"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("master", "panda", "classroom", "date")},
        ),
    ]
