# Generated by Django 6.0.3 on 2026-08-19 11:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogicPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="English title.", max_length=200)),
                (
                    "title_uz",
                    models.CharField(
                        blank=True, help_text="Oʻzbekcha sarlavha.", max_length=200
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "number",
                    models.PositiveIntegerField(
                        default=0, help_text="Puzzle number shown on the card (#7)."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weighing", "Weighing"),
                            ("crossing", "Crossing"),
                            ("liars", "Liars & Truth"),
                            ("cutting", "Cut & Measure"),
                            ("numbers", "Numbers"),
                            ("shapes", "Shapes & Grids"),
                            ("chance", "Chance"),
                            ("strategy", "Strategy"),
                        ],
                        default="numbers",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "teaser",
                    models.CharField(
                        blank=True,
                        help_text="One-line hook shown on the card and while upcoming.",
                        max_length=300,
                    ),
                ),
                ("teaser_uz", models.CharField(blank=True, max_length=300)),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="The problem. Figures are inline SVG."
                    ),
                ),
                ("body_uz", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "hint",
                    models.TextField(
                        blank=True, help_text="Optional nudge, hidden behind a toggle."
                    ),
                ),
                ("hint_uz", models.TextField(blank=True)),
                (
                    "answer_key",
                    models.CharField(
                        help_text='The canonical short answer, e.g. "2" or "17".',
                        max_length=200,
                    ),
                ),
                (
                    "accepted",
                    models.TextField(
                        blank=True,
                        help_text="Other spellings that count as correct, one per line.",
                    ),
                ),
                (
                    "answer_hint",
                    models.CharField(
                        blank=True,
                        help_text='What shape of answer to type, e.g. "a number".',
                        max_length=160,
                    ),
                ),
                ("answer_hint_uz", models.CharField(blank=True, max_length=160)),
                (
                    "solution",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="Full reasoning, revealed on the reveal date."
                    ),
                ),
                ("solution_uz", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "opens_at",
                    models.DateTimeField(
                        help_text="When the problem becomes readable and answerable."
                    ),
                ),
                (
                    "reveal_at",
                    models.DateTimeField(
                        help_text="When the solution and everyone’s verdict appear."
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 = derive from difficulty."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logic_puzzles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opens_at", "-number"],
            },
        ),
        migrations.CreateModel(
            name="LogicSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=200)),
                (
                    "reasoning",
                    models.TextField(
                        blank=True,
                        help_text="How they got there — optional, but the good part.",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "sealed",
                    models.BooleanField(
                        default=True, help_text="Submitted before the reveal date."
                    ),
                ),
                ("points_awarded", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="logic.logicpuzzle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logic_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="logicpuzzle",
            index=models.Index(
                fields=["is_published", "opens_at"],
                name="logic_logic_is_publ_fbce15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="logicpuzzle",
            index=models.Index(
                fields=["reveal_at"], name="logic_logic_reveal__47b249_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logicsubmission",
            index=models.Index(
                fields=["user", "is_correct"], name="logic_logic_user_id_1f83d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="logicsubmission",
            unique_together={("puzzle", "user")},
        ),
    ]
