# Generated by Django 6.0.3 on 2026-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quiz", "Daily quiz question"),
                            ("puzzle", "Logic Arena puzzle"),
                            ("solution", "Logic Arena solution"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="PracticeQuestion.id or LogicPuzzle.id, depending on kind."
                    ),
                ),
                ("chat_id", models.CharField(blank=True, max_length=64)),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "posted_at"], name="telegrambot_kind_011d22_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "object_id"),
                        name="telegram_post_unique_per_object",
                    )
                ],
            },
        ),
    ]
