# Generated by Django 6.0.3 on 2026-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrampost",
            name="kind",
            field=models.CharField(
                choices=[
                    ("quiz", "Daily quiz question"),
                    ("puzzle", "Logic Arena puzzle"),
                    ("solution", "Logic Arena solution"),
                    (
                        "abroad_month",
                        "Study abroad — monthly deadlines (object_id = YYYYMM)",
                    ),
                    (
                        "abroad_reminder",
                        "Study abroad — 7-day reminder (object_id = Deadline.id)",
                    ),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="telegrampost",
            name="object_id",
            field=models.PositiveIntegerField(
                help_text="PracticeQuestion.id, LogicPuzzle.id, Deadline.id or YYYYMM, depending on kind."
            ),
        ),
    ]
