# -*- coding: utf-8 -*-
"""IELTS vocab bank — Environment, health & technology.

Order decade 700-799. The second cluster of recurring Task 2 topics, plus the
health and technology vocabulary that Reading passages are built from.

⚠️ Imported LAST — uses roots from files 1-3. See toc_ielts_vocab.txt.
See STYLE_GUIDE_VOCAB_IELTS.md.
"""

TRACK = {
    "name":    "IELTS",
    "summary": "Ingliz tili imtihoniga tayyorgarlik (Academic).",
    "icon":    "bi-globe2",
    "color":   "#059669",
}

WORDS = [
    # ── Ekologiya ───────────────────────────────────────────────────────────
    {
        "word":        "fossil fuels",
        "roots":       [],
        "pos":         "phrase",
        "topic":       "environment",
        "level":       3,
        "freq":        3,
        "meaning":     "qazib olinadigan yoqilg‘i — ko‘mir, neft, gaz",
        "collocation": "burn fossil fuels · dependence on fossil fuels · phase out fossil fuels",
        "note":        "<p>Ekologiya inshosining birinchi so‘zi. Yonidagi fe’llar: "
                       "<b>burn</b>, <b>phase out</b> (bosqichma-bosqich bekor qilmoq), "
                       "<b>rely on</b>.</p>",
        "examples":    [("Burning fossil fuels remains the largest source of greenhouse gases.",
                         "Qazib olinadigan yoqilg‘ini yoqish hamon issiqxona gazlarining eng katta manbai.")],
        "antonyms":    [("renewable", "fossil fuels = tugaydi; renewable = tiklanadi")],
    },
    {
        "word":        "greenhouse gases",
        "roots":       [],
        "pos":         "phrase",
        "topic":       "environment",
        "level":       4,
        "freq":        2,
        "meaning":     "issiqxona gazlari — iqlim isishiga sabab bo‘luvchi gazlar",
        "collocation": "greenhouse gas emissions · trap heat · reduce greenhouse gases",
        "note":        "<p>Sabab zanjirini bir gapda berish uchun: <i><b>Greenhouse gases</b> "
                       "trap heat, <b>thereby raising</b> global temperatures.</i></p>",
        "examples":    [("Agriculture accounts for a significant share of greenhouse gas emissions.",
                         "Qishloq xo‘jaligi issiqxona gazlari chiqindilarining sezilarli qismini tashkil qiladi.")],
        "related":     [("emission", "emission = chiqarish; greenhouse gases = chiqarilayotgan narsa")],
    },
    {
        "word":        "depletion",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "environment",
        "level":       6,
        "freq":        1,
        "meaning":     "tugash, kamayib ketish — zaxiraning yo‘qolib borishi",
        "collocation": "resource depletion · the depletion of fish stocks · deplete reserves",
        "note":        "<p>Fe’li — <b>deplete</b>. Tabiiy resurslar mavzusida: "
                       "<i>the <b>depletion of</b> groundwater</i>.</p>",
        "examples":    [("The depletion of natural resources threatens future economic growth.",
                         "Tabiiy resurslarning tugab borishi kelajakdagi iqtisodiy o‘sishga tahdid soladi.")],
        "related":     [("conservation", "depletion = yo‘qotish; conservation = saqlash")],
    },
    {
        "word":        "conservation",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "environment",
        "level":       5,
        "freq":        2,
        "meaning":     "muhofaza — tabiatni asrash",
        "collocation": "wildlife conservation · energy conservation · conservation efforts",
        "note":        "<p>Fe’li — <b>conserve</b> (asramoq), <i>preserve</i> ga yaqin. "
                       "Ikki sohada: tabiat muhofazasi va energiya tejash.</p>",
        "examples":    [("Conservation projects have helped several species recover.",
                         "Muhofaza loyihalari bir necha turning tiklanishiga yordam berdi.")],
        "antonyms":    [("depletion", "conservation = asrash; depletion = tugatish")],
    },
    {
        "word":        "biodiversity",
        "roots":       [],
        "pos":         "noun",
        "topic":       "environment",
        "level":       6,
        "freq":        2,
        "meaning":     "biologik xilma-xillik — turlarning rang-barangligi",
        "collocation": "loss of biodiversity · protect biodiversity · biodiversity hotspots",
        "note":        "<p><b>bio-</b> (hayot) + <b>diversity</b> (xilma-xillik). "
                       "<b>the loss of biodiversity</b> — o‘rmon kesish va iqlim mavzularida "
                       "eng kuchli oqibat.</p>",
        "examples":    [("Deforestation is the leading cause of biodiversity loss worldwide.",
                         "O‘rmonlarning kesilishi dunyo bo‘ylab biologik xilma-xillik yo‘qolishining asosiy sababi.")],
        "related":     [("diverse", "bir o‘zak: diversity — xilma-xillik")],
    },
    {
        "word":        "deforestation",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "environment",
        "level":       5,
        "freq":        2,
        "meaning":     "o‘rmonlarning kesilishi",
        "collocation": "large-scale deforestation · combat deforestation · deforestation rates",
        "note":        "<p>Teskari jarayon — <b>reforestation</b> (qayta o‘rmonzorlashtirish), "
                       "u yechim qismida ishlaydi.</p>",
        "examples":    [("Deforestation in tropical regions accelerated sharply after 1990.",
                         "Tropik mintaqalarda o‘rmon kesilishi 1990-yildan keyin keskin tezlashdi.")],
        "related":     [("biodiversity", "o‘rmon kesish → xilma-xillik yo‘qoladi")],
    },
    {
        "word":        "pollution",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "environment",
        "level":       2,
        "freq":        3,
        "meaning":     "ifloslanish",
        "collocation": "air pollution · water pollution · reduce pollution levels",
        "note":        "<p>⚠️ <b>Sanalmaydigan</b>: ❌ <i>pollutions</i> → ✅ <i>types <b>of</b> "
                       "pollution</i>. Fe’li — <b>pollute</b>, manba — <b>pollutant</b> "
                       "(ifloslantiruvchi modda).</p>",
        "examples":    [("Air pollution is responsible for millions of premature deaths each year.",
                         "Havo ifloslanishi har yili millionlab bevaqt o‘limga sabab bo‘ladi.")],
        "related":     [("emission", "emission = manba; pollution = natija")],
    },
    {
        "word":        "landfill",
        "roots":       [],
        "pos":         "noun",
        "topic":       "environment",
        "level":       5,
        "freq":        1,
        "meaning":     "chiqindi poligoni — chiqindi ko‘miladigan joy",
        "collocation": "sent to landfill · landfill sites · reduce landfill waste",
        "note":        "<p>Chiqindi mavzusida uchta bosqich: <b>reduce</b> → <b>reuse</b> → "
                       "<b>recycle</b>, va oxirgi chora — <b>landfill</b>.</p>",
        "examples":    [("Around half of household waste still ends up in landfill.",
                         "Maishiy chiqindining qariyb yarmi hamon poligonga tushadi.")],
        "related":     [("recycle", "qayta ishlash poligonga tushadigan chiqindini kamaytiradi")],
    },
    {
        "word":        "carbon footprint",
        "roots":       [],
        "pos":         "phrase",
        "topic":       "environment",
        "level":       5,
        "freq":        2,
        "meaning":     "uglerod izi — bir odam yoki tashkilot chiqaradigan uglerod miqdori",
        "collocation": "reduce your carbon footprint · a large carbon footprint",
        "note":        "<p>Shaxsiy mas’uliyat haqidagi bahsda tayyor ibora: <i>individuals can "
                       "<b>reduce their carbon footprint</b> by …</i></p>",
        "examples":    [("Flying less is the quickest way to cut an individual’s carbon footprint.",
                         "Kamroq uchish — shaxsning uglerod izini qisqartirishning eng tez yo‘li.")],
        "related":     [("emission", "carbon footprint = shaxsiy emissiya hisobi")],
    },
    # ── Sog'liq ─────────────────────────────────────────────────────────────
    {
        "word":        "sedentary",
        "roots":       [],
        "pos":         "adj",
        "topic":       "health",
        "level":       6,
        "freq":        2,
        "meaning":     "harakatsiz — ko‘p o‘tirib o‘tkaziladigan (turmush tarzi)",
        "collocation": "a sedentary lifestyle · sedentary work · increasingly sedentary",
        "note":        "<p><b>a sedentary lifestyle</b> — sog‘liq inshosining eng foydali "
                       "birikmalaridan: <i>Office work encourages a <b>sedentary lifestyle</b>.</i></p>",
        "examples":    [("Increasingly sedentary lifestyles have contributed to rising obesity.",
                         "Tobora harakatsiz turmush tarzi semizlikning o‘sishiga hissa qo‘shdi.")],
        "antonyms":    [("active", "sedentary = harakatsiz; active = faol")],
    },
    {
        "word":        "obesity",
        "roots":       [],
        "pos":         "noun",
        "topic":       "health",
        "level":       5,
        "freq":        3,
        "meaning":     "semizlik — sog‘liqqa zarar darajadagi ortiqcha vazn",
        "collocation": "childhood obesity · rising obesity rates · tackle obesity",
        "note":        "<p>⚠️ Sanalmaydigan. Sifati — <b>obese</b>. Sabablari sifatida: "
                       "<i>processed food</i>, <i>a sedentary lifestyle</i>, "
                       "<i>lack of exercise</i>.</p>",
        "examples":    [("Childhood obesity has tripled in many countries since the 1980s.",
                         "1980-yillardan beri ko‘p mamlakatlarda bolalar semizligi uch baravar oshdi.")],
        "related":     [("sedentary", "harakatsiz hayot semizlikning asosiy sabablaridan")],
    },
    {
        "word":        "life expectancy",
        "roots":       [],
        "pos":         "phrase",
        "topic":       "health",
        "level":       5,
        "freq":        2,
        "meaning":     "o‘rtacha umr ko‘rish davomiyligi",
        "collocation": "life expectancy has risen · average life expectancy · rising life expectancy",
        "note":        "<p>Task 1 diagrammalarida va qarish mavzusida ko‘p uchraydi: "
                       "<i>rising <b>life expectancy</b> combined with falling birth rates</i> — "
                       "demografik muammoning tayyor ta’rifi.</p>",
        "examples":    [("Life expectancy has risen by more than a decade since 1970.",
                         "1970-yildan beri o‘rtacha umr ko‘rish davomiyligi o‘n yildan ko‘proqqa oshdi.")],
        "related":     [("demographic", "umr uzayishi demografik o‘zgarishning asosiy omili")],
    },
    {
        "word":        "chronic",
        "roots":       [],
        "pos":         "adj",
        "topic":       "health",
        "level":       5,
        "freq":        2,
        "meaning":     "surunkali — uzoq davom etadigan (kasallik yoki muammo)",
        "collocation": "chronic illness · chronic shortage · chronic stress",
        "note":        "<p>Faqat tibbiyotda emas: <b>a chronic shortage of housing</b> = "
                       "«surunkali uy-joy tanqisligi». Teskarisi — <b>acute</b> (o‘tkir, keskin).</p>",
        "examples":    [("Chronic illnesses account for the majority of healthcare spending.",
                         "Surunkali kasalliklar sog‘liqni saqlash xarajatlarining katta qismini tashkil qiladi.")],
        "related":     [("prevalent", "surunkali kasalliklar qanchalik keng tarqalgani muhim")],
    },
    {
        "word":        "healthcare",
        "roots":       [],
        "pos":         "noun",
        "topic":       "health",
        "level":       3,
        "freq":        3,
        "meaning":     "sog‘liqni saqlash — tibbiy xizmat tizimi",
        "collocation": "free healthcare · access to healthcare · healthcare system",
        "note":        "<p>⚠️ Sanalmaydigan va bir so‘z (BrE’da <i>health care</i> ham uchraydi). "
                       "<b>free healthcare</b> — davlat xarajatlari haqidagi savolning markazi.</p>",
        "examples":    [("Universal access to healthcare remains a distant goal in many regions.",
                         "Sog‘liqni saqlashdan umumiy foydalanish ko‘p mintaqalarda hamon uzoq maqsad.")],
        "related":     [("welfare", "sog‘liqni saqlash ijtimoiy ta’minotning bir qismi")],
    },
    {
        "word":        "preventive",
        "roots":       ["pre-"],
        "pos":         "adj",
        "topic":       "health",
        "level":       6,
        "freq":        1,
        "meaning":     "profilaktik — oldini oluvchi",
        "collocation": "preventive measures · preventive healthcare · preventive medicine",
        "note":        "<p>Sog‘liq inshosining eng kuchli dalili: <i><b>preventive</b> healthcare "
                       "is far cheaper than treatment</i>.</p>",
        "examples":    [("Investment in preventive healthcare reduces long-term costs.",
                         "Profilaktik tibbiyotga sarmoya uzoq muddatli xarajatlarni kamaytiradi.")],
        "related":     [("prevent", "fe’l va sifat — bir ildizdan")],
    },
    # ── Texnologiya ─────────────────────────────────────────────────────────
    {
        "word":        "innovation",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "science",
        "level":       4,
        "freq":        3,
        "meaning":     "innovatsiya — yangilik joriy etish",
        "collocation": "technological innovation · drive innovation · a culture of innovation",
        "note":        "<p>Fe’li — <b>innovate</b>, sifati — <b>innovative</b>. Iqtisod va ta’lim "
                       "mavzularida: <i>education systems that encourage <b>innovation</b></i>.</p>",
        "examples":    [("Public funding for research drives long-term technological innovation.",
                         "Tadqiqotlarga davlat mablag‘i uzoq muddatli texnologik innovatsiyani harakatga keltiradi.")],
        "related":     [("technology", "technology = vosita; innovation = uni yangilash jarayoni")],
    },
    {
        "word":        "automation",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "science",
        "level":       5,
        "freq":        3,
        "meaning":     "avtomatlashtirish — mehnatni mashinaga o‘tkazish",
        "collocation": "the rise of automation · automation of routine tasks · automated systems",
        "note":        "<p>Ish mavzusidagi eng dolzarb savol: <i>Will <b>automation</b> destroy "
                       "jobs?</i> Yonidagi so‘zlar: <b>artificial intelligence</b>, "
                       "<b>redundant</b> (ortiqcha, ishdan bo‘shatilgan).</p>",
        "examples":    [("Automation is expected to replace many routine administrative roles.",
                         "Avtomatlashtirish ko‘plab bir xildagi ma’muriy ish o‘rinlarini almashtirishi kutilmoqda.")],
        "related":     [("workforce", "avtomatlashtirish ishchi kuchi tarkibini o‘zgartiradi")],
    },
    {
        "word":        "artificial intelligence",
        "roots":       [],
        "pos":         "phrase",
        "topic":       "science",
        "level":       4,
        "freq":        2,
        "meaning":     "sun’iy intellekt (AI)",
        "collocation": "advances in artificial intelligence · AI-driven · rely on AI",
        "note":        "<p>Birinchi marta to‘liq yozing, keyin <b>AI</b> deb qisqartiring — "
                       "akademik yozuvda qisqartma shunday kiritiladi.</p>",
        "examples":    [("Artificial intelligence is already used to diagnose certain illnesses.",
                         "Sun’iy intellekt allaqachon ayrim kasalliklarni aniqlashda qo‘llanilmoqda.")],
        "related":     [("automation", "AI avtomatlashtirishning hozirgi bosqichi")],
    },
    {
        "word":        "surveillance",
        "roots":       [],
        "pos":         "noun",
        "topic":       "government",
        "level":       6,
        "freq":        2,
        "meaning":     "kuzatuv, nazorat — kameralar va ma’lumot orqali",
        "collocation": "state surveillance · surveillance cameras · under surveillance",
        "note":        "<p>Xavfsizlik va shaxsiy hayot muvozanati haqidagi bahsning markazi: "
                       "<i><b>surveillance</b> improves safety but erodes privacy</i>.</p>",
        "examples":    [("The expansion of state surveillance has raised serious privacy concerns.",
                         "Davlat kuzatuvining kengayishi shaxsiy hayot bo‘yicha jiddiy xavotir uyg‘otdi.")],
        "related":     [("privacy", "kuzatuv va maxfiylik — doim juftlashadigan qarama-qarshilik")],
    },
    {
        "word":        "privacy",
        "roots":       [],
        "pos":         "noun",
        "topic":       "media",
        "level":       4,
        "freq":        2,
        "meaning":     "shaxsiy hayot daxlsizligi, maxfiylik",
        "collocation": "invade privacy · privacy concerns · the right to privacy",
        "note":        "<p>⚠️ Sanalmaydigan. Fe’l birikmasi — <b>invade somebody’s privacy</b>.</p>",
        "examples":    [("Social media platforms have been criticised for invading users’ privacy.",
                         "Ijtimoiy tarmoq platformalari foydalanuvchilar maxfiyligini buzgani uchun tanqid qilindi.")],
        "related":     [("surveillance", "maxfiylik kuzatuv kuchayganda yo‘qoladi")],
    },
    {
        "word":        "misinformation",
        "roots":       ["-ion"],
        "pos":         "noun",
        "topic":       "media",
        "level":       6,
        "freq":        2,
        "meaning":     "noto‘g‘ri axborot — tarqalayotgan yolg‘on ma’lumot",
        "collocation": "the spread of misinformation · combat misinformation · online misinformation",
        "note":        "<p>⚠️ Sanalmaydigan. <b>the spread of misinformation</b> — ijtimoiy "
                       "tarmoqlar mavzusidagi eng kuchli salbiy dalil.</p>",
        "examples":    [("The rapid spread of misinformation online undermines public trust.",
                         "Internetda noto‘g‘ri axborotning tez tarqalishi jamoatchilik ishonchini yemiradi.")],
        "related":     [("undermine", "noto‘g‘ri axborot ishonchni yemiradi")],
    },
    {
        "word":        "digital divide",
        "roots":       [],
        "pos":         "phrase",
        "topic":       "society",
        "level":       6,
        "freq":        1,
        "meaning":     "raqamli tafovut — internetdan foydalana oladigan va olmaydiganlar orasidagi farq",
        "collocation": "bridge the digital divide · widen the digital divide",
        "note":        "<p>Onlayn ta’lim va texnologiya mavzularida eng kuchli qarshi dalil: "
                       "<i>online learning risks <b>widening the digital divide</b></i>.</p>",
        "examples":    [("Remote learning has widened the digital divide between rich and poor pupils.",
                         "Masofaviy ta’lim boy va kambag‘al o‘quvchilar orasidagi raqamli tafovutni kengaytirdi.")],
        "related":     [("inequality", "raqamli tafovut — tengsizlikning yangi shakli")],
    },
    {
        "word":        "efficient",
        "roots":       [],
        "pos":         "adj",
        "topic":       "science",
        "level":       3,
        "freq":        3,
        "meaning":     "samarali — kam resurs bilan ko‘p natija beradigan",
        "collocation": "energy-efficient · more efficient use of · improve efficiency",
        "note":        "<p><b>energy-efficient</b> va <b>fuel-efficient</b> — ekologiya "
                       "yechimlarining tayyor sifatlari. Oti — <b>efficiency</b>.</p>",
        "examples":    [("Energy-efficient buildings can cut heating costs by up to 40%.",
                         "Energiya tejaydigan binolar isitish xarajatini 40% gacha kamaytirishi mumkin.")],
        "synonyms":    [("effective", "efficient = kam resurs bilan; effective = maqsadga erishadi")],
    },
    {
        "word":        "effective",
        "roots":       [],
        "pos":         "adj",
        "topic":       "academic",
        "level":       3,
        "freq":        3,
        "meaning":     "samarali, natija beradigan — maqsadga erishadigan",
        "collocation": "an effective solution · prove effective · the most effective way to",
        "note":        "<p>⚠️ <b>effective</b> (natija beradi) ≠ <b>efficient</b> (tejamli). "
                       "Task 2 xulosasida: <i>the most <b>effective</b> long-term solution</i>.</p>",
        "examples":    [("Public awareness campaigns have proved surprisingly effective.",
                         "Aholi xabardorligini oshirish kampaniyalari kutilmaganda samarali bo‘ldi.")],
        "synonyms":    [("efficient", "effective = ishlaydi; efficient = arzon va tez ishlaydi")],
    },
    {
        "word":        "alternative",
        "roots":       [],
        "pos":         "noun",
        "topic":       "science",
        "level":       3,
        "freq":        3,
        "meaning":     "muqobil — o‘rniga ishlatiladigan variant",
        "collocation": "a viable alternative to · alternative energy sources · offer an alternative",
        "note":        "<p>Predlogi <b>to</b>: <i>an alternative <b>to</b> private cars</i> "
                       "(❌ alternative of). Yechim taklif qilishning eng qulay shakli.</p>",
        "examples":    [("Cycling offers a practical alternative to short car journeys.",
                         "Velosiped qisqa avtosafarlarga amaliy muqobil taklif qiladi.")],
        "related":     [("viable", "«a viable alternative» — tayyor birikma")],
    },
]

# The list is already in the order the table should show, so stamp this group's
# `order` decade on it here rather than repeating a number in every dict.
# Decades are allocated in toc_ielts_vocab.txt — keep them unique per file, or
# two groups interleave in the table.
for _i, _word in enumerate(WORDS):
    _word.setdefault("order", 700 + _i)
