# Generated by Django 6.0.3 on 2026-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_practice_is_available_for_all"),
        ("tutorial", "0002_tutorialreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="practices",
            field=models.ManyToManyField(
                blank=True, related_name="tutorials", to="practice.practice"
            ),
        ),
    ]
