# Generated by Django 6.0.3 on 2026-07-25 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0004_alter_tutorial_category_tutorialplaylist_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="category",
            field=models.CharField(
                choices=[
                    ("math", "Mathematics"),
                    ("korean", "Korean"),
                    ("programming", "Programming"),
                    ("english", "English"),
                    ("japanese", "Japanese"),
                    ("russian", "Russian"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tutorialplaylist",
            name="category",
            field=models.CharField(
                choices=[
                    ("math", "Mathematics"),
                    ("korean", "Korean"),
                    ("programming", "Programming"),
                    ("english", "English"),
                    ("japanese", "Japanese"),
                    ("russian", "Russian"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TutorialProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_awarded", models.PositiveSmallIntegerField(default=4)),
                ("finished_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="tutorial.tutorial",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tutorial")},
            },
        ),
    ]
