# Generated by Django 6.0.3 on 2026-08-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corner", "0007_remove_writingpracticeprogress_practice_and_more"),
        ("tutorial", "0005_alter_tutorial_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorial",
            name="stories",
            field=models.ManyToManyField(
                blank=True, related_name="tutorials", to="corner.story"
            ),
        ),
    ]
