# -*- coding: utf-8 -*-
"""GMAT Focus Edition — PrimePoint Mock 1 — Data Insights (20 questions, 45 min).

Rules: exam/data/STYLE_GUIDE_GMAT_MOCK.md. Blueprint: Data Sufficiency 7 (1–7) ·
Table Analysis 3 (8–10) · Graphics Interpretation 4 (11–14) · Two-Part Analysis 3 (15–17) ·
Multi-Source Reasoning 3 (18–20). The multi-part formats are rebuilt as single-answer
questions (as in Prime GMAT): a table/chart question asks one thing; a two-part question
offers one PAIR per choice. Tables and charts are generated by
tutorial/management/commands/_dikit.py — never hand-typed.
The companies, regions' figures, museum and shipping rates are invented for the exam.
Answer gate: verify_gmat_mock1_di.py (scratchpad) re-derives every DS verdict from world
models and recomputes every other key from the numbers parsed back out of the HTML.

    python manage.py load_mock exam/data/gmat1_di.py --expect-questions=20
"""
import importlib.util
import os

_KIT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    '..', '..', 'tutorial', 'management', 'commands', '_dikit.py')
_spec = importlib.util.spec_from_file_location('_dikit', _KIT)
kit = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(kit)

EXAM_META = {
    'title': 'GMAT Focus Edition — PrimePoint Mock 1',
    'language': 'english',
    'exam_format': 'gmat',
    'exam_number': 301,
    'is_published': True,
}

MODULES = [
    {'code': 'quant', 'kind': 'quant', 'stage': 1, 'order': 1, 'minutes': 45,
     'label': 'Quantitative Reasoning', 'label_uz': 'Miqdoriy mulohaza'},
    {'code': 'verbal', 'kind': 'verbal', 'stage': 1, 'order': 2, 'minutes': 45,
     'label': 'Verbal Reasoning', 'label_uz': 'Ogʻzaki mulohaza'},
    {'code': 'di', 'kind': 'di', 'stage': 1, 'order': 3, 'minutes': 45, 'calculator': True,
     'label': 'Data Insights', 'label_uz': 'Maʼlumotlar tahlili'},
]

DS, TA, GI, TPA, MSR = ('Data Sufficiency', 'Table Analysis', 'Graphics Interpretation',
                        'Two-Part Analysis', 'Multi-Source Reasoning')

DS_CHOICES = [
    "Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.",
    "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.",
    "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.",
    "EACH statement ALONE is sufficient.",
    "Statements (1) and (2) TOGETHER are NOT sufficient.",
]
DS_NAMES = ['faqat (1) yetarli', 'faqat (2) yetarli', 'faqat ikkalasi birga yetarli',
            'har biri alohida yetarli', 'ikkalasi birga ham yetarli emas']


def ds(number, difficulty, stem, s1, s2, verdict, explanation):
    """verdict: 1–5 in the standard order. The explanation names the verdict, never a letter."""
    text = (f'<p>{stem}</p><p>(1) {s1}</p><p>(2) {s2}</p>'
            '<p class="small text-muted">Data Sufficiency: decide whether the data given are '
            'sufficient to answer the question.</p>')
    return {'section': 'di', 'number': number, 'skill': DS, 'difficulty': difficulty,
            'question_text': text, 'choices': DS_CHOICES, 'correct': verdict,
            'explanation': f'<p>{explanation} Javob: <strong>{DS_NAMES[verdict - 1]}</strong>.</p>'}


def q(number, skill, difficulty, passage, stem, choices, correct, explanation):
    return {'section': 'di', 'number': number, 'skill': skill, 'difficulty': difficulty,
            'passage': passage, 'question_text': f'<p><strong>{stem}</strong></p>',
            'choices': choices, 'correct': correct, 'explanation': f'<p>{explanation}</p>'}


# ── Shared data ───────────────────────────────────────────────────────────────
REGIONS = ['Tashkent', 'Samarkand', 'Fergana', 'Bukhara', 'Khorezm']
SALES_2024 = [48.0, 21.5, 18.0, 12.4, 9.6]
SALES_2025 = [55.2, 23.0, 16.2, 15.5, 10.8]
STORES_2025 = [120, 64, 58, 40, 32]
TABLE = ('<p>The table shows the beverage sales of Company Z in five regions.</p>' + kit.table(
    ['Region', 'Sales 2024 ($ million)', 'Sales 2025 ($ million)', 'Stores (2025)'],
    [[r, a, b, s] for r, a, b, s in zip(REGIONS, SALES_2024, SALES_2025, STORES_2025)]))

MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
VISITORS = [12, 15, 21, 30, 27, 33]
BARS = kit.bar_chart(MONTHS, VISITORS, 40, 10,
                     'Visitors to the Riverside Museum, January–June (thousands)',
                     'Bar chart of monthly museum visitors in thousands', unit='')

YEARS = ['2019', '2020', '2021', '2022', '2023', '2024', '2025']
PRICE = [40, 44, 38, 50, 55, 52, 65]
LINE = kit.line_chart(YEARS, PRICE, 70, 10,
                      'Share price of Orion Ltd at year-end, 2019–2025 (dollars)',
                      'Line chart of the year-end share price in dollars', unit='')

MEMO = ('<p><strong>Source 1 — Memo.</strong> Lotus Textiles ships fabric from Tashkent to a client in Riga. '
        'It can ship by rail (14 days), by truck (9 days) or by air (2 days). The client requires delivery '
        'within 10 days for any order heavier than 2 tonnes, and accepts any option for lighter orders. '
        'Orders heavier than 5 tonnes cannot be shipped by air.</p>')
RATES = ('<p><strong>Source 2 — Rates.</strong></p>' + kit.table(
    ['Option', 'Cost per tonne ($)', 'Fixed fee per shipment ($)'],
    [['Rail', 180, 400], ['Truck', 260, 300], ['Air', 1450, 150]]))
SOURCES = MEMO + RATES


QUESTIONS = [
    # ═══ Data Sufficiency ═════════════════════════════════════════════════
    ds(1, 'easy', 'What is the value of x?',
       '3x + 2y = 12', 'x − y = −1', 3,
       'Har bir tenglama alohida ikki nomaʼlumli — x ni aniqlamaydi. Birga: x = y − 1 ni '
       'birinchisiga qoʻysak, 5y − 3 = 12, y = 3, x = 2 — yagona qiymat.'),

    ds(2, 'medium', 'Is the integer n odd?',
       'n<sup>2</sup> + n is even.', 'n<sup>2</sup> − 2n is odd.', 2,
       '(1): n<sup>2</sup> + n = n(n + 1) — har qanday butun son uchun juft, hech narsa demaydi. '
       '(2): n<sup>2</sup> − 2n = n(n − 2) toq boʻlishi uchun ikkala koʻpaytuvchi toq boʻlishi kerak — '
       'demak n toq. Yetarli.'),

    ds(3, 'medium', 'A store sold 120 shirts in March, some at full price and the rest at a discount. '
       'How many shirts did it sell at full price?',
       'The store\'s revenue from shirts in March was $3,000.',
       'Each full-price shirt sold for $30 and each discounted shirt sold for $20.', 3,
       '(1) narxlarni bermaydi; (2) tushumni bermaydi. Birga: 30f + 20(120 − f) = 3,000 → '
       '10f = 600 → f = 60.'),

    ds(4, 'easy', 'What is the average (arithmetic mean) of a, b and c?',
       'a + b = 14 and c = 10.', 'a + b + 2c = 34.', 1,
       '(1): a + b + c = 24, oʻrtacha 8 — yetarli. (2): a + b + 2c = 34 dan a + b + c ni topib '
       'boʻlmaydi (masalan, c = 10 da 24, c = 12 da 22). Yetarli emas.'),

    ds(5, 'hard', 'Is x &gt; y?',
       'x − y &gt; −2', 'x<sup>2</sup> &gt; y<sup>2</sup>', 5,
       'Ikkalasini qanoatlantiradigan ikki misol: x = 1, y = 0 — ha; x = −1, y = 0 — '
       '(−1 − 0 = −1 &gt; −2 va 1 &gt; 0), lekin x &gt; y emas. Javob bir xil emas.'),

    ds(6, 'medium', 'If n is a positive integer, what is the remainder when n is divided by 6?',
       'n is divisible by 3, and n is odd.', 'n + 3 is divisible by 6.', 4,
       '(1): 3 ga boʻlinadigan toq son — 3, 9, 15… — hammasi 6 ga boʻlganda 3 qoldiq beradi. '
       '(2): n + 3 = 6k → n = 6k − 3 → qoldiq 3. Har biri alohida yetarli.'),

    ds(7, 'hard', 'What is the capacity, in liters, of a water tank?',
       'The tank is now more than half full.',
       'If 30 liters were added to the water now in the tank, the tank would be 70 percent full; '
       'if instead 20 liters were removed, it would be 50 percent full.', 2,
       '(1) faqat «yarmidan koʻp» deydi — sigʻim istalgancha boʻlishi mumkin. (2): hozirgi suv w: w + 30 = 0.7C va w − 20 = 0.5C → ayirsak '
       '50 = 0.2C → C = 250. Yetarli — (1) siz.'),

    # ═══ Table Analysis ═══════════════════════════════════════════════════
    q(8, TA, 'medium', TABLE,
      'Which region had the greatest percentage increase in sales from 2024 to 2025?',
      REGIONS, 4,
      'Oʻsish foizlari: Tashkent 15%, Samarkand ≈ 7%, Fergana −10%, Bukhara ≈ 25%, Khorezm 12.5%. '
      'Eng katta — <strong>Bukhara</strong>. Tuzoq: Tashkent — eng katta <b>mutlaq</b> oʻsish (7.2 mln), '
      'lekin foizda emas.'),

    q(9, TA, 'medium', TABLE,
      'In 2025, which region had the highest sales per store?',
      REGIONS, 1,
      '2025-yilda bir doʻkonga: Tashkent 55.2 ÷ 120 = 0.46, Samarkand ≈ 0.36, Fergana ≈ 0.28, '
      'Bukhara ≈ 0.39, Khorezm ≈ 0.34 (mln $). Eng yuqori — <strong>Tashkent</strong>.'),

    q(10, TA, 'hard', TABLE,
      'Total sales of the five regions increased by approximately what percent from 2024 to 2025?',
      ['6%', '8%', '10%', '12%', '14%'], 3,
      'Jami 2024: 109.5; jami 2025: 120.7. Oʻsish 11.2 ÷ 109.5 ≈ 10.2% — taxminan '
      '<strong>10%</strong>. Eslatma: mintaqalar foizlarining oddiy oʻrtachasi (≈ 9.9%) bu safar '
      'yaqin chiqdi, lekin bu tasodif — doim jami miqdorlarni solishtiring.'),

    # ═══ Graphics Interpretation ══════════════════════════════════════════
    q(11, GI, 'medium', BARS,
      'In which month did the number of visitors increase by the greatest percentage over the previous month?',
      ['February', 'March', 'April', 'May', 'June'], 3,
      'Oʻsishlar: Feb +25%, Mar +40%, Apr +42.9% (21 → 30), May −10%, Jun +22.2%. '
      'Eng katta foiz — <strong>April</strong>. Tuzoq: March (+40%) — juda yaqin, lekin '
      'aprel 42.9% bilan biroz yuqori; taxmin emas, hisoblang.'),

    q(12, GI, 'easy', BARS,
      'The average (arithmetic mean) number of visitors per month from January to June was closest to ____ thousand.',
      ['19', '20', '21', '22', '23'], 5,
      'Yigʻindi 12 + 15 + 21 + 30 + 27 + 33 = 138; 138 ÷ 6 = <strong>23</strong> ming.'),

    q(13, GI, 'medium', LINE,
      'The greatest increase in the share price between two consecutive year-ends occurred from ____.',
      ['2019 to 2020', '2021 to 2022', '2022 to 2023', '2023 to 2024', '2024 to 2025'], 5,
      'Farqlar: +4, −6, +12, +5, −3, +13. Eng katta oʻsish — <strong>2024 to 2025</strong> (+13). '
      'Tuzoq: 2021 to 2022 (+12) — eng tik koʻrinadi, lekin 1 dollar kam.'),

    q(14, GI, 'medium', LINE,
      'From year-end 2019 to year-end 2025, the share price increased by ____ percent.',
      ['25', '37.5', '50', '62.5', '65'], 4,
      '(65 − 40) ÷ 40 = 0.625 = <strong>62.5</strong>%. Tuzoq: 25 — farqni dollarda berish; 65 — '
      'oxirgi narxni foiz deb olish.'),

    # ═══ Two-Part Analysis ════════════════════════════════════════════════
    q(15, TPA, 'medium',
      '<p>A caterer charges a fixed fee per event plus the same charge for each guest. An event for 40 guests '
      'costs $1,300 and an event for 70 guests costs $2,050.</p>',
      'Select the fixed fee and the charge per guest that are consistent with this information.',
      [kit.pair('Fixed fee', '$250', 'Per guest', '$26.25'),
       kit.pair('Fixed fee', '$300', 'Per guest', '$25'),
       kit.pair('Fixed fee', '$300', 'Per guest', '$30'),
       kit.pair('Fixed fee', '$500', 'Per guest', '$20'),
       kit.pair('Fixed fee', '$550', 'Per guest', '$25')], 2,
      'Har mehmon: (2,050 − 1,300) ÷ 30 = 25. Qatʼiy toʻlov: 1,300 − 40 × 25 = 300. '
      'Juft: <strong>$300 va $25</strong>. Tuzoq: $250/$26.25 va $500/$20 — faqat birinchi tadbirga mos, '
      'ikkinchisiga emas; ikki qismli savolda ikkala shart ham tekshiriladi.'),

    q(16, TPA, 'hard',
      '<p>A train travels from City A to City B at an average speed of 90 kilometers per hour and returns along '
      'the same route at an average speed of 60 kilometers per hour. The two journeys take 5 hours in total.</p>',
      'Select the distance from City A to City B and the average speed for the whole round trip.',
      [kit.pair('Distance', '180 km', 'Average speed', '72 km/h'),
       kit.pair('Distance', '180 km', 'Average speed', '75 km/h'),
       kit.pair('Distance', '150 km', 'Average speed', '72 km/h'),
       kit.pair('Distance', '200 km', 'Average speed', '75 km/h'),
       kit.pair('Distance', '150 km', 'Average speed', '60 km/h')], 1,
      'd/90 + d/60 = 5 → (2d + 3d)/180 = 5 → d = 180. Oʻrtacha tezlik: 360 ÷ 5 = 72. '
      'Juft: <strong>180 km va 72 km/h</strong>. Tuzoq: 75 — tezliklarning oddiy oʻrtachasi.'),

    q(17, TPA, 'hard',
      '<p>The integers x and y satisfy x + y = 10 and x − y ≥ 4.</p>',
      'Select the values of x and y for which the product xy is as large as possible.',
      [kit.pair('x', '5', 'y', '5'),
       kit.pair('x', '6', 'y', '4'),
       kit.pair('x', '8', 'y', '2'),
       kit.pair('x', '7', 'y', '3'),
       kit.pair('x', '9', 'y', '1')], 4,
      'x − y ≥ 4 va x + y = 10 → 2x ≥ 14 → x ≥ 7. xy = x(10 − x) x oshgan sari kamayadi '
      '(x ≥ 5 da), shuning uchun eng kattasi x = 7: <strong>x = 7, y = 3</strong>, xy = 21. '
      'Tuzoq: 5 va 5 (xy = 25) — eng katta koʻpaytma, lekin x − y ≥ 4 shartini buzadi.'),

    # ═══ Multi-Source Reasoning ═══════════════════════════════════════════
    q(18, MSR, 'medium', SOURCES,
      'For a 3-tonne order, which option meets the client\'s requirements at the lowest cost?',
      ['Rail, at $940', 'Truck, at $1,080', 'Air, at $4,500', 'Truck, at $780', 'Rail, at $1,080'], 2,
      '3 tonna &gt; 2 tonna, demak 10 kun ichida — temir yoʻl (14 kun) mos emas. Yuk mashinasi: '
      '3 × 260 + 300 = 1,080; havo: 3 × 1,450 + 150 = 4,500. Eng arzon mos variant — '
      '<strong>Truck, $1,080</strong>. Tuzoq: Rail, $940 — eng arzon, lekin muddat shartini buzadi; '
      'Truck, $780 — qatʼiy toʻlovni unutish.'),

    q(19, MSR, 'easy', SOURCES,
      'For an order of 1.5 tonnes, what is the cost of the cheapest option?',
      ['$600', '$670', '$690', '$735', '$2,325'], 2,
      '1.5 tonna — har qanday variant mos. Rail: 1.5 × 180 + 400 = 670; Truck: 390 + 300 = 690; '
      'Air: 2,175 + 150 = 2,325. Eng arzon — <strong>$670</strong>. Tuzoq: $690 — qatʼiy toʻlov '
      'kichikroq boʻlgani uchun yuk mashinasini arzon deb oʻylash.'),

    q(20, MSR, 'hard', SOURCES,
      'For an order of 6 tonnes, which option is the cheapest one that meets all of the requirements?',
      ['Rail, at $1,480', 'Truck, at $1,560', 'Truck, at $1,860', 'Air, at $8,850',
       'No option meets all of the requirements'], 3,
      '6 tonna: 5 tonnadan ogʻir — havo mumkin emas; 2 tonnadan ogʻir — 10 kun ichida, temir yoʻl mumkin emas. '
      'Qoladi yuk mashinasi: 6 × 260 + 300 = <strong>$1,860</strong>. Tuzoq: Truck, $1,560 — '
      'qatʼiy toʻlovsiz; Rail, $1,480 — eng arzon, lekin 14 kun.'),
]
