# Generated by Django 6.0.3 on 2026-04-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0001_initial"),
        ("masters", "0002_alter_master_profile"),
        ("panda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PandaGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panda_groups",
                        to="masters.master",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="panda.panda"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("master", "name")},
            },
        ),
    ]
