# Generated by Django 6.0.3 on 2026-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_pandagroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="description",
        ),
        migrations.RemoveField(
            model_name="homework",
            name="homework_type",
        ),
        migrations.RemoveField(
            model_name="homeworkassignment",
            name="notes",
        ),
        migrations.AddField(
            model_name="homework",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Optional instructions shown to students."
            ),
        ),
    ]
