# Generated by Django 6.0.3 on 2026-08-23 18:06

import django.db.models.deletion
from django.db import migrations, models


def carry_the_practice_over(apps, schema_editor):
    """Old homeworks pointed at exactly one practice; move it into the new
    many-to-many before the column goes away.

    Runs before the RemoveField below on purpose — the field has to still
    exist for there to be anything to read.
    """
    Homework = apps.get_model("homework", "Homework")
    for homework in Homework.objects.exclude(practice__isnull=True).iterator():
        homework.practices.add(homework.practice_id)


def adopt_into_classrooms(apps, schema_editor):
    """Give every old homework the classroom it was already attached to.

    Homework predates the move into classrooms, but a lesson could already
    pin one to itself (`classroom.Lesson.homeworks`), and that link says which
    room it belonged to. Anything with no such link stays classroom-less and
    keeps showing up in the pupil's inbox — it just has no room page.
    """
    Homework = apps.get_model("homework", "Homework")
    Lesson = apps.get_model("classroom", "Lesson")
    for lesson in Lesson.objects.prefetch_related("homeworks"):
        for homework in lesson.homeworks.all():
            if homework.classroom_id is None:
                homework.classroom_id = lesson.classroom_id
                homework.save(update_fields=["classroom"])


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0004_classroom_subject_classroomresource"),
        ("corner", "0007_remove_writingpracticeprogress_practice_and_more"),
        ("examprep", "0011_alter_grammarpoint_category_and_more"),
        ("homework", "0003_remove_homework_description_and_more"),
        ("practice", "0006_subject_icon"),
        ("tutorial", "0006_tutorial_stories"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                help_text="The classroom this homework was set in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeworks",
                to="classroom.classroom",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="exam_lessons",
            field=models.ManyToManyField(
                blank=True, related_name="homeworks", to="examprep.lesson"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="practices",
            field=models.ManyToManyField(
                blank=True, related_name="homeworks", to="practice.practice"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="stories",
            field=models.ManyToManyField(
                blank=True, related_name="homeworks", to="corner.story"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="tutorials",
            field=models.ManyToManyField(
                blank=True, related_name="homeworks", to="tutorial.tutorial"
            ),
        ),
        migrations.RunPython(carry_the_practice_over, migrations.RunPython.noop),
        migrations.RunPython(adopt_into_classrooms, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="homework",
            name="practice",
        ),
    ]
