# Generated by Django 6.0.3 on 2026-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0004_remove_homework_practice_homework_classroom_and_more"),
        ("workbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="workbooks",
            field=models.ManyToManyField(
                blank=True, related_name="homeworks", to="workbook.workbook"
            ),
        ),
    ]
