# Generated by Django 6.0.3 on 2026-05-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Yet"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
