# Generated by Django 6.0.3 on 2026-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0002_lesson_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="youtube_url",
            field=models.URLField(
                blank=True, help_text="Optional YouTube video URL for this lesson."
            ),
        ),
    ]
