# Generated by Django 6.0.3 on 2026-08-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0003_add_youtube_url_to_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="subject",
            field=models.CharField(
                blank=True,
                choices=[
                    ("english", "English"),
                    ("korean", "Korean"),
                    ("math", "Math"),
                    ("russian", "Russian"),
                ],
                help_text="What this classroom teaches. Narrows every homework picker to that subject. Leave blank to see everything.",
                max_length=30,
                verbose_name="Subject",
            ),
        ),
        migrations.CreateModel(
            name="ClassroomResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("link", "Link"),
                            ("video", "Video"),
                        ],
                        default="link",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="Note"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="A YouTube video, a Google Doc, a Telegram group…",
                        verbose_name="Link",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="classroom/resources/",
                        verbose_name="File",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="classroom.classroom",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
