# Generated by Django 6.0.3 on 2026-04-21 10:04

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_specialty'),
        ('panda', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='testset',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='testset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testset',
            name='creator',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('math', 'Math'), ('english', 'English'), ('korean', 'Korean'), ('sat', 'SAT'), ('gmat', 'GMAT'), ('gre', 'GRE'), ('it', 'IT')], max_length=20)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('real', 'Real')], default='medium', max_length=20)),
                ('purpose', models.CharField(choices=[('homework', 'Homework'), ('summary', 'Summary'), ('test', 'Test')], default='test', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='masters.master')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('panda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='panda.panda')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practice')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Question Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='practice_images/')),
                ('choice1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 1')),
                ('choice2', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Choice 2')),
                ('choice3', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Choice 3')),
                ('choice4', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Choice 4')),
                ('choice5', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Choice 5')),
                ('correct_answer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('is_multiple_choice', models.BooleanField(default=False, help_text='Check if multiple answers are allowed')),
                ('explanation', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Explanation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.practice')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='practice.practiceattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practicequestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='TestSet',
        ),
    ]
