# Generated by Django 6.0.3 on 2026-04-23 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_alter_master_profile"),
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicequestion",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="practice",
            name="shuffle_choices",
        ),
        migrations.RemoveField(
            model_name="practice",
            name="shuffle_questions",
        ),
        migrations.AlterField(
            model_name="practice",
            name="level",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="max_attempts",
            field=models.PositiveIntegerField(
                default=1, help_text="Set to 0 for unlimited attempts."
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="practice.subject",
            ),
        ),
        migrations.AlterField(
            model_name="practice",
            name="time_limit",
            field=models.PositiveIntegerField(
                blank=True, help_text="Minutes. Leave blank for no limit.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="practiceattempt",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="practice.practice",
            ),
        ),
        migrations.AlterField(
            model_name="practicequestion",
            name="made_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="masters.master",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="practice.practicequestion",
            ),
        ),
        migrations.AlterField(
            model_name="useranswer",
            name="selected_choices",
            field=models.ManyToManyField(blank=True, to="practice.practicechoice"),
        ),
    ]
