# Generated by Django 6.0.3 on 2026-04-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_remove_shuffle_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="is_available_for_all",
            field=models.BooleanField(
                default=False,
                help_text="Allow other masters to assign this as homework.",
            ),
        ),
    ]
