# Generated by Django 6.0.3 on 2026-04-21 16:27

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_remove_choice_question_remove_question_creator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="purpose",
        ),
        migrations.RemoveField(
            model_name="practice",
            name="type",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="choice1",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="choice2",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="choice3",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="choice4",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="choice5",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="is_multiple_choice",
        ),
        migrations.RemoveField(
            model_name="practicequestion",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="selected_choice",
        ),
        migrations.AddField(
            model_name="practice",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practice",
            name="max_attempts",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="practice",
            name="pass_score",
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name="practice",
            name="show_answers_after",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="practice",
            name="shuffle_choices",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practice",
            name="shuffle_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practice",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="practice.subject",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="time_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practiceattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="hint",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="points",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="practice",
            name="level",
            field=models.CharField(default="medium", max_length=20),
        ),
        migrations.AlterField(
            model_name="practicequestion",
            name="explanation",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="practicequestion",
            name="question_text",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="PracticeChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", django_ckeditor_5.fields.CKEditor5Field()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="practice.practicequestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="useranswer",
            name="selected_choices",
            field=models.ManyToManyField(to="practice.practicechoice"),
        ),
    ]
