# Generated by Django 6.0.3 on 2026-04-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0004_remove_master_specialty"),
        ("practice", "0003_remove_practice_purpose_remove_practice_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicequestion",
            name="made_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="masters.master",
            ),
        ),
    ]
