# Generated by Django 6.0.3 on 2026-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_practice_is_available_for_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="practiceattempt",
            name="rating_points",
            field=models.FloatField(
                default=0, help_text="Rating points awarded for this attempt."
            ),
        ),
    ]
