# Generated by Django 6.0.3 on 2026-04-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_alter_practicequestion_made_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicechoice",
            name="text",
            field=models.TextField(),
        ),
    ]
