# Generated by Django 6.0.3 on 2026-06-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_subject_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="icon",
            field=models.CharField(
                default="bi-journal-bookmark-fill",
                help_text="Bootstrap Icon class, e.g. bi-calculator, bi-translate, bi-flask",
                max_length=50,
            ),
        ),
    ]
