# Generated by Django 6.0.3 on 2026-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0006_subject_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicequestion",
            name="fixed_order",
            field=models.BooleanField(
                default=False,
                help_text="Show the choices in the order they were written instead of shuffled (e.g. GMAT Data Sufficiency, whose five answers are always A–E).",
            ),
        ),
    ]
