# Generated by Django 6.0.3 on 2026-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_people_email_remove_people_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
