# Generated by Django 6.0.3 on 2026-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_people_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
