# Generated by Django 6.0.3 on 2026-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_people_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_cofounder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='people',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
