# Generated by Django 6.0.3 on 2026-07-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="study_subjects",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
