# Generated by Django 6.0.3 on 2026-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KoreanWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=30)),
                ("clue_korean", models.TextField()),
                ("clue_uzbek", models.TextField()),
            ],
            options={
                "ordering": ["word"],
            },
        ),
        migrations.CreateModel(
            name="CrosswordPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("grid_data", models.JSONField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("words", models.ManyToManyField(blank=True, to="games.koreanword")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
