# Generated by Django 6.0.3 on 2026-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosswordpuzzle",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="crossword/"),
        ),
    ]
