# Generated by Django 6.0.3 on 2026-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_crosswordpuzzle_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosswordpuzzle",
            name="grid_size",
            field=models.IntegerField(
                choices=[
                    (10, "10 × 10"),
                    (12, "12 × 12"),
                    (13, "13 × 13"),
                    (15, "15 × 15"),
                    (17, "17 × 17"),
                    (20, "20 × 20"),
                ],
                default=15,
                help_text="Working grid size — larger allows more words but creates a bigger puzzle.",
            ),
        ),
    ]
