# Generated by Django 6.0.3 on 2026-05-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_crosswordpuzzle_grid_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crosswordpuzzle",
            name="words",
        ),
        migrations.RemoveField(
            model_name="crosswordpuzzle",
            name="grid_size",
        ),
        migrations.AddField(
            model_name="crosswordpuzzle",
            name="grid_cols",
            field=models.IntegerField(default=8, help_text="Width of the grid (1–10)."),
        ),
        migrations.AddField(
            model_name="crosswordpuzzle",
            name="grid_rows",
            field=models.IntegerField(
                default=10, help_text="Height of the grid (1–20)."
            ),
        ),
        migrations.DeleteModel(
            name="KoreanWord",
        ),
    ]
