# Generated by Django 6.0.3 on 2026-05-27 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_wordorderchallenge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OddOneOutPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ko", "Korean"),
                            ("uz", "Uzbek"),
                            ("any", "Mixed"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oddoneout_packs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OddOneOutQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_1", models.CharField(max_length=120)),
                ("word_2", models.CharField(max_length=120)),
                ("word_3", models.CharField(max_length=120)),
                ("word_4", models.CharField(max_length=120)),
                (
                    "odd_index",
                    models.PositiveSmallIntegerField(
                        help_text="0-based index of the odd word (0=word_1, 1=word_2, …)"
                    ),
                ),
                ("explanation", models.CharField(blank=True, max_length=400)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="games.oddoneoutpack",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
    ]
