# Generated by Django 6.0.3 on 2026-05-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_oddoneout"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordorderchallenge",
            options={"ordering": ["language", "difficulty", "pk"]},
        ),
        migrations.AddField(
            model_name="wordorderchallenge",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="wordorderchallenge",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ko", "Korean"), ("uz", "Uzbek")],
                default="en",
                max_length=10,
            ),
        ),
    ]
