# Generated by Django 6.0.3 on 2026-05-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_alter_wordorderchallenge_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishCrossword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="crossword_en/"),
                ),
                (
                    "grid_rows",
                    models.IntegerField(
                        default=15, help_text="Height of the grid (1–25)."
                    ),
                ),
                (
                    "grid_cols",
                    models.IntegerField(
                        default=15, help_text="Width of the grid (1–25)."
                    ),
                ),
                ("grid_data", models.JSONField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "English Crossword",
                "verbose_name_plural": "English Crosswords",
                "ordering": ["-created_at"],
            },
        ),
    ]
