# Generated by Django 6.0.3 on 2026-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0011_english_crossword"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordSearchPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "word_list",
                    models.TextField(
                        help_text="One word per line (English letters only)."
                    ),
                ),
                (
                    "grid_size",
                    models.IntegerField(
                        default=15, help_text="Grid width/height (10–20)."
                    ),
                ),
                ("grid_data", models.JSONField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Word Search Puzzle",
                "verbose_name_plural": "Word Search Puzzles",
                "ordering": ["-created_at"],
            },
        ),
    ]
