# Generated by Django 6.0.3 on 2026-06-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_mathsquarepuzzle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mathsquarepuzzle",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                    ("ultra", "Ultra-hard"),
                ],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mathsquarepuzzle",
            name="size",
            field=models.IntegerField(
                default=2, help_text="Numbers per row/column (N): 2–5."
            ),
        ),
    ]
