# Generated by Django 6.0.3 on 2026-07-18 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_alter_mathsquarepuzzle_difficulty_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MathChampResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        choices=[(5, "5-sinf"), (6, "6-sinf"), (7, "7-sinf")], default=5
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("stage_reached", models.PositiveSmallIntegerField(default=1)),
                ("finished", models.BooleanField(default=False)),
                ("hearts_left", models.PositiveSmallIntegerField(default=0)),
                ("best_streak", models.PositiveSmallIntegerField(default=0)),
                (
                    "elapsed",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds from start to finish."
                    ),
                ),
                (
                    "medal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("", "None"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mathchamp_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "elapsed"],
            },
        ),
    ]
