# Generated by Django 6.0.3 on 2026-08-10 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_englishchampresult"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DuelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("duel", "Duel"), ("together", "Together")],
                        default="duel",
                        max_length=10,
                    ),
                ),
                ("name_a", models.CharField(max_length=40)),
                ("name_b", models.CharField(max_length=40)),
                (
                    "subject_a",
                    models.CharField(
                        blank=True,
                        choices=[("math", "Matematika"), ("english", "Ingliz tili")],
                        help_text="Together mode: what this pupil studies.",
                        max_length=10,
                    ),
                ),
                (
                    "subject_b",
                    models.CharField(
                        blank=True,
                        choices=[("math", "Matematika"), ("english", "Ingliz tili")],
                        max_length=10,
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Math difficulty (5-7)."
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        default="a1",
                        help_text="English level (a1/a2/b1).",
                        max_length=2,
                    ),
                ),
                ("score_a", models.IntegerField(default=0)),
                ("score_b", models.IntegerField(default=0)),
                ("hearts_a", models.PositiveSmallIntegerField(default=0)),
                ("hearts_b", models.PositiveSmallIntegerField(default=0)),
                ("stages_done", models.PositiveSmallIntegerField(default=0)),
                ("finished", models.BooleanField(default=False)),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("a", "A"), ("b", "B"), ("", "Draw / co-op")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "elapsed",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds from start to finish."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duel_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
