# Generated by Django 6.0.3 on 2026-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0017_duelresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="duelresult",
            name="limit_english",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Seconds per English question; 0 = no limit."
            ),
        ),
        migrations.AddField(
            model_name="duelresult",
            name="limit_math",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Seconds per math question; 0 = no limit."
            ),
        ),
        migrations.AlterField(
            model_name="duelresult",
            name="subject_a",
            field=models.CharField(
                blank=True,
                choices=[
                    ("math", "Matematika"),
                    ("english", "Ingliz tili"),
                    ("both", "Ikkalasi ham"),
                ],
                help_text="Together mode: what this pupil studies.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="duelresult",
            name="subject_b",
            field=models.CharField(
                blank=True,
                choices=[
                    ("math", "Matematika"),
                    ("english", "Ingliz tili"),
                    ("both", "Ikkalasi ham"),
                ],
                max_length=10,
            ),
        ),
    ]
