# Generated by Django 6.0.3 on 2026-08-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_duelresult_limit_english_duelresult_limit_math_and_more"),
        ("practice", "0006_subject_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("emoji", models.CharField(blank=True, default="🎁", max_length=8)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=12,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, help_text="0 = unlimited."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="JourneyRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("road", models.CharField(max_length=20)),
                ("leg", models.PositiveSmallIntegerField(default=1)),
                ("seed", models.BigIntegerField(default=0)),
                ("state", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("travelling", "Travelling"),
                            ("paused", "Paused"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="travelling",
                        max_length=12,
                    ),
                ),
                ("coins", models.IntegerField(default=0)),
                ("kuch_left", models.PositiveSmallIntegerField(default=0)),
                ("detours", models.PositiveSmallIntegerField(default=0)),
                (
                    "elapsed",
                    models.PositiveIntegerField(
                        default=0, help_text="Seconds from setting out to arriving."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyPrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carried", models.BooleanField(default=True)),
                ("won_at", models.DateTimeField(auto_now_add=True)),
                ("handed_over", models.BooleanField(default=False)),
                ("handed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journey_prizes_handed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_prizes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to="games.journeyreward",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prizes",
                        to="games.journeyrun",
                    ),
                ),
            ],
            options={
                "ordering": ["handed_over", "-won_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneySeenQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_sightings",
                        to="practice.practicequestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_seen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="journeyrun",
            index=models.Index(
                fields=["user", "status"], name="games_journ_user_id_372867_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyrun",
            index=models.Index(
                fields=["road", "leg", "-coins"], name="games_journ_road_0ab2ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journeyseenquestion",
            index=models.Index(
                fields=["user", "question"], name="games_journ_user_id_8c4b94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journeyseenquestion",
            unique_together={("user", "question")},
        ),
    ]
