# Generated by Django 6.0.3 on 2026-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_journeyreward_journeyrun_journeyprize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeyrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("travelling", "Travelling"),
                    ("stopped", "Stopped"),
                    ("finished", "Finished"),
                    ("failed", "Failed"),
                    ("abandoned", "Abandoned"),
                ],
                default="travelling",
                max_length=12,
            ),
        ),
    ]
