# Generated by Django 6.0.3 on 2026-09-30 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("start", "Start here"),
                            ("letters", "Letters"),
                            ("documents", "Documents"),
                            ("money", "Money"),
                            ("after", "Visa and arrival"),
                            ("choose", "Choosing"),
                        ],
                        default="start",
                        max_length=12,
                    ),
                ),
                ("icon", models.CharField(default="bi-compass", max_length=40)),
                ("minutes", models.PositiveSmallIntegerField(default=5)),
                ("title", models.CharField(max_length=200)),
                ("title_uz", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=300)),
                ("summary_uz", models.CharField(max_length=300)),
                ("body", models.TextField()),
                ("body_uz", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        help_text='Official short name, e.g. "GKS".', max_length=120
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("country", models.CharField(max_length=60)),
                ("country_uz", models.CharField(max_length=60)),
                ("flag", models.CharField(blank=True, max_length=8)),
                (
                    "depth",
                    models.CharField(
                        choices=[("full", "full page"), ("card", "card only")],
                        default="card",
                        max_length=4,
                    ),
                ),
                (
                    "levels",
                    models.CharField(
                        default="bachelor,master",
                        help_text="bachelor, master, phd",
                        max_length=40,
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        default="english",
                        help_text="english, korean, japanese, any — what you can study in",
                        max_length=60,
                    ),
                ),
                ("fully_funded", models.BooleanField(default=True)),
                ("summary", models.CharField(max_length=300)),
                ("summary_uz", models.CharField(max_length=300)),
                (
                    "covers",
                    models.TextField(
                        blank=True, help_text="HTML list of what it pays for."
                    ),
                ),
                ("covers_uz", models.TextField(blank=True)),
                (
                    "usual_period",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Sep–Oct (bachelor), Feb–Mar (master)"',
                        max_length=160,
                    ),
                ),
                ("usual_period_uz", models.CharField(blank=True, max_length=160)),
                (
                    "body",
                    models.TextField(blank=True, help_text="HTML, for depth=full."),
                ),
                ("body_uz", models.TextField(blank=True)),
                ("official_url", models.URLField()),
                ("last_checked", models.DateField()),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(max_length=160)),
                ("name_local", models.CharField(blank=True, max_length=160)),
                ("country", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=60)),
                ("url", models.URLField()),
                ("gks_university_track", models.BooleanField(default=False)),
                ("strengths", models.CharField(max_length=300)),
                ("strengths_uz", models.CharField(max_length=300)),
                (
                    "rank_label",
                    models.CharField(
                        blank=True, help_text='e.g. "QS 2026: #31"', max_length=60
                    ),
                ),
                ("rank_source", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "universities",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=40)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=300)),
                ("text_uz", models.CharField(max_length=300)),
                ("hint", models.CharField(blank=True, max_length=300)),
                ("hint_uz", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["target", "order"],
                "unique_together": {("target", "order")},
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("statement", "Personal statement"),
                            ("study_plan", "Study plan"),
                            ("recommendation", "Recommendation letter"),
                            ("cv", "CV"),
                            ("email", "Email to a professor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_uz", models.CharField(max_length=200)),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="HTML — who wrote it, for what."
                    ),
                ),
                ("intro_uz", models.TextField(blank=True)),
                (
                    "letter",
                    models.TextField(
                        help_text='HTML; paragraphs as <p data-note="n">.'
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        default=list,
                        help_text='[{"en": "...", "uz": "..."}] per note number.',
                    ),
                ),
                (
                    "prompts",
                    models.JSONField(
                        default=list,
                        help_text='[{"en": "...", "uz": "...", "lines": 4}]',
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "scholarship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples",
                        to="abroad.scholarship",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='e.g. "GKS-U 2027 — Embassy track"', max_length=160
                    ),
                ),
                ("label_uz", models.CharField(max_length=160)),
                ("opens", models.DateField(blank=True, null=True)),
                ("closes", models.DateField()),
                (
                    "is_estimate",
                    models.BooleanField(
                        default=False,
                        help_text="Not yet announced — based on last year.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("note_uz", models.CharField(blank=True, max_length=300)),
                ("source_url", models.URLField()),
                ("last_checked", models.DateField()),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="abroad.scholarship",
                    ),
                ),
            ],
            options={
                "ordering": ["closes"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="abroad.checklistitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abroad_ticks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "item")},
            },
        ),
    ]
