# Generated by Django 6.0.3 on 2026-10-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abroad", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="letter_lang",
            field=models.CharField(
                default="en",
                help_text="Language the letter is written in (it is submitted in it).",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="letter",
            field=models.TextField(help_text="HTML, one <p> per paragraph."),
        ),
        migrations.AlterField(
            model_name="sample",
            name="notes",
            field=models.JSONField(
                default=list,
                help_text='[{"para": 1, "en": "...", "uz": "..."}] — para is 1-based.',
            ),
        ),
    ]
