# Generated by Django 6.0.3 on 2026-09-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tutorial", "0006_tutorial_stories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("A", "Warm-up"),
                            ("B", "Drill"),
                            ("C", "Apply"),
                            ("D", "Create"),
                            ("E", "Mission"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("gap", "Fill the gap"),
                            ("conj", "Conjugate"),
                            ("transform", "Transform"),
                            ("build", "Build the sentence"),
                            ("translate", "Translate"),
                            ("fix", "Find and fix the error"),
                            ("hangul", "Letters and blocks"),
                            ("pick", "Choose"),
                            ("write", "Write"),
                            ("mission", "Mission"),
                            ("copy", "Copy by hand"),
                        ],
                        max_length=12,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "instruction",
                    models.TextField(help_text="HTML — what to do, in Uzbek."),
                ),
                ("stars", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "ordering": ["section", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "stem",
                    models.TextField(
                        blank=True, help_text="HTML. A gap is written ___ ."
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Every accepted answer, as typed.",
                    ),
                ),
                (
                    "model_answer",
                    models.TextField(
                        blank=True, help_text="HTML — what a good answer looks like."
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="HTML, Uzbek — why."),
                ),
                ("words", models.JSONField(blank=True, default=list)),
                ("options", models.JSONField(blank=True, default=list)),
                ("checklist", models.JSONField(blank=True, default=list)),
                (
                    "size",
                    models.CharField(
                        choices=[("s", "short"), ("m", "medium"), ("l", "long")],
                        default="m",
                        max_length=5,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="workbook.task",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Workbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True, help_text="HTML shown above the tasks."
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("data_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutorial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbook",
                        to="tutorial.tutorial",
                    ),
                ),
            ],
            options={
                "ordering": ["tutorial_id"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="workbook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="workbook.workbook",
            ),
        ),
        migrations.CreateModel(
            name="WorkbookAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sections_done",
                    models.CharField(
                        blank=True,
                        help_text='Section codes sent at least once, e.g. "ABD".',
                        max_length=8,
                    ),
                ),
                ("correct", models.PositiveSmallIntegerField(default=0)),
                ("total", models.PositiveSmallIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("points_awarded", models.FloatField(default=0)),
                ("teacher_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher_note_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbook_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="workbook.workbook",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "workbook")},
            },
        ),
        migrations.CreateModel(
            name="AnswerAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workbook_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="workbook.taskitem",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
                "unique_together": {("item", "user", "text")},
            },
        ),
        migrations.CreateModel(
            name="ItemResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("verdict", models.CharField(blank=True, max_length=8)),
                ("is_correct", models.BooleanField(null=True)),
                ("checks", models.JSONField(blank=True, default=list)),
                (
                    "self_mark",
                    models.CharField(
                        blank=True,
                        choices=[("good", "good"), ("again", "again")],
                        max_length=8,
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="workbook.taskitem",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="workbook.workbookattempt",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "item")},
            },
        ),
    ]
