# Generated by Django 6.0.3 on 2026-07-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyword",
            name="pos",
            field=models.CharField(
                blank=True,
                choices=[("verb", "Verb"), ("adj", "Adjective"), ("adv", "Adverb")],
                help_text="Part of speech (colour tag); blank = neutral.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="StoryQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The question, in the target language."),
                ),
                (
                    "choices",
                    models.JSONField(
                        default=list, help_text="List of answer choices (strings)."
                    ),
                ),
                (
                    "answer",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0-based index of the correct choice."
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Why the answer is right — in Uzbek."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="corner.story",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
