# Generated by Django 6.0.3 on 2026-07-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corner", "0002_storyword_pos_storyquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryGrammar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="The grammar form, e.g. -는 바람에.", max_length=100
                    ),
                ),
                ("meaning", models.TextField(help_text="Short explanation in Uzbek.")),
                (
                    "examples",
                    models.JSONField(
                        default=list,
                        help_text="List of Korean example sentences (strings).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar",
                        to="corner.story",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
