# Generated by Django 6.0.3 on 2026-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corner", "0003_storygrammar"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="audio",
            field=models.FileField(
                blank=True,
                help_text="Optional narration of the story (MP3/M4A). Leave empty if there is no audio.",
                null=True,
                upload_to="corner/audio/",
            ),
        ),
    ]
