# Generated by Django 6.0.3 on 2026-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corner", "0005_writingpractice_writingpracticeword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional illustration shown at the top of the story (e.g. a picture explaining a proverb).",
                null=True,
                upload_to="corner/images/",
            ),
        ),
    ]
