# Generated by Django 6.0.3 on 2026-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corner", "0007_remove_writingpracticeprogress_practice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="open_question",
            field=models.CharField(
                blank=True,
                help_text="Optional transfer question with NO answer key, shown after the quiz. Same tool as the story, new situation — something to think about, not something to get wrong.",
                max_length=400,
            ),
        ),
    ]
