# -*- coding: utf-8 -*-
"""Prime GMAT mashqlar — GMAT-31 … GMAT-35: Data Insights formats (100 questions).

The real formats are multi-part (Table Analysis: three yes/no statements; Two-Part: one
answer per column; Graphics: drop-down blanks), and the real test gives NO partial credit.
A practice question here has one answer, so each format is rebuilt to keep that rule:
  · three statements → "I only / I and III only / …" — all three must be judged right;
  · two columns      → each choice is a PAIR — both parts must be right;
  · a drop-down      → one blank per question.
Tables and charts are generated by tutorial/management/commands/_dikit.py from the data
below — never hand-typed — and the gate re-measures every bar and dot back to the data.

Import:
    python manage.py import_practices practice/management/commands/_practice_pg_31_35.py \\
        --master=prime --expect-questions=20
"""
import importlib.util
import os

_KIT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    '..', '..', '..', 'tutorial', 'management', 'commands', '_dikit.py')
_spec = importlib.util.spec_from_file_location('_dikit', _KIT)
kit = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(kit)
table, bar_chart, line_chart, statements, combo, pair = (
    kit.table, kit.bar_chart, kit.line_chart, kit.statements, kit.combo, kit.pair)

SUBJECT = {
    "name":        "GMAT",
    "description": "GMAT Quant — Prime GMAT darslarining mashqlari",
    "icon":        "bi-graph-up-arrow",
    "color":       "#0f766e",
}

DEFAULTS = {
    "level":                "medium",
    "is_free":              True,
    "is_published":         True,
    "is_available_for_all": True,
    "pass_score":           60,
    "max_attempts":         0,
    "show_answers_after":   True,
    "time_limit":           None,
}

DS = [
    "Statement (1) ALONE is sufficient, but statement (2) alone is not sufficient.",
    "Statement (2) ALONE is sufficient, but statement (1) alone is not sufficient.",
    "BOTH statements TOGETHER are sufficient, but NEITHER statement ALONE is sufficient.",
    "EACH statement ALONE is sufficient.",
    "Statements (1) and (2) TOGETHER are NOT sufficient.",
]


def q(body, choices, correct, why, fixed=False):
    item = {"text": body, "choices": choices, "correct": correct,
            "explanation": f"<p><strong>{correct}</strong></p>{why}"}
    if fixed:
        item["fixed_order"] = True
    return item


def ds(question, s1, s2, key, why):
    return q(f"<p>{question}</p><p>(1) {s1}</p><p>(2) {s2}</p>", list(DS), DS["ABCDE".index(key)], why, fixed=True)


def ta(intro, tbl, ask):
    return f"<p>{intro}</p>{tbl}<p>{ask}</p>"


def ta3(intro, tbl, items):
    return (f"<p>{intro}</p>{tbl}<p>Based on the table, which of the following statements are true?</p>"
            + statements(items))


# =====================================================================
# GMAT-31 — Table Analysis
# =====================================================================
T1_H = ["Branch", "Staff", "Sales ($k)", "Growth (%)"]
T1 = [["Tashkent", 40, 820, 12], ["Samarkand", 25, 540, 9], ["Bukhara", 18, 310, 5],
      ["Andijan", 22, 450, 15], ["Namangan", 15, 270, 8], ["Fergana", 20, 400, 11]]
T1_I = "The table shows the staff, annual sales and sales growth of a company's six branches last year."
t1 = table(T1_H, T1)

T2_H = ["Product", "Price ($)", "Units sold", "Returns"]
T2 = [["Kettle", 25, 1200, 36], ["Toaster", 40, 800, 40], ["Blender", 60, 500, 10],
      ["Iron", 30, 900, 45], ["Fan", 50, 600, 15]]
T2_I = "The table shows the price, units sold and units returned for five products in one quarter."
t2 = table(T2_H, T2)

T3_H = ["Department", "Staff", "Trained", "Avg score"]
T3 = [["Sales", 50, 40, 72], ["Finance", 20, 18, 81], ["IT", 30, 30, 88],
      ["Marketing", 25, 15, 76], ["HR", 10, 9, 84]]
T3_I = ("The table shows, for each department of a firm, the number of staff, the number who "
        "completed a training course, and their average test score.")
t3 = table(T3_H, T3)

T4_H = ["Destination", "Km", "Hours", "Cost ($)"]
T4 = [["Samarkand", 300, 4, 240], ["Bukhara", 560, 7, 420], ["Fergana", 310, 5, 280],
      ["Nukus", 1100, 14, 880], ["Andijan", 350, 6, 300]]
T4_I = "The table shows a courier company's delivery routes from Tashkent: distance, driving time and cost."
t4 = table(T4_H, T4)

BR = ["Tashkent", "Samarkand", "Andijan", "Fergana", "Namangan"]
PR = ["Kettle", "Toaster", "Blender", "Iron", "Fan"]
DP = ["Sales", "Finance", "IT", "Marketing", "HR"]
DE = ["Samarkand", "Bukhara", "Fergana", "Nukus", "Andijan"]

Q31 = [
    q(ta(T1_I, t1, "Which branch had the highest sales per staff member?"), BR, "Samarkand",
      "<p>Sotuv ÷ xodim: Samarqand 21.6, Toshkent 20.5, Andijon ≈ 20.45, Fargʻona 20.</p><p>Eng katta sotuv — eng yuqori samaradorlik degani emas.</p>"),
    q(ta(T1_I, t1, "What is the median growth rate of the six branches?"), ["8%", "9%", "10%", "10.5%", "11%"], "10%",
      "<p>Tartiblangan: 5, 8, 9, 11, 12, 15 → (9 + 11) ÷ 2 = 10.</p><p>Juft sonli toʻplam — ikki oʻrta sonning oʻrtachasi.</p>"),
    q(ta3(T1_I, t1, ["More than half of the branches grew by more than 10%.",
                     "The branch with the most staff also had the highest sales.",
                     "The six branches' total sales were more than $2.7 million."]),
      ["I only", "II only", "II and III only", "I and III only", "I, II and III"], "II and III only",
      "<p>I — 10% dan yuqori: 11, 12, 15 — 3 ta, oltitadan aynan yarmi, «yarmidan koʻp» emas. II — Toshkent. III — jami 2,790 ming.</p><p>«More than half» — qatʼiy.</p>"),
    q(ta(T1_I, t1, "How many branches had sales above the mean sales of the six branches?"), ["1", "2", "3", "4", "5"], "2",
      "<p>Oʻrtacha 2,790 ÷ 6 = 465: faqat Toshkent va Samarqand.</p><p>Avval oʻrtachani toping, keyin ustunni koʻzdan kechiring.</p>"),
    q(ta3(T1_I, t1, ["Andijan had the highest growth rate.",
                     "Bukhara had the lowest sales per staff member.",
                     "Fergana's sales were exactly half of Tashkent's."]),
      ["I only", "I and II only", "I and III only", "II and III only", "I, II and III"], "I and II only",
      "<p>I — 15%. II — Buxoro ≈ 17.2, eng past. III — 400 va 410: yarmi emas.</p><p>«Exactly» — taxmin emas.</p>"),
    q(ta(T2_I, t2, "Which product brought in the most revenue (price × units sold)?"), PR, "Toaster",
      "<p>Choynak 30,000; toster 32,000; blender 30,000; dazmol 27,000; ventilyator 30,000.</p><p>Eng koʻp sotilgan — eng koʻp tushum degani emas.</p>"),
    q(ta(T2_I, t2, "Which product had the lowest return rate (returns ÷ units sold)?"), PR, "Blender",
      "<p>Blender 2%, ventilyator 2.5%, choynak 3%, toster va dazmol 5%.</p><p>Eng kam qaytarilgan son — eng past ulush emas.</p>"),
    q(ta3(T2_I, t2, ["Exactly two products had a return rate of 5%.",
                     "The product with the most units sold also brought in the most revenue.",
                     "More than 4,000 units were sold in total."]),
      ["I only", "II only", "I and II only", "I and III only", "None of the statements"], "I only",
      "<p>I — toster va dazmol. II — choynak 30,000, toster 32,000. III — jami aynan 4,000.</p><p>«More than» — 4,000 ning oʻzi kirmaydi.</p>"),
    q(ta(T2_I, t2, "What was the total revenue of the five products?"), ["$140,000", "$145,000", "$149,000", "$150,000", "$154,000"], "$149,000",
      "<p>30 + 32 + 30 + 27 + 30 = 149 ming.</p><p>Har bir qatorni alohida hisoblang.</p>"),
    q(ta(T2_I, t2, "If every returned unit was refunded at full price, which product lost the most revenue to refunds?"), PR, "Toaster",
      "<p>Qaytarish × narx: toster 1,600; dazmol 1,350; choynak 900; ventilyator 750; blender 600.</p><p>Eng koʻp qaytarilgan (dazmol) — eng koʻp yoʻqotish emas.</p>"),
    q(ta(T3_I, t3, "Which department had the highest share of staff who completed the training?"), DP, "IT",
      "<p>IT 100%, moliya va HR 90%, sotuv 80%, marketing 60%.</p><p>Ulushni soʻrasa — boʻling.</p>"),
    q(ta(T3_I, t3, "How many staff in total completed the training?"), ["102", "108", "112", "118", "135"], "112",
      "<p>40 + 18 + 30 + 15 + 9 = 112.</p><p>135 — barcha xodimlar.</p>"),
    q(ta(T3_I, t3, "The percent of all staff who completed the training is closest to which of the following?"), ["75%", "79%", "83%", "87%", "90%"], "83%",
      "<p>112 ÷ 135 ≈ 0.83.</p><p>Boʻlimlar foizlarini oʻrtachalash notoʻgʻri — hajmlar har xil.</p>"),
    q(ta3(T3_I, t3, ["Every department in which more than 85% of staff completed the training had an average score above 80.",
                     "Marketing had the lowest average score.",
                     "More than half of all staff work in Sales or IT."]),
      ["I only", "I and III only", "II and III only", "I, II and III", "None of the statements"], "I and III only",
      "<p>I — moliya 81, IT 88, HR 84. II — sotuv 72 pastroq. III — 80 ÷ 135 ≈ 59%.</p><p>Har bir bayonotni alohida tekshiring.</p>"),
    q(ta(T3_I, t3, "When the departments are ranked from highest to lowest average score, which department is third?"), DP, "Finance",
      "<p>IT 88, HR 84, moliya 81, marketing 76, sotuv 72.</p><p>Ustun boʻyicha saralash — imtihonda ekranda mumkin.</p>"),
    q(ta(T4_I, t4, "Which route has the highest average speed?"), DE, "Bukhara",
      "<p>Km ÷ soat: Buxoro 80, Nukus ≈ 78.6, Samarqand 75, Fargʻona 62, Andijon ≈ 58.3.</p><p>Eng uzun yoʻl — eng tez emas.</p>"),
    q(ta(T4_I, t4, "Which route has the highest cost per kilometer?"), DE, "Fergana",
      "<p>Fargʻona ≈ $0.90, Andijon ≈ $0.86, Samarqand va Nukus $0.80, Buxoro $0.75.</p><p>Eng qimmat yoʻl — eng qimmat kilometr emas.</p>"),
    q(ta3(T4_I, t4, ["Every route costs at least $0.75 per kilometer.",
                     "The longest route also takes the most hours.",
                     "The trip to Fergana has a higher average speed than the trip to Andijan."]),
      ["I only", "I and II only", "II and III only", "I, II and III", "None of the statements"], "I, II and III",
      "<p>I — eng arzoni Buxoro, aynan $0.75. II — Nukus. III — 62 va ≈ 58.3.</p><p>«At least» — tenglik ham kiradi.</p>"),
    q(ta(T4_I, t4, "A delivery goes to Bukhara and returns along the same route at the same cost. What is the total cost?"), ["$420", "$560", "$760", "$840", "$880"], "$840",
      "<p>420 × 2.</p><p>$420 — faqat bir tomon.</p>"),
    q(ta(T4_I, t4, "If rising fuel prices increase the cost of every route by 10%, what will the route to Nukus cost?"), ["$888", "$918", "$968", "$978", "$1,080"], "$968",
      "<p>880 × 1.1 = 968.</p><p>$888 — 10% oʻrniga 8 dollar qoʻshilgan.</p>"),
]

# =====================================================================
# GMAT-32 — Graphics Interpretation
# =====================================================================
G1L, G1 = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"], [120, 150, 135, 180, 210, 195]
g1 = bar_chart(G1L, G1, 250, 50, "Monthly sales of a product, January to June.", "Monthly sales bar chart", "Units sold")
G2L, G2 = ["W1", "W2", "W3", "W4", "W5", "W6"], [12, 15, 14, 18, 24, 21]
g2 = line_chart(G2L, G2, 30, 10, "Weekly visitors to a company's online shop, in thousands.", "Weekly visitors line chart", "Visitors (thousands)")
G3L, G3 = ["Marketing", "Salaries", "Rent", "Other"], [30, 45, 15, 10]
g3 = bar_chart(G3L, G3, 50, 10, "How a company's $240,000 annual budget is divided.", "Budget shares bar chart", "Share of budget (%)")
G4L, G4 = ["20–29", "30–39", "40–49", "50+"], [35, 50, 25, 10]
g4 = bar_chart(G4L, G4, 60, 20, "Employees of a firm by age group.", "Employees by age group bar chart", "Employees")


def gi(chart, sentence):
    return f"{chart}<p>Complete the statement so that it is accurate according to the graph.</p><p>{sentence}</p>"


MONTH_PAIRS = ["January and February", "February and March", "March and April", "April and May", "May and June"]
Q32 = [
    q(gi(g1, "Sales in May were ____ percent higher than sales in January."), ["45%", "60%", "75%", "90%", "175%"], "75%",
      "<p>(210 − 120) ÷ 120 = 0.75.</p><p>175% — May sotuvi Yanvarning necha foizi, oʻsish emas.</p>"),
    q(gi(g1, "The largest increase in sales from one month to the next occurred between ____."), MONTH_PAIRS, "March and April",
      "<p>Oʻzgarishlar: +30, −15, +45, +30, −15.</p><p>Eng baland ustun — eng katta oʻsish emas.</p>"),
    q(gi(g1, "Average monthly sales over the six months were ____ units."), ["150", "160", "165", "170", "180"], "165",
      "<p>990 ÷ 6.</p><p>Birinchi va oxirgi oyning oʻrtachasi (157.5) — notoʻgʻri yoʻl.</p>"),
    q(gi(g1, "Sales were above the six-month average in ____ of the six months."), ["1", "2", "3", "4", "5"], "3",
      "<p>165 dan yuqori: aprel, may, iyun.</p><p>Avval oʻrtachani toping.</p>"),
    q(gi(g1, "Sales from April to June were closest to ____ of total sales for the six months."), ["41%", "50%", "55%", "59%", "65%"], "59%",
      "<p>585 ÷ 990 ≈ 0.59.</p><p>41% — birinchi chorak ulushi.</p>"),
    q(gi(g2, "Visitors in week 5 were ____ times the number of visitors in week 1."), ["1.5", "2", "2.5", "3", "12"], "2",
      "<p>24 ÷ 12.</p><p>12 — farq, nisbat emas.</p>"),
    q(gi(g2, "From week 5 to week 6 the number of visitors fell by ____."), ["3%", "10%", "12.5%", "14.3%", "25%"], "12.5%",
      "<p>3 ÷ 24 = 0.125.</p><p>14.3% — yangi qiymatga (21) boʻlingan.</p>"),
    q(gi(g2, "The number of visitors first exceeded 16,000 in ____."), ["Week 2", "Week 3", "Week 4", "Week 5", "Week 6"], "Week 4",
      "<p>18 ming — toʻrtinchi haftada.</p><p>Shkala mingda — 16 ni 16,000 deb oʻqing.</p>"),
    q(gi(g2, "The median weekly number of visitors was ____."), ["15,000", "16,000", "16,500", "17,333", "18,000"], "16,500",
      "<p>12, 14, 15, 18, 21, 24 → (15 + 18) ÷ 2.</p><p>17,333 — oʻrtacha.</p>"),
    q(gi(g2, "Over the six weeks the online shop had ____ visitors in total."), ["96,000", "100,000", "104,000", "108,000", "124,000"], "104,000",
      "<p>12 + 15 + 14 + 18 + 24 + 21 = 104 ming.</p><p>Shkala birligini unutmang.</p>"),
    q(gi(g3, "The company spends ____ a year on salaries."), ["$45,000", "$72,000", "$96,000", "$108,000", "$120,000"], "$108,000",
      "<p>45% × 240,000.</p><p>$45,000 — foizni dollar deb oʻqish.</p>"),
    q(gi(g3, "Spending on rent is ____ times spending on other items."), ["0.67", "1.5", "2", "2.5", "5"], "1.5",
      "<p>15 ÷ 10.</p><p>0.67 — teskari boʻlingan.</p>"),
    q(gi(g3, "Marketing and rent together take ____ of the budget."), ["35%", "40%", "45%", "50%", "55%"], "45%",
      "<p>30 + 15.</p><p>Ulushlar bir butunning qismlari — qoʻshiladi.</p>"),
    q(gi(g3, "If the budget grows to $300,000 with the same shares, marketing spending rises by ____."), ["$12,000", "$15,000", "$18,000", "$24,000", "$90,000"], "$18,000",
      "<p>30% × 60,000.</p><p>$90,000 — yangi marketing summasi, oʻsish emas.</p>"),
    q(gi(g3, "The ratio of salaries spending to marketing spending is ____."), ["2 : 3", "1 : 1", "3 : 2", "9 : 5", "3 : 1"], "3 : 2",
      "<p>45 : 30 = 3 : 2.</p><p>2 : 3 — tartib almashgan.</p>"),
    q(gi(g4, "The share of employees younger than 40 is closest to ____."), ["60%", "65%", "71%", "75%", "85%"], "71%",
      "<p>85 ÷ 120 ≈ 0.71.</p><p>85% — sonni foiz deb oʻqish.</p>"),
    q(gi(g4, "The 30–39 group has ____ more employees than the 40–49 group."), ["15", "20", "25", "35", "50"], "25",
      "<p>50 − 25.</p><p>Ustun balandligini emas, raqamni oʻqing.</p>"),
    q(gi(g4, "If 12 new employees aged 20–29 are hired, the 20–29 group will make up closest to ____ of all employees."), ["29%", "33%", "36%", "39%", "47%"], "36%",
      "<p>47 ÷ 132 ≈ 0.356.</p><p>39% — jamini oʻzgartirmagan javob (47 ÷ 120).</p>"),
    q(gi(g4, "The median employee, by age, is in the ____ group."), ["20–29", "30–39", "40–49", "50+", "20–29 or 30–39 equally"], "30–39",
      "<p>120 kishi: 60- va 61-chi; jamgʻarma 35, keyin 85 — ikkalasi ham 30–39 da.</p><p>Eng koʻp sonli guruh — mediana emas, bu yerda tasodifan mos.</p>"),
    q(gi(g4, "If the 40–49 group grows by 20% and the other groups do not change, the firm will have ____ employees."), ["122", "125", "130", "140", "144"], "125",
      "<p>25 × 1.2 = 30; 120 + 5.</p><p>144 — butun firmaga 20% qoʻshilgan.</p>"),
]

# =====================================================================
# GMAT-33 — Two-Part Analysis
# =====================================================================
def tp(body, part1, part2):
    return f"<p>{body}</p><p>Select one value for <b>{part1}</b> and one value for <b>{part2}</b>.</p>"


SUP = ("<p>Four suppliers quoted for the same order: supplier A, $500 with delivery in 5 days; "
       "supplier B, $450 in 7 days; supplier C, $520 in 3 days; supplier D, $480 in 4 days.</p>")

Q33 = [
    q(tp("A shop sells notebooks for $3 each and pens for $2 each. A customer buys 12 items and pays $30.", "the number of notebooks", "the number of pens"),
      [pair("Notebooks", 6, "Pens", 6), pair("Notebooks", 4, "Pens", 8), pair("Notebooks", 8, "Pens", 4), pair("Notebooks", 6, "Pens", 4), pair("Notebooks", 5, "Pens", 7)],
      pair("Notebooks", 6, "Pens", 6), "<p>3<i>n</i> + 2(12 − <i>n</i>) = 30 → <i>n</i> = 6.</p><p>Ikkala shart ham — son va summa — bajarilishi kerak.</p>"),
    q(tp("<i>x</i> + <i>y</i> = 10 and <i>x</i> − <i>y</i> = 4.", "<i>x</i>", "<i>y</i>"),
      [pair("x", 7, "y", 3), pair("x", 3, "y", 7), pair("x", 6, "y", 4), pair("x", 7, "y", 4), pair("x", 5, "y", 5)],
      pair("x", 7, "y", 3), "<p>Qoʻshamiz: 2<i>x</i> = 14.</p><p>Ustunlarni almashtirmang.</p>"),
    q(tp("Working together, machines A and B finish a job in 6 hours. Machine A alone takes 10 hours.", "the fraction of the job A does in one hour", "the hours B needs alone"),
      [pair("A per hour", "1/10", "B alone", "15 hours"), pair("A per hour", "1/6", "B alone", "15 hours"), pair("A per hour", "1/10", "B alone", "4 hours"),
       pair("A per hour", "1/15", "B alone", "10 hours"), pair("A per hour", "1/10", "B alone", "16 hours")],
      pair("A per hour", "1/10", "B alone", "15 hours"), "<p>1/6 − 1/10 = 1/15 → B 15 soat.</p><p>4 soat — vaqtlar ayirmasi.</p>"),
    q(tp("A retailer sells an item at a profit equal to 25% of its cost and makes $30 profit.", "the cost", "the selling price"),
      [pair("Cost", "$120", "Price", "$150"), pair("Cost", "$120", "Price", "$144"), pair("Cost", "$150", "Price", "$180"),
       pair("Cost", "$96", "Price", "$120"), pair("Cost", "$100", "Price", "$130")],
      pair("Cost", "$120", "Price", "$150"), "<p>0.25 × tannarx = 30 → 120.</p><p>Foyda tannarxdan olinadi.</p>"),
    q(tp("A chemist mixes a 20% solution with a 40% solution to make 40 liters of a 35% solution.", "the liters of the 20% solution", "the liters of the 40% solution"),
      [pair("20% solution", "10 L", "40% solution", "30 L"), pair("20% solution", "30 L", "40% solution", "10 L"), pair("20% solution", "20 L", "40% solution", "20 L"),
       pair("20% solution", "15 L", "40% solution", "25 L"), pair("20% solution", "10 L", "40% solution", "20 L")],
      pair("20% solution", "10 L", "40% solution", "30 L"), "<p>Chalishtirish: (40 − 35) : (35 − 20) = 1 : 3.</p><p>35% — 40% ga yaqin, demak 40% li koʻp.</p>"),
    q(tp("The average of five numbers is 12. Two more numbers, <i>a</i> and <i>b</i>, are added; the average of all seven is 14, and <i>a</i> − <i>b</i> = 4.", "<i>a</i>", "<i>b</i>"),
      [pair("a", 21, "b", 17), pair("a", 17, "b", 21), pair("a", 20, "b", 16), pair("a", 19, "b", 15), pair("a", 22, "b", 16)],
      pair("a", 21, "b", 17), "<p>Yigʻindi 98 − 60 = 38; ayirma 4.</p><p>Oʻrtachani yigʻindiga aylantiring.</p>"),
    q(tp("$1,000 is deposited at 10% annual interest for 2 years.", "the simple interest", "the interest compounded annually"),
      [pair("Simple", "$200", "Compound", "$210"), pair("Simple", "$200", "Compound", "$200"), pair("Simple", "$210", "Compound", "$200"),
       pair("Simple", "$100", "Compound", "$110"), pair("Simple", "$200", "Compound", "$221")],
      pair("Simple", "$200", "Compound", "$210"), "<p>Oddiy 2 × 100; murakkab 1,210 − 1,000.</p><p>$221 — uch yillik xato.</p>"),
    q(tp("Of 100 people, 60 use app A, 50 use app B, and 20 use neither.", "the number who use both apps", "the number who use only app A"),
      [pair("Both", 30, "Only A", 30), pair("Both", 10, "Only A", 50), pair("Both", 30, "Only A", 20), pair("Both", 20, "Only A", 40), pair("Both", 40, "Only A", 20)],
      pair("Both", 30, "Only A", 30), "<p>Ikkalasi 60 + 50 + 20 − 100 = 30; faqat A 60 − 30.</p><p>«Hech biri»ni unutmang.</p>"),
    q(tp("<i>f</i>(<i>x</i>) = 2<i>x</i> + 3.", "<i>f</i>(4)", "the value of <i>x</i> for which <i>f</i>(<i>x</i>) = 17"),
      [pair("f(4)", 11, "x", 7), pair("f(4)", 11, "x", 10), pair("f(4)", 8, "x", 7), pair("f(4)", 14, "x", 7), pair("f(4)", 11, "x", 8.5)],
      pair("f(4)", 11, "x", 7), "<p>2 × 4 + 3; 2<i>x</i> + 3 = 17.</p><p>Ikkinchisi — teskari savol.</p>"),
    q(tp("An arithmetic sequence has first term 5 and common difference 3.", "the 10th term", "the sum of the first 10 terms"),
      [pair("10th term", 32, "Sum", 185), pair("10th term", 35, "Sum", 185), pair("10th term", 32, "Sum", 200), pair("10th term", 30, "Sum", 175), pair("10th term", 35, "Sum", 200)],
      pair("10th term", 32, "Sum", 185), "<p>5 + 9 × 3 = 32; 10 × (5 + 32) ÷ 2.</p><p>35 — 10 ta qadam olingan.</p>"),
    q(SUP + "<p>Select the <b>cheapest supplier</b> and the <b>fastest supplier</b>.</p>",
      [pair("Cheapest", "B", "Fastest", "C"), pair("Cheapest", "B", "Fastest", "D"), pair("Cheapest", "D", "Fastest", "C"), pair("Cheapest", "A", "Fastest", "C"), pair("Cheapest", "C", "Fastest", "B")],
      pair("Cheapest", "B", "Fastest", "C"), "<p>Eng arzon $450 — B; eng tez 3 kun — C.</p><p>Har bir ustun — alohida mezon.</p>"),
    q(SUP + "<p>Select the <b>cheapest supplier that delivers within 5 days</b> and the <b>fastest supplier that costs less than $500</b>. The same supplier may be the answer to both.</p>",
      [pair("Cheapest within 5 days", "D", "Fastest under $500", "D"), pair("Cheapest within 5 days", "B", "Fastest under $500", "D"),
       pair("Cheapest within 5 days", "D", "Fastest under $500", "C"), pair("Cheapest within 5 days", "A", "Fastest under $500", "D"),
       pair("Cheapest within 5 days", "D", "Fastest under $500", "B")],
      pair("Cheapest within 5 days", "D", "Fastest under $500", "D"), "<p>5 kungacha: A, C, D — eng arzoni D ($480). $500 dan arzon: B, D — eng tezi D (4 kun).</p><p>Bir variant ikkala ustunga ham toʻgʻri kelishi mumkin.</p>"),
    q(tp("A car drives 180 km at 60 km per hour and returns along the same road at 90 km per hour.", "the time of the outward trip", "the average speed for the round trip"),
      [pair("Outward", "3 hours", "Average", "72 km/h"), pair("Outward", "3 hours", "Average", "75 km/h"), pair("Outward", "2 hours", "Average", "72 km/h"),
       pair("Outward", "3 hours", "Average", "70 km/h"), pair("Outward", "2 hours", "Average", "75 km/h")],
      pair("Outward", "3 hours", "Average", "72 km/h"), "<p>180 ÷ 60 = 3; 360 ÷ (3 + 2) = 72.</p><p>75 — tezliklar oʻrtachasi.</p>"),
    q(tp("A class of 40 students has boys and girls in the ratio 2 : 3.", "the number of boys", "the number of girls"),
      [pair("Boys", 16, "Girls", 24), pair("Boys", 24, "Girls", 16), pair("Boys", 15, "Girls", 25), pair("Boys", 16, "Girls", 25), pair("Boys", 20, "Girls", 20)],
      pair("Boys", 16, "Girls", 24), "<p>5 qism, bir qism 8.</p><p>Jami 40 boʻlishini tekshiring.</p>"),
    q(tp("A $50 price rises by 20% and then falls by 20%.", "the price after the rise", "the final price"),
      [pair("After rise", "$60", "Final", "$48"), pair("After rise", "$60", "Final", "$50"), pair("After rise", "$70", "Final", "$56"),
       pair("After rise", "$60", "Final", "$52"), pair("After rise", "$55", "Final", "$44")],
      pair("After rise", "$60", "Final", "$48"), "<p>50 × 1.2 = 60; 60 × 0.8 = 48.</p><p>$50 — «bir-birini yoʻqotadi» xatosi.</p>"),
    q(tp("Two fair dice are rolled.", "the probability that the sum is 7", "the probability that the sum is 11"),
      [pair("Sum 7", "1/6", "Sum 11", "1/18"), pair("Sum 7", "1/6", "Sum 11", "1/36"), pair("Sum 7", "7/36", "Sum 11", "1/18"),
       pair("Sum 7", "1/12", "Sum 11", "1/18"), pair("Sum 7", "1/6", "Sum 11", "1/12")],
      pair("Sum 7", "1/6", "Sum 11", "1/18"), "<p>6/36 va 2/36.</p><p>11 ikki usulda chiqadi: (5, 6) va (6, 5).</p>"),
    q(tp("A firm has 6 candidates.", "the number of different 3-person committees", "the number of ways to choose a president, a vice president and a secretary"),
      [pair("Committees", 20, "Officers", 120), pair("Committees", 120, "Officers", 20), pair("Committees", 20, "Officers", 216),
       pair("Committees", 18, "Officers", 120), pair("Committees", 30, "Officers", 120)],
      pair("Committees", 20, "Officers", 120), "<p>C(6, 3) = 20; 6 × 5 × 4 = 120.</p><p>Tartib muhim — lavozimlarda.</p>"),
    q(tp("A data set consists of 3, 5, 7, 9 and 21.", "the mean", "the median"),
      [pair("Mean", 9, "Median", 7), pair("Mean", 7, "Median", 9), pair("Mean", 9, "Median", 9), pair("Mean", 8, "Median", 7), pair("Mean", 9, "Median", 5)],
      pair("Mean", 9, "Median", 7), "<p>45 ÷ 5 = 9; oʻrtadagi 7.</p><p>21 oʻrtachani tortadi, medianani emas.</p>"),
    q(tp("A company's revenue is 5 times its costs, and its profit is $40,000.", "the costs", "the revenue"),
      [pair("Costs", "$10,000", "Revenue", "$50,000"), pair("Costs", "$8,000", "Revenue", "$40,000"), pair("Costs", "$10,000", "Revenue", "$40,000"),
       pair("Costs", "$40,000", "Revenue", "$200,000"), pair("Costs", "$12,500", "Revenue", "$52,500")],
      pair("Costs", "$10,000", "Revenue", "$50,000"), "<p>5<i>C</i> − <i>C</i> = 40,000.</p><p>$40,000 — foyda, tushum emas.</p>"),
    q(tp("Machine A makes 40 parts per hour and machine B makes 60. They start together on an order of 1,000 parts.", "the hours needed", "the number of parts made by B"),
      [pair("Hours", 10, "Parts by B", 600), pair("Hours", 10, "Parts by B", 400), pair("Hours", 12.5, "Parts by B", 600),
       pair("Hours", 10, "Parts by B", 500), pair("Hours", 25, "Parts by B", 600)],
      pair("Hours", 10, "Parts by B", 600), "<p>1,000 ÷ 100 = 10; 60 × 10.</p><p>400 — A yasaganlar.</p>"),
]

# =====================================================================
# GMAT-34 — Multi-Source Reasoning
# =====================================================================
def src(n, label, html):
    return f"<p><b>Source {n} — {label}</b></p>{html}"


M1 = (src(1, "Room rates", table(["Room", "Per night ($)", "Sleeps"], [["Standard", 60, 2], ["Deluxe", 90, 3], ["Suite", 150, 4]]))
      + src(2, "Hotel policy (email)", "<p>Stays of 5 or more nights receive 10% off the room charges; breakfast is not discounted. "
            "Breakfast costs $8 per adult per night. Children under 6 stay free and do not count toward a room's capacity.</p>")
      + src(3, "Booking request", "<p>Our team of 7 adults needs rooms for 4 nights. Please quote the cheapest option, including breakfast for everyone.</p>"))
M2 = (src(1, "Production memo", "<p>Line A produces 120 units per hour and Line B produces 80 units per hour. Each line runs 8 hours a day, "
            "Monday to Friday, except that Line B stops every Friday for maintenance.</p>")
      + src(2, "Weekly orders", table(["Client", "Units per week"], [["X", 3000], ["Y", 2400], ["Z", 1500]]))
      + src(3, "Quality email", "<p>2% of Line A's units and 5% of Line B's units are defective and cannot be shipped.</p>"))
M3 = (src(1, "Last quarter", table(["Channel", "Cost ($)", "Visitors", "Sales"],
                                     [["Social", 4000, 20000, 400], ["Search", 6000, 15000, 600], ["Email", 2000, 5000, 250], ["Radio", 5000, 10000, 150]]))
      + src(2, "Finance memo", "<p>Each sale brings $40 of revenue. A channel's profit is its revenue minus its cost.</p>")
      + src(3, "CFO email", "<p>Next quarter's budget is $12,000. Spend it only on channels whose conversion rate (sales ÷ visitors) was at least 3%, "
            "split between them in proportion to what we spent on them last quarter.</p>"))
M4 = (src(1, "Job posting", "<p>Requirements: at least 3 years of experience and an IELTS score of 6.5 or higher. Salary range: $1,500 to $2,000 a month.</p>")
      + src(2, "Candidates", table(["Name", "Years", "IELTS", "Asks ($)"],
                                   [["Aziz", 5, "7.0", 2100], ["Dilnoza", 3, "6.5", 1800], ["Rustam", 2, "8.0", 1600], ["Malika", 4, "6.0", 1700], ["Bekzod", 6, "7.5", 1950]]))
      + src(3, "HR email", "<p>A candidate who asks for more than the range may be hired only with at least 5 years of experience. "
            "Among eligible candidates, prefer the highest IELTS score; break ties by the lower salary.</p>"))
NAMES = ["Aziz", "Dilnoza", "Rustam", "Malika", "Bekzod"]

Q34 = [
    q(M1 + "<p>What is the lowest possible room cost per night for the team?</p>", ["$180", "$210", "$240", "$270", "$300"], "$210",
      "<p>Bitta Deluxe (3) va ikkita Standard (2 + 2): 90 + 120.</p><p>$240 — Suite + Deluxe yoki toʻrtta Standard.</p>"),
    q(M1 + "<p>What is the hotel's quote for the request, including breakfast?</p>", ["$840", "$1,008", "$1,064", "$1,120", "$1,184"], "$1,064",
      "<p>Xona 210 × 4 = 840; nonushta 7 × 8 × 4 = 224.</p><p>$840 — nonushtasiz.</p>"),
    q(M1 + "<p>If the team stayed 5 nights instead of 4, what would the total be, including breakfast?</p>", ["$1,155", "$1,225", "$1,295", "$1,330", "$1,400"], "$1,225",
      "<p>Xona 1,050 × 0.9 = 945; nonushta 280 — chegirmasiz.</p><p>$1,330 — chegirma unutilgan.</p>"),
    q(M1 + "<p>Which of the following statements are true?</p>" + statements(
        ["One Suite can sleep 4 adults.",
         "Two adults travelling with two children aged 3 and 5 can share one Standard room.",
         "Breakfast for one adult for 4 nights costs more than one night in a Standard room."]),
      ["I only", "I and II only", "I and III only", "II and III only", "I, II and III"], "I and II only",
      "<p>I — sigʻimi 4. II — 6 yoshgacha bolalar sigʻimga kirmaydi. III — 32 &lt; 60.</p><p>Ikkinchi manba birinchisini aniqlashtiradi.</p>"),
    q(M1 + "<p>By how much would the 4-night room cost rise if the team booked one Suite and one Deluxe room instead of the cheapest option?</p>", ["$30", "$60", "$90", "$120", "$240"], "$120",
      "<p>(240 − 210) × 4.</p><p>$30 — bir kecha.</p>"),
    q(M2 + "<p>How many units do the two lines produce together on a Monday?</p>", ["960", "1,200", "1,600", "1,920", "2,000"], "1,600",
      "<p>(120 + 80) × 8.</p><p>960 — faqat A liniyasi.</p>"),
    q(M2 + "<p>How many units do the two lines produce in a full week, Monday to Friday?</p>", ["6,400", "7,040", "7,360", "7,680", "8,000"], "7,360",
      "<p>4 × 1,600 + 960 — jumada faqat A liniyasi ishlaydi.</p><p>8,000 — juma toʻxtash unutilgan.</p>"),
    q(M2 + "<p>How many units can be shipped in a week, after defective units are removed?</p>", ["6,900", "7,000", "7,136", "7,232", "7,360"], "7,136",
      "<p>A: 4,800 × 0.98 = 4,704; B: 2,560 × 0.95 = 2,432.</p><p>7,360 — nuqsonlar ayirilmagan.</p>"),
    q(M2 + "<p>By how many units does the week's shippable output exceed the total weekly orders?</p>", ["136", "236", "336", "460", "1,100"], "236",
      "<p>7,136 − 6,900.</p><p>460 — nuqsonlarni hisobga olmagan javob.</p>"),
    q(M2 + "<p>If Line B also ran on Friday, how many more shippable units would the week produce?</p>", ["480", "576", "608", "640", "800"], "608",
      "<p>640 × 0.95.</p><p>640 — nuqsonlar ayirilmagan.</p>"),
    q(M3 + "<p>Which channel made the most profit last quarter?</p>", ["Social", "Search", "Email", "Radio", "Social and Search equally"], "Search",
      "<p>Foyda: qidiruv 18,000; ijtimoiy 12,000; email 8,000; radio 1,000.</p><p>Eng koʻp tashrif — eng koʻp foyda emas.</p>"),
    q(M3 + "<p>Which channels qualify for next quarter's budget?</p>", ["Search only", "Email only", "Search and Email", "Social, Search and Email", "All four channels"], "Search and Email",
      "<p>Konversiya: email 5%, qidiruv 4%, ijtimoiy 2%, radio 1.5%.</p><p>CFO sharti — 3% dan kam boʻlmasin.</p>"),
    q(M3 + "<p>What was Email's cost per sale last quarter?</p>", ["$2", "$4", "$8", "$10", "$40"], "$8",
      "<p>2,000 ÷ 250.</p><p>$40 — sotuvdan tushum.</p>"),
    q(M3 + "<p>What was the overall conversion rate across all four channels?</p>", ["2%", "2.5%", "2.8%", "3%", "3.1%"], "2.8%",
      "<p>1,400 ÷ 50,000.</p><p>3.1% — kanal foizlarining oddiy oʻrtachasi.</p>"),
    q(M3 + "<p>How much of next quarter's budget goes to Email?</p>", ["$2,000", "$3,000", "$4,000", "$6,000", "$9,000"], "$3,000",
      "<p>Qidiruv 6,000 : email 2,000 = 3 : 1 → email 12,000 ÷ 4.</p><p>$6,000 — teng boʻlingan.</p>"),
    q(M4 + "<p>How many candidates meet the posting's experience and IELTS requirements?</p>", ["1", "2", "3", "4", "5"], "3",
      "<p>Aziz, Dilnoza, Bekzod. Rustam — 2 yil, Malika — IELTS 6.0.</p><p>Ikkala shart ham kerak.</p>"),
    q(M4 + "<p>Which candidate should be preferred?</p>", NAMES, "Bekzod",
      "<p>Mos nomzodlar: Aziz (5 yil — oraliqdan yuqori soʻrashga haqli), Dilnoza, Bekzod; eng yuqori IELTS — Bekzod 7.5.</p><p>Rustam — IELTS eng yuqori, lekin tajriba yetmaydi.</p>"),
    q(M4 + "<p>Which of the following statements are true?</p>" + statements(
        ["Rustam has the highest IELTS score of the five candidates.",
         "Every eligible candidate asks for at least $1,800 a month.",
         "Malika would be eligible if her IELTS score were 6.5."]),
      ["I only", "I and II only", "II and III only", "I, II and III", "None of the statements"], "I, II and III",
      "<p>I — 8.0. II — 2,100, 1,800, 1,950. III — 4 yil va $1,700 oraliqda.</p><p>Har bir bayonot uchun kerakli manbani toping.</p>"),
    q(M4 + "<p>If Bekzod withdraws, which candidate should be preferred?</p>", NAMES, "Aziz",
      "<p>Qolgan mos nomzodlar: Aziz 7.0 va Dilnoza 6.5.</p><p>Aziz oraliqdan yuqori soʻraydi, lekin 5 yillik tajribasi bor.</p>"),
    q(M4 + "<p>If the preferred candidate is hired at the salary they ask for, how far below the top of the salary range is that salary?</p>", ["$0", "$50", "$150", "$200", "$450"], "$50",
      "<p>2,000 − 1,950.</p><p>$450 — eng past chegaradan hisoblangan.</p>"),
]

# =====================================================================
# GMAT-35 — mixed Data Insights review
# =====================================================================
T5_H = ["Store", "Revenue ($k)", "Costs ($k)", "Staff"]
T5 = [["North", 240, 180, 12], ["South", 300, 250, 15], ["East", 180, 120, 9], ["West", 210, 175, 10]]
T5_I = "The table shows last year's revenue, costs and staff of a retailer's four stores."
t5 = table(T5_H, T5)
G5L, G5 = ["Q1", "Q2", "Q3", "Q4"], [40, 55, 50, 75]
g5 = bar_chart(G5L, G5, 80, 20, "A company's profit in each quarter of last year.", "Quarterly profit bar chart", "Profit ($ thousands)")
SHIP = (src(1, "Shipping policy (email)", "<p>Shipping costs $5 per order plus $0.50 per kilogram. Orders worth more than $100 ship free.</p>")
        + src(2, "Today's orders", table(["Order", "Value ($)", "Weight (kg)"], [["A", 80, 6], ["B", 120, 10], ["C", 95, 20], ["D", 60, 4]])))

Q35 = [
    ds("What is the value of <i>x</i>?", "4<i>x</i> − 1 = 11", "<i>x</i><sup>2</sup> = 9", "A",
       "<p>(1): 3. (2): ±3.</p><p>Data Sufficiency — qiymat savoli.</p>"),
    ds("If <i>n</i> is an integer, is <i>n</i> divisible by 4?", "<i>n</i> is divisible by 8.", "<i>n</i> is even.", "A",
       "<p>(1): har doim «ha». (2): 2 — yoʻq, 4 — ha.</p><p>Ha/yoʻq savoli.</p>"),
    ds("How many employees does a firm have?", "30% of them, 18 people, work remotely.", "70% of them, 42 people, work in the office.", "D",
       "<p>(1): 60. (2): 60.</p><p>Har biri foiz va sonni birga beradi.</p>"),
    ds("Is <i>xy</i> &lt; 0?", "<i>x</i> &lt; 0", "<i>y</i> &gt; 0", "C",
       "<p>Birga — aniq «ha».</p><p>Har biri yolgʻiz — ikkinchi ishora nomaʼlum.</p>"),
    ds("What is the price of one child ticket?", "3 adult tickets and 2 child tickets cost $50.", "An adult ticket costs $10.", "C",
       "<p>Birga: 30 + 2<i>c</i> = 50 → 10.</p><p>(1) — ikki nomaʼlum.</p>"),
    ds("Working together at constant rates, how many hours do machines A and B take to do a job?", "A alone takes 4 hours and B alone takes 12 hours.", "A works three times as fast as B.", "A",
       "<p>(1): 1/4 + 1/12 = 1/3 → 3 soat. (2): faqat nisbat.</p><p>Tezliklar nisbati vaqtni bermaydi.</p>"),
    q(ta(T5_I, t5, "Which store had the highest profit per staff member?"), ["North", "South", "East", "West", "North and East equally"], "East",
      "<p>Foyda ÷ xodim: Sharq ≈ 6.67, Shimol 5, Gʻarb 3.5, Janub ≈ 3.33 ming.</p><p>Shimol va Sharq foydasi teng, lekin xodimlar soni har xil.</p>"),
    q(ta3(T5_I, t5, ["Two of the stores made the same profit.",
                     "South had both the highest revenue and the highest profit.",
                     "Total costs were less than 75% of total revenue."]),
      ["I only", "I and II only", "I and III only", "II and III only", "I, II and III"], "I only",
      "<p>I — Shimol va Sharq 60. II — Janub foydasi 50. III — 725 ÷ 930 ≈ 78%.</p><p>Har bir bayonot — alohida hisob.</p>"),
    q(ta(T5_I, t5, "What is the median revenue of the four stores?"), ["$210,000", "$225,000", "$232,500", "$240,000", "$250,000"], "$225,000",
      "<p>180, 210, 240, 300 → (210 + 240) ÷ 2.</p><p>$232,500 — oʻrtacha.</p>"),
    q(ta(T5_I, t5, "West's profit as a percent of its revenue is closest to which of the following?"), ["14%", "17%", "20%", "25%", "35%"], "17%",
      "<p>35 ÷ 210 ≈ 0.167.</p><p>20% — foydani xarajatga boʻlgan javob.</p>"),
    q(gi(g5, "Profit in Q4 was ____ percent higher than profit in Q1."), ["35%", "53%", "75%", "87.5%", "187.5%"], "87.5%",
      "<p>35 ÷ 40.</p><p>187.5% — Q4 Q1 ning necha foizi.</p>"),
    q(gi(g5, "Average quarterly profit last year was ____."), ["$50,000", "$52,500", "$55,000", "$57,500", "$60,000"], "$55,000",
      "<p>220 ÷ 4.</p><p>Shkala ming dollarda.</p>"),
    q(gi(g5, "Profit fell from the previous quarter in ____."), ["Q1", "Q2", "Q3", "Q4", "No quarter"], "Q3",
      "<p>55 → 50.</p><p>Q1 ning oldingi choragi grafikda yoʻq.</p>"),
    q(gi(g5, "Q4 profit was closest to ____ of the year's total profit."), ["25%", "30%", "34%", "38%", "75%"], "34%",
      "<p>75 ÷ 220 ≈ 0.34.</p><p>75% — ming dollarni foiz deb oʻqish.</p>"),
    q(tp("Pens cost $2 and folders cost $5. A customer buys 10 items for $32.", "the number of pens", "the number of folders"),
      [pair("Pens", 6, "Folders", 4), pair("Pens", 4, "Folders", 6), pair("Pens", 5, "Folders", 5), pair("Pens", 6, "Folders", 5), pair("Pens", 7, "Folders", 3)],
      pair("Pens", 6, "Folders", 4), "<p>2<i>p</i> + 5(10 − <i>p</i>) = 32 → <i>p</i> = 6.</p><p>Ikki shart: son va summa.</p>"),
    q(tp("<i>x</i> + <i>y</i> = 20 and 2<i>x</i> − <i>y</i> = 10.", "<i>x</i>", "<i>y</i>"),
      [pair("x", 10, "y", 10), pair("x", 5, "y", 15), pair("x", 10, "y", 12), pair("x", 12, "y", 8), pair("x", 15, "y", 5)],
      pair("x", 10, "y", 10), "<p>Qoʻshamiz: 3<i>x</i> = 30.</p><p>Bir xil qiymat ikkala ustunda ham boʻlishi mumkin.</p>"),
    q(tp("A manager chooses from 8 applicants.", "the number of different 2-person teams", "the number of ways to choose a leader and a deputy"),
      [pair("Teams", 28, "Leader and deputy", 56), pair("Teams", 56, "Leader and deputy", 28), pair("Teams", 28, "Leader and deputy", 64),
       pair("Teams", 16, "Leader and deputy", 56), pair("Teams", 28, "Leader and deputy", 28)],
      pair("Teams", 28, "Leader and deputy", 56), "<p>C(8, 2) = 28; 8 × 7 = 56.</p><p>Lavozimlarda tartib muhim.</p>"),
    q(SHIP + "<p>Which order has the highest shipping cost?</p>", ["A", "B", "C", "D", "A and C equally"], "C",
      "<p>A 8, B 0 (bepul), C 15, D 7.</p><p>Eng qimmat buyurtma — eng qimmat yetkazish emas.</p>"),
    q(SHIP + "<p>What is the total shipping cost of today's four orders?</p>", ["$22", "$28", "$30", "$35", "$40"], "$30",
      "<p>8 + 0 + 15 + 7.</p><p>$40 — B ning bepulligi unutilgan.</p>"),
    q(SHIP + "<p>Which of the following statements are true?</p>" + statements(
        ["Order B ships free.",
         "Order C would ship free if its value rose by $10.",
         "Order D's shipping cost is less than 10% of its value."]),
      ["I only", "I and II only", "I and III only", "II and III only", "I, II and III"], "I and II only",
      "<p>I — 120 &gt; 100. II — 105 &gt; 100. III — 7 ÷ 60 ≈ 11.7%.</p><p>«More than $100» — qatʼiy.</p>"),
]

PRACTICES = [
    {
        "title": "GMAT-31 Practice: Table Analysis",
        "description": "20 ta jadval savoli — saralash, ulush, mediana va uchta bayonotli savollar.",
        "tutorial": "GMAT-31:", "subject": "GMAT", "level": "medium", "questions": Q31,
    },
    {
        "title": "GMAT-32 Practice: Graphics Interpretation",
        "description": "20 ta grafik savoli — ustunli va chiziqli diagrammalar, foiz oʻzgarishi, oʻrtacha va ulush.",
        "tutorial": "GMAT-32:", "subject": "GMAT", "level": "medium", "questions": Q32,
    },
    {
        "title": "GMAT-33 Practice: Two-Part Analysis",
        "description": "20 ta ikki qismli savol — har bir javob juft: ikkala qism ham toʻgʻri boʻlishi kerak.",
        "tutorial": "GMAT-33:", "subject": "GMAT", "level": "medium", "questions": Q33,
    },
    {
        "title": "GMAT-34 Practice: Multi-Source Reasoning",
        "description": "20 ta koʻp manbali savol — mehmonxona, ishlab chiqarish, marketing va ishga qabul vaziyatlari.",
        "tutorial": "GMAT-34:", "subject": "GMAT", "level": "hard", "questions": Q34,
    },
    {
        "title": "GMAT-35 Practice: Data Insights Mixed Review",
        "description": "20 ta aralash savol — Data Sufficiency, jadval, grafik, ikki qismli va koʻp manbali.",
        "tutorial": "GMAT-35:", "subject": "GMAT", "level": "hard", "questions": Q35,
    },
]
