
QUESTIONS_10 = [
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ for you for two hours. Where have you been?</strong></p>',
        'explanation': '<p><strong>have been waiting</strong> is correct. We use Present Perfect Continuous for an action that started in the past and is still happening. <br><br><em>(<strong>have been waiting</strong> to\'g\'ri. Biz o\'tmishda boshlanib, hozir ham davom etayotgan harakatlar uchun Present Perfect Continuous zamonini ishlatamiz.)</em></p>',
        'correct': 'have been waiting',
        'choices': ['have waited', 'am waiting', 'have been waiting', 'was waiting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She ___ three books this week.</strong></p>',
        'explanation': '<p><strong>has read</strong> is correct. We use Present Perfect because we are focusing on the completed result and quantity (three books). <br><br><em>(<strong>has read</strong> to\'g\'ri. Biz Present Perfect zamonini ishlatamiz, chunki e\'tibor tugallangan natija va miqdorga (uchta kitob) qaratilgan.)</em></p>',
        'correct': 'has read',
        'choices': ['has been reading', 'has read', 'is reading', 'reads'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>How long ___ English? Your pronunciation is great!</strong></p>',
        'explanation': '<p><strong>have you been learning</strong> is correct. We use Present Perfect Continuous with "How long" to ask about the duration of an ongoing process. <br><br><em>(<strong>have you been learning</strong> to\'g\'ri. Biz davom etayotgan jarayonning qancha vaqt o\'tganini so\'rash uchun "How long" bilan Present Perfect Continuous zamonini ishlatamiz.)</em></p>',
        'correct': 'have you been learning',
        'choices': ['did you learn', 'are you learning', 'do you learn', 'have you been learning'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ my best friend since we were children.</strong></p>',
        'explanation': '<p><strong>have known</strong> is correct. "Know" is a state verb, so we cannot use it in the continuous form even if it shows duration. <br><br><em>(<strong>have known</strong> to\'g\'ri. "Know" (bilmoq/tanimoq) holat fe\'lidir, shuning uchun davomiylikni ko\'rsatsa ham uni davomiy (continuous) shaklda ishlata olmaymiz.)</em></p>',
        'correct': 'have known',
        'choices': ['have known', 'have been knowing', 'knew', 'am knowing'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The ground is wet. It ___ .</strong></p>',
        'explanation': '<p><strong>has been raining</strong> is correct. We use Present Perfect Continuous for a recently finished action that leaves a visible result (wet ground). <br><br><em>(<strong>has been raining</strong> to\'g\'ri. Yaqinda tugagan va hozir ko\'rinib turgan natijani (ho\'l yer) qoldirgan harakatlar uchun Present Perfect Continuous zamonini ishlatamiz.)</em></p>',
        'correct': 'has been raining',
        'choices': ['rained', 'rains', 'has been raining', 'has rained'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He ___ all the cookies! The jar is completely empty.</strong></p>',
        'explanation': '<p><strong>has eaten</strong> is correct. The action is completed and the focus is on the result (the jar is empty). <br><br><em>(<strong>has eaten</strong> to\'g\'ri. Harakat tugallangan va urg\'u natijaga (idish bo\'shligiga) qaratilgan.)</em></p>',
        'correct': 'has eaten',
        'choices': ['ate', 'has eaten', 'has been eating', 'is eating'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>They ___ on this project since 2024.</strong></p>',
        'explanation': '<p><strong>have been working</strong> is correct. The action started in the past and is still ongoing. <br><br><em>(<strong>have been working</strong> to\'g\'ri. Harakat o\'tmishda boshlangan va hozir ham davom etmoqda.)</em></p>',
        'correct': 'have been working',
        'choices': ['have been working', 'are working', 'worked', 'have worked'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We ___ each other much lately.</strong></p>',
        'explanation': '<p><strong>haven\'t seen</strong> is correct. "See" is usually a state verb in this context, focusing on the lack of contact over a recent period. <br><br><em>(<strong>haven\'t seen</strong> to\'g\'ri. "See" (ko\'rmoq) bu o\'rinda holat fe\'li bo\'lib, so\'nggi paytlardagi aloqaning yo\'qligiga e\'tibor qaratadi.)</em></p>',
        'correct': 'haven\'t seen',
        'choices': ['didn\'t see', 'don\'t see', 'haven\'t been seeing', 'haven\'t seen'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>You look exhausted. What ___ ?</strong></p>',
        'explanation': '<p><strong>have you been doing</strong> is correct. We are asking about the continuous action that caused the visible present result (exhaustion). <br><br><em>(<strong>have you been doing</strong> to\'g\'ri. Biz hozirgi natijaga (charchoqqa) sabab bo\'lgan davomiy harakat haqida so\'rayapmiz.)</em></p>',
        'correct': 'have you been doing',
        'choices': ['did you do', 'have you done', 'have you been doing', 'are you doing'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ my room. That\'s why there is paint on my clothes, but I am only half finished.</strong></p>',
        'explanation': '<p><strong>have been painting</strong> is correct. The action is incomplete and still ongoing, with visible evidence (paint on clothes). <br><br><em>(<strong>have been painting</strong> to\'g\'ri. Harakat hali tugallanmagan va davom etmoqda, hamda uning asorati (kiyimdagi bo\'yoq) ko\'rinib turibdi.)</em></p>',
        'correct': 'have been painting',
        'choices': ['painted', 'have been painting', 'have painted', 'am painting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Somebody ___ my coffee. The cup is half empty.</strong></p>',
        'explanation': '<p><strong>has been drinking</strong> is correct. The action is ongoing or recently stopped, and the coffee isn\'t completely gone. <br><br><em>(<strong>has been drinking</strong> to\'g\'ri. Harakat davom etgan yoki yaqinda to\'xtagan, va qahva to\'liq tugamagan.)</em></p>',
        'correct': 'has been drinking',
        'choices': ['has been drinking', 'drinks', 'drank', 'has drunk'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ my keys. Can you help me find them?</strong></p>',
        'explanation': '<p><strong>have lost</strong> is correct. The action is completed and has a clear present result (keys are missing). <br><br><em>(<strong>have lost</strong> to\'g\'ri. Harakat tugallangan va uning hozirgi aniq natijasi bor (kalitlar yo\'qolgan).)</em></p>',
        'correct': 'have lost',
        'choices': ['have been losing', 'am losing', 'have lost', 'lost'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>How many times ___ New York?</strong></p>',
        'explanation': '<p><strong>have you visited</strong> is correct. We use Present Perfect for quantities and repeated experiences ("How many times"). <br><br><em>(<strong>have you visited</strong> to\'g\'ri. Biz miqdor va takrorlangan tajribalar uchun ("Necha marta") Present Perfect zamonini ishlatamiz.)</em></p>',
        'correct': 'have you visited',
        'choices': ['do you visit', 'have you visited', 'did you visit', 'have you been visiting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He ___ for an hour and he is very tired now.</strong></p>',
        'explanation': '<p><strong>has been running</strong> is correct. The action has a duration (for an hour) and explains a present result (being tired). <br><br><em>(<strong>has been running</strong> to\'g\'ri. Harakatning davomiyligi bor (bir soat davomida) va u hozirgi natijani (charchaganini) tushuntiradi.)</em></p>',
        'correct': 'has been running',
        'choices': ['runs', 'ran', 'has run', 'has been running'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ chocolate. It\'s my favorite!</strong></p>',
        'explanation': '<p><strong>have always loved</strong> is correct. "Love" is a state verb, so it cannot be used in a continuous tense. <br><br><em>(<strong>have always loved</strong> to\'g\'ri. "Love" (sevmoq/yoqtirmoq) holat fe\'lidir, shuning uchun uni davomiy zamonda ishlatib bo\'lmaydi.)</em></p>',
        'correct': 'have always loved',
        'choices': ['have always loved', 'have always been loving', 'always loved', 'am always loving'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She ___ her essay all morning. She needs a break.</strong></p>',
        'explanation': '<p><strong>has been writing</strong> is correct. "All morning" emphasizes the uninterrupted duration of the action. <br><br><em>(<strong>has been writing</strong> to\'g\'ri. "All morning" (butun ertalab) harakatning uzluksiz davom etganligiga urg\'u beradi.)</em></p>',
        'correct': 'has been writing',
        'choices': ['wrote', 'has written', 'has been writing', 'is writing'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She ___ five pages of her essay so far.</strong></p>',
        'explanation': '<p><strong>has written</strong> is correct. "Five pages" shows the quantity of the completed action up to now. <br><br><em>(<strong>has written</strong> to\'g\'ri. "Five pages" (besh sahifa) hozirgi paytgacha tugallangan harakatning miqdorini ko\'rsatadi.)</em></p>',
        'correct': 'has written',
        'choices': ['wrote', 'has written', 'has been writing', 'writes'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ about buying a new car recently. What do you think?</strong></p>',
        'explanation': '<p><strong>have been thinking</strong> is correct. "Think" (meaning "consider") can be used in continuous form. "Recently" points to an ongoing process. <br><br><em>(<strong>have been thinking</strong> to\'g\'ri. "Think" (o\'ylamoq/ko\'rib chiqmoq ma\'nosida) davomiy shaklda ishlatilishi mumkin. "Recently" (yaqinda/shu kunlarda) davom etayotgan jarayonni ko\'rsatadi.)</em></p>',
        'correct': 'have been thinking',
        'choices': ['thought', 'am thinking', 'have thought', 'have been thinking'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We ___ this car for five years. It\'s very reliable.</strong></p>',
        'explanation': '<p><strong>have had</strong> is correct. "Have" (meaning "possess") is a state verb and cannot be continuous. <br><br><em>(<strong>have had</strong> to\'g\'ri. "Have" (egalik qilmoq ma\'nosida) holat fe\'lidir va uni davomiy zamonda ishlatib bo\'lmaydi.)</em></p>',
        'correct': 'have had',
        'choices': ['had', 'have been having', 'have had', 'are having'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Why are your hands dirty? I ___ my bike.</strong></p>',
        'explanation': '<p><strong>have been fixing</strong> is correct. Fixing the bike is the ongoing activity that explains the present result (dirty hands). <br><br><em>(<strong>have been fixing</strong> to\'g\'ri. Velosipedni tuzatish - bu hozirgi natijaga (iflos qo\'llarga) sabab bo\'lgan davomiy mashg\'ulotdir.)</em></p>',
        'correct': 'have been fixing',
        'choices': ['have been fixing', 'have fixed', 'am fixing', 'fixed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ the bike. You can ride it now.</strong></p>',
        'explanation': '<p><strong>have fixed</strong> is correct. The action is finished, and the result is that the bike is ready to use. <br><br><em>(<strong>have fixed</strong> to\'g\'ri. Harakat tugagan va natijada velosiped haydashga tayyor.)</em></p>',
        'correct': 'have fixed',
        'choices': ['fixed', 'have fixed', 'have been fixing', 'am fixing'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He ___ the lesson at all. He needs extra help.</strong></p>',
        'explanation': '<p><strong>hasn\'t understood</strong> is correct. "Understand" is a state verb and cannot be used in continuous tenses. <br><br><em>(<strong>hasn\'t understood</strong> to\'g\'ri. "Understand" (tushunmoq) holat fe\'lidir va uni davomiy zamonlarda ishlatib bo\'lmaydi.)</em></p>',
        'correct': 'hasn\'t understood',
        'choices': ['didn\'t understand', 'hasn\'t been understanding', 'hasn\'t understood', 'isn\'t understanding'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>___ sushi? It\'s delicious!</strong></p>',
        'explanation': '<p><strong>Have you ever eaten</strong> is correct. We use Present Perfect with "ever" to ask about life experiences up to now. <br><br><em>(<strong>Have you ever eaten</strong> to\'g\'ri. Biz hozirgi kungacha bo\'lgan hayotiy tajribalar haqida so\'rash uchun "ever" bilan Present Perfect ishlatamiz.)</em></p>',
        'correct': 'Have you ever eaten',
        'choices': ['Did you ever eat', 'Have you ever eaten', 'Have you ever been eating', 'Are you ever eating'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>It ___ since yesterday evening, and the roads are covered in white.</strong></p>',
        'explanation': '<p><strong>has been snowing</strong> is correct. The action started in the past (yesterday evening) and is still continuing. <br><br><em>(<strong>has been snowing</strong> to\'g\'ri. Harakat o\'tmishda (kecha kechqurun) boshlangan va hozir ham davom etmoqda.)</em></p>',
        'correct': 'has been snowing',
        'choices': ['has been snowing', 'snows', 'has snowed', 'snowed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ in ghosts since I was a child.</strong></p>',
        'explanation': '<p><strong>have believed</strong> is correct. "Believe" is a state verb and cannot be continuous. <br><br><em>(<strong>have believed</strong> to\'g\'ri. "Believe" (ishonmoq) holat fe\'lidir va uni davomiy (continuous) shaklda ishlata olmaymiz.)</em></p>',
        'correct': 'have believed',
        'choices': ['believed', 'am believing', 'have been believing', 'have believed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The baby ___ for three hours. Let\'s wake him up.</strong></p>',
        'explanation': '<p><strong>has been sleeping</strong> is correct. This emphasizes the continuous duration of the sleep up to now. <br><br><em>(<strong>has been sleeping</strong> to\'g\'ri. Bu uyquning hozirgi paytgacha bo\'lgan davomiyligiga urg\'u beradi.)</em></p>',
        'correct': 'has been sleeping',
        'choices': ['slept', 'has been sleeping', 'is sleeping', 'has slept'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Someone ___ my chocolates! The box is completely empty.</strong></p>',
        'explanation': '<p><strong>has eaten</strong> is correct. The action is completed, leaving a result (the box is empty). <br><br><em>(<strong>has eaten</strong> to\'g\'ri. Harakat tugallangan va o\'zidan natija qoldirgan (quti bo\'sh).)</em></p>',
        'correct': 'has eaten',
        'choices': ['ate', 'is eating', 'has eaten', 'has been eating'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>How long ___ for the bus? He looks annoyed.</strong></p>',
        'explanation': '<p><strong>has he been waiting</strong> is correct. We use "How long" with Present Perfect Continuous to focus on the duration of an ongoing action. <br><br><em>(<strong>has he been waiting</strong> to\'g\'ri. Davom etayotgan harakatning muddatiga urg\'u berish uchun biz "How long" bilan Present Perfect Continuous ishlatamiz.)</em></p>',
        'correct': 'has he been waiting',
        'choices': ['has he been waiting', 'did he wait', 'is he waiting', 'has he waited'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ my homework. Can I go out to play now?</strong></p>',
        'explanation': '<p><strong>have finished</strong> is correct. The action of finishing is complete, bringing a result (permission to play). <br><br><em>(<strong>have finished</strong> to\'g\'ri. Tugatish harakati yakunlangan, va u natija olib keladi (o\'ynashga ruxsat).)</em></p>',
        'correct': 'have finished',
        'choices': ['am finishing', 'finished', 'have been finishing', 'have finished'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>My eyes hurt because I ___ TV for too long.</strong></p>',
        'explanation': '<p><strong>have been watching</strong> is correct. The continuous action explains the visible present result (hurting eyes). <br><br><em>(<strong>have been watching</strong> to\'g\'ri. Davomiy harakat hozirgi ko\'rinib turgan natijani (ko\'z og\'rishini) tushuntiradi.)</em></p>',
        'correct': 'have been watching',
        'choices': ['watch', 'have been watching', 'have watched', 'watched'],
    }
]

QUESTIONS_11 = [
    {
        'text': '<p>Choose the correct option.</p><p><strong>I really enjoy ___ books in my free time.</strong></p>',
        'explanation': '<p><strong>reading</strong> is correct. The verb "enjoy" is always followed by a gerund (-ing). <br><br><em>(<strong>reading</strong> to\'g\'ri. "Enjoy" (zavqlanmoq) fe\'lidan so\'ng doim gerundiy keladi.)</em></p>',
        'correct': 'reading',
        'choices': ['to read', 'reading', 'read', 'to reading'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She wants ___ a new language this year.</strong></p>',
        'explanation': '<p><strong>to learn</strong> is correct. The verb "want" is followed by an infinitive (to + verb). <br><br><em>(<strong>to learn</strong> to\'g\'ri. "Want" (xohlamoq) fe\'lidan so\'ng doim infinitiv ishlatiladi.)</em></p>',
        'correct': 'to learn',
        'choices': ['learning', 'learn', 'to learn', 'learned'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We talked about ___ a new project for the education center.</strong></p>',
        'explanation': '<p><strong>starting</strong> is correct. We always use a gerund after a preposition like "about". <br><br><em>(<strong>starting</strong> to\'g\'ri. "About" (haqida) kabi predloglardan keyin har doim gerundiy ishlatamiz.)</em></p>',
        'correct': 'starting',
        'choices': ['to start', 'starting', 'start', 'started'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I went to the store ___ some milk.</strong></p>',
        'explanation': '<p><strong>to buy</strong> is correct. We use the infinitive to show the purpose of an action (why you did something). <br><br><em>(<strong>to buy</strong> to\'g\'ri. Harakatning maqsadini (nima uchun qilinganini) ko\'rsatish uchun biz infinitivdan foydalanamiz.)</em></p>',
        'correct': 'to buy',
        'choices': ['buying', 'for buy', 'to buy', 'buy'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He stopped ___ two years ago for his health.</strong></p>',
        'explanation': '<p><strong>smoking</strong> is correct. "Stop" + gerund means to quit an action completely. <br><br><em>(<strong>smoking</strong> to\'g\'ri. "Stop" + gerundiy harakatni butunlay tashlashni (to\'xtatishni) anglatadi.)</em></p>',
        'correct': 'smoking',
        'choices': ['to smoke', 'smoking', 'smoke', 'smoked'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We were driving and stopped ___ some food on the way.</strong></p>',
        'explanation': '<p><strong>to buy</strong> is correct. "Stop" + infinitive means interrupting your current action in order to do something else. <br><br><em>(<strong>to buy</strong> to\'g\'ri. "Stop" + infinitiv boshqa biror ishni qilish maqsadida joriy harakatdan to\'xtashni anglatadi.)</em></p>',
        'correct': 'to buy',
        'choices': ['buying', 'to buy', 'buy', 'bought'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>___ is a great way to stay fit and healthy.</strong></p>',
        'explanation': '<p><strong>Swimming</strong> is correct. When an action is the subject of a sentence, we use the gerund form. <br><br><em>(<strong>Swimming</strong> to\'g\'ri. Harakat gapning egasi (bosh qismi) bo\'lib kelganida, biz gerundiy shaklidan foydalanamiz.)</em></p>',
        'correct': 'Swimming',
        'choices': ['To swim', 'Swim', 'Swimming', 'Swam'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>They decided ___ the old house.</strong></p>',
        'explanation': '<p><strong>to sell</strong> is correct. The verb "decide" is always followed by an infinitive. <br><br><em>(<strong>to sell</strong> to\'g\'ri. "Decide" (qaror qilmoq) fe\'lidan so\'ng doim infinitiv keladi.)</em></p>',
        'correct': 'to sell',
        'choices': ['selling', 'to sell', 'sell', 'sold'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He promised ___ me with my Python homework.</strong></p>',
        'explanation': '<p><strong>to help</strong> is correct. The verb "promise" is followed by an infinitive. <br><br><em>(<strong>to help</strong> to\'g\'ri. "Promise" (vada bermoq) fe\'lidan keyin infinitiv ishlatiladi.)</em></p>',
        'correct': 'to help',
        'choices': ['helping', 'to help', 'help', 'helped'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Do you mind ___ the window? It\'s hot in here.</strong></p>',
        'explanation': '<p><strong>opening</strong> is correct. The verb "mind" is always followed by a gerund. <br><br><em>(<strong>opening</strong> to\'g\'ri. "Mind" (qarshi bo\'lmoq) fe\'lidan so\'ng har doim gerundiy keladi.)</em></p>',
        'correct': 'opening',
        'choices': ['to open', 'opening', 'open', 'opened'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I clearly remember ___ the door before leaving. I double-checked it!</strong></p>',
        'explanation': '<p><strong>locking</strong> is correct. "Remember" + gerund refers to having a memory of a past action. <br><br><em>(<strong>locking</strong> to\'g\'ri. "Remember" + gerundiy o\'tmishda qilingan harakatni xotirlashni bildiradi.)</em></p>',
        'correct': 'locking',
        'choices': ['to lock', 'locking', 'lock', 'locked'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Please remember ___ the milk on your way home.</strong></p>',
        'explanation': '<p><strong>to buy</strong> is correct. "Remember" + infinitive means not forgetting to do a required task. <br><br><em>(<strong>to buy</strong> to\'g\'ri. "Remember" + infinitiv qilinishi kerak bo\'lgan vazifani unutmaslikni bildiradi.)</em></p>',
        'correct': 'to buy',
        'choices': ['buying', 'to buy', 'buy', 'bought'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>You should avoid ___ too much junk food.</strong></p>',
        'explanation': '<p><strong>eating</strong> is correct. The verb "avoid" is followed by a gerund. <br><br><em>(<strong>eating</strong> to\'g\'ri. "Avoid" (qochmoq/saqlanmoq) fe\'lidan so\'ng gerundiy ishlatiladi.)</em></p>',
        'correct': 'eating',
        'choices': ['to eat', 'eating', 'eat', 'ate'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We plan ___ to Japan next summer.</strong></p>',
        'explanation': '<p><strong>to travel</strong> is correct. The verb "plan" is followed by an infinitive. <br><br><em>(<strong>to travel</strong> to\'g\'ri. "Plan" (rejalashtirmoq) fe\'lidan so\'ng infinitiv keladi.)</em></p>',
        'correct': 'to travel',
        'choices': ['traveling', 'to travel', 'travel', 'traveled'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He left the room without ___ a single word.</strong></p>',
        'explanation': '<p><strong>saying</strong> is correct. "Without" is a preposition, and prepositions must be followed by a gerund. <br><br><em>(<strong>saying</strong> to\'g\'ri. "Without" (siz/masdan) predlog hisoblanadi va predloglardan keyin gerundiy kelishi shart.)</em></p>',
        'correct': 'saying',
        'choices': ['to say', 'saying', 'say', 'said'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Have you finished ___ your essay yet?</strong></p>',
        'explanation': '<p><strong>writing</strong> is correct. The verb "finish" is always followed by a gerund. <br><br><em>(<strong>writing</strong> to\'g\'ri. "Finish" (tugatmoq) fe\'lidan keyin doim gerundiy keladi.)</em></p>',
        'correct': 'writing',
        'choices': ['to write', 'writing', 'write', 'wrote'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I hope ___ you soon!</strong></p>',
        'explanation': '<p><strong>to see</strong> is correct. The verb "hope" points to the future and is followed by an infinitive. <br><br><em>(<strong>to see</strong> to\'g\'ri. "Hope" (umid qilmoq) fe\'li kelajakka ishora qiladi va o\'zidan so\'ng infinitiv oladi.)</em></p>',
        'correct': 'to see',
        'choices': ['seeing', 'to see', 'see', 'saw'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I am trying ___ this math problem, but it\'s very hard.</strong></p>',
        'explanation': '<p><strong>to solve</strong> is correct. "Try" + infinitive means making an effort to do something difficult. <br><br><em>(<strong>to solve</strong> to\'g\'ri. "Try" + infinitiv qiyin narsani bajarishga harakat qilishni anglatadi.)</em></p>',
        'correct': 'to solve',
        'choices': ['solving', 'to solve', 'solve', 'solved'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The computer isn\'t working. Have you tried ___ it?</strong></p>',
        'explanation': '<p><strong>restarting</strong> is correct. "Try" + gerund means experimenting with something to see if it solves a problem. <br><br><em>(<strong>restarting</strong> to\'g\'ri. "Try" + gerundiy muammoni hal qilish yoki qilmasligini sinab ko\'rish (eksperiment qilish) ma\'nosida keladi.)</em></p>',
        'correct': 'restarting',
        'choices': ['to restart', 'restarting', 'restart', 'restarted'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He suggested ___ to the park for a walk.</strong></p>',
        'explanation': '<p><strong>going</strong> is correct. The verb "suggest" must be followed by a gerund, not an infinitive. <br><br><em>(<strong>going</strong> to\'g\'ri. "Suggest" (taklif qilmoq) fe\'lidan keyin infinitiv emas, gerundiy ishlatilishi shart.)</em></p>',
        'correct': 'going',
        'choices': ['to go', 'going', 'go', 'went'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I need ___ some urgent emails right now.</strong></p>',
        'explanation': '<p><strong>to send</strong> is correct. The verb "need" is followed by an infinitive. <br><br><em>(<strong>to send</strong> to\'g\'ri. "Need" (muhtoj bo\'lmoq/kerak) fe\'lidan so\'ng infinitiv keladi.)</em></p>',
        'correct': 'to send',
        'choices': ['sending', 'to send', 'send', 'sent'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She is very good at ___ new languages quickly.</strong></p>',
        'explanation': '<p><strong>learning</strong> is correct. "At" is a preposition, and prepositions are always followed by gerunds. <br><br><em>(<strong>learning</strong> to\'g\'ri. "At" (-da) predlog hisoblanadi va predloglardan keyin har doim gerundiy keladi.)</em></p>',
        'correct': 'learning',
        'choices': ['to learn', 'learning', 'learn', 'learned'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Don\'t forget ___ your grandmother on her birthday!</strong></p>',
        'explanation': '<p><strong>to call</strong> is correct. "Forget" + infinitive is used for a future action you must not fail to do. <br><br><em>(<strong>to call</strong> to\'g\'ri. "Forget" + infinitiv kelajakda qilinishi kerak bo\'lgan va yoddan chiqmasligi muhim bo\'lgan harakatlar uchun ishlatiladi.)</em></p>',
        'correct': 'to call',
        'choices': ['calling', 'to call', 'call', 'called'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I prefer ___ coffee in the morning.</strong></p>',
        'explanation': '<p><strong>drinking</strong> is correct. "Prefer" can take both, but gerund is most common for general preferences. <br><br><em>(<strong>drinking</strong> to\'g\'ri. "Prefer" (afzal ko\'rmoq) ikkalasini ham qabul qilishi mumkin, ammo umumiy odatlar uchun asosan gerundiy ishlatiladi.)</em></p>',
        'correct': 'drinking',
        'choices': ['to drinking', 'drinking', 'drink', 'drank'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I would like ___ a pizza, please.</strong></p>',
        'explanation': '<p><strong>to order</strong> is correct. While "like" can take a gerund, "would like" is ALWAYS followed by an infinitive. <br><br><em>(<strong>to order</strong> to\'g\'ri. "Like" gerundiyni qabul qilsa ham, "would like" (xohlardim) har doim o\'zidan keyin infinitiv oladi.)</em></p>',
        'correct': 'to order',
        'choices': ['ordering', 'to order', 'order', 'ordered'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He gave up ___ fast food to get healthy.</strong></p>',
        'explanation': '<p><strong>eating</strong> is correct. "Give up" is a phrasal verb ending in a preposition (up), so it needs a gerund. <br><br><em>(<strong>eating</strong> to\'g\'ri. "Give up" (voz kechmoq) predlog (up) bilan tugaydigan iborali fe\'l bo\'lgani uchun u gerundiy talab qiladi.)</em></p>',
        'correct': 'eating',
        'choices': ['to eat', 'eating', 'eat', 'ate'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She is learning ___ the guitar.</strong></p>',
        'explanation': '<p><strong>to play</strong> is correct. The verb "learn" is followed by an infinitive. <br><br><em>(<strong>to play</strong> to\'g\'ri. "Learn" (o\'rganmoq) fe\'lidan keyin infinitiv ishlatiladi.)</em></p>',
        'correct': 'to play',
        'choices': ['playing', 'to play', 'play', 'played'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Please keep ___ until you reach the end of the street.</strong></p>',
        'explanation': '<p><strong>walking</strong> is correct. The verb "keep" (meaning to continue) is followed by a gerund. <br><br><em>(<strong>walking</strong> to\'g\'ri. "Keep" (davom etmoq ma\'nosida) fe\'lidan so\'ng gerundiy keladi.)</em></p>',
        'correct': 'walking',
        'choices': ['to walk', 'walking', 'walk', 'walked'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>It is easy ___ mistakes when you are tired.</strong></p>',
        'explanation': '<p><strong>to make</strong> is correct. We use the infinitive form after an adjective (like "easy"). <br><br><em>(<strong>to make</strong> to\'g\'ri. Biz sifatlardan (masalan, "easy" - oson) keyin infinitiv shaklidan foydalanamiz.)</em></p>',
        'correct': 'to make',
        'choices': ['making', 'to make', 'make', 'made'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I look forward to ___ you again.</strong></p>',
        'explanation': '<p><strong>seeing</strong> is correct. In the phrase "look forward to", "to" is a preposition, so it must be followed by a gerund. <br><br><em>(<strong>seeing</strong> to\'g\'ri. "Look forward to" (intizorlik bilan kutmoq) iborasidagi "to" predlog vazifasida keladi, shuning uchun undan keyin gerundiy kelishi shart.)</em></p>',
        'correct': 'seeing',
        'choices': ['to see', 'seeing', 'see', 'saw'],
    }
]

QUESTIONS_12 = [
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you heat water to 100 degrees, it ___.</strong></p>',
        'explanation': '<p><strong>boils</strong> is correct. This is a Zero Conditional sentence describing a scientific fact, so we use Present Simple in both parts. <br><br><em>(<strong>boils</strong> to\'g\'ri. Bu ilmiy faktni tasvirlovchi nolinchi shart gapi, shuning uchun biz ikkala qismda ham Present Simple ishlatamiz.)</em></p>',
        'correct': 'boils',
        'choices': ['will boil', 'boils', 'boiled', 'is boiling'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If it rains tomorrow, I ___ at home.</strong></p>',
        'explanation': '<p><strong>will stay</strong> is correct. This is a First Conditional sentence talking about a specific future plan. <br><br><em>(<strong>will stay</strong> to\'g\'ri. Bu kelajakdagi aniq reja haqida gapiradigan birinchi shart gapi.)</em></p>',
        'correct': 'will stay',
        'choices': ['stay', 'stayed', 'will stay', 'am staying'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you mix red and blue, you ___ purple.</strong></p>',
        'explanation': '<p><strong>get</strong> is correct. Mixing colors is a general fact that always produces the same result (Zero Conditional). <br><br><em>(<strong>get</strong> to\'g\'ri. Ranglarni aralashtirish har doim bir xil natija beradigan umumiy faktdir (Nolinchi shart gapi).)</em></p>',
        'correct': 'get',
        'choices': ['will get', 'got', 'are getting', 'get'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ hurry up, you will miss the train!</strong></p>',
        'explanation': '<p><strong>don\'t</strong> is correct. In the First Conditional, the "If" part uses the Present Simple tense. <br><br><em>(<strong>don\'t</strong> to\'g\'ri. Birinchi shart gapida "If" (agar) qismi Present Simple (oddiy hozirgi) zamonidan foydalanadi.)</em></p>',
        'correct': 'don\'t',
        'choices': ['won\'t', 'don\'t', 'didn\'t', 'aren\'t'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If people eat too much, they ___ fat.</strong></p>',
        'explanation': '<p><strong>get</strong> is correct. This is a general truth or biological fact (Zero Conditional). <br><br><em>(<strong>get</strong> to\'g\'ri. Bu umumiy haqiqat yoki biologik faktdir (Nolinchi shart gapi).)</em></p>',
        'correct': 'get',
        'choices': ['will get', 'got', 'get', 'are getting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I see him later, I ___ him the good news.</strong></p>',
        'explanation': '<p><strong>will tell</strong> is correct. This is a real possibility in the future (First Conditional). <br><br><em>(<strong>will tell</strong> to\'g\'ri. Bu kelajakdagi real ehtimollikdir (Birinchi shart gapi).)</em></p>',
        'correct': 'will tell',
        'choices': ['tell', 'told', 'will tell', 'am telling'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Babies cry if they ___ hungry.</strong></p>',
        'explanation': '<p><strong>are</strong> is correct. This is a general fact about babies (Zero Conditional). <br><br><em>(<strong>are</strong> to\'g\'ri. Bu chaqaloqlar haqidagi umumiy faktdir (Nolinchi shart gapi).)</em></p>',
        'correct': 'are',
        'choices': ['will be', 'are', 'were', 'be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you eat all that cake, you ___ sick.</strong></p>',
        'explanation': '<p><strong>will feel</strong> is correct. This is a warning about a specific future result (First Conditional). <br><br><em>(<strong>will feel</strong> to\'g\'ri. Bu kelajakdagi aniq natija haqidagi ogohlantirishdir (Birinchi shart gapi).)</em></p>',
        'correct': 'will feel',
        'choices': ['feel', 'felt', 'are feeling', 'will feel'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Plants die if they ___ enough water.</strong></p>',
        'explanation': '<p><strong>don\'t get</strong> is correct. This is a scientific fact, so it requires the Zero Conditional (Present Simple). <br><br><em>(<strong>don\'t get</strong> to\'g\'ri. Bu ilmiy fakt, shuning uchun u Nolinchi shart gapini (Present Simple) talab qiladi.)</em></p>',
        'correct': 'don\'t get',
        'choices': ['won\'t get', 'didn\'t get', 'don\'t get', 'not get'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If we leave now, we ___ on time.</strong></p>',
        'explanation': '<p><strong>will arrive</strong> is correct. This is a specific plan or prediction for the immediate future (First Conditional). <br><br><em>(<strong>will arrive</strong> to\'g\'ri. Bu yaqin kelajak uchun aniq reja yoki bashorat (Birinchi shart gapi).)</em></p>',
        'correct': 'will arrive',
        'choices': ['arrive', 'will arrive', 'arrived', 'are arriving'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>When the sun goes down, it ___ dark.</strong></p>',
        'explanation': '<p><strong>gets</strong> is correct. "When" can often replace "If" in Zero Conditional sentences to express a 100% certain fact. <br><br><em>(<strong>gets</strong> to\'g\'ri. 100% aniq faktni ifodalash uchun nolinchi shart gaplarida "When" (qachonki) so\'zi ko\'pincha "If" (agar) o\'rniga kelishi mumkin.)</em></p>',
        'correct': 'gets',
        'choices': ['will get', 'gets', 'got', 'is getting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I have enough money next month, I ___ a new Mac.</strong></p>',
        'explanation': '<p><strong>will buy</strong> is correct. This refers to a possible specific action in the future (First Conditional). <br><br><em>(<strong>will buy</strong> to\'g\'ri. Bu kelajakdagi ehtimoliy aniq harakatni bildiradi (Birinchi shart gapi).)</em></p>',
        'correct': 'will buy',
        'choices': ['buy', 'bought', 'will buy', 'am buying'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you press this button, the computer ___.</strong></p>',
        'explanation': '<p><strong>turns off</strong> is correct. This describes how a machine works, which is a fact (Zero Conditional). <br><br><em>(<strong>turns off</strong> to\'g\'ri. Bu mashinaning qanday ishlashini tasvirlaydi, bu esa faktdir (Nolinchi shart gapi).)</em></p>',
        'correct': 'turns off',
        'choices': ['will turn off', 'turned off', 'turns off', 'turn off'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you drop that glass, it ___.</strong></p>',
        'explanation': '<p><strong>will break</strong> is correct. This is a warning about what will specifically happen if you do this right now. <br><br><em>(<strong>will break</strong> to\'g\'ri. Bu agar siz hozir buni qilsangiz nima sodir bo\'lishi haqida aniq ogohlantirishdir.)</em></p>',
        'correct': 'will break',
        'choices': ['breaks', 'will break', 'broke', 'is breaking'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Ice melts if you ___ it.</strong></p>',
        'explanation': '<p><strong>heat</strong> is correct. This is a scientific fact. The "if" clause uses Present Simple. <br><br><em>(<strong>heat</strong> to\'g\'ri. Bu ilmiy fakt. "If" (agar) qismi Present Simple zamonidan foydalanadi.)</em></p>',
        'correct': 'heat',
        'choices': ['will heat', 'heated', 'are heating', 'heat'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If the weather ___ nice this weekend, we will go to the park.</strong></p>',
        'explanation': '<p><strong>is</strong> is correct. In the First Conditional, the "If" part must be in the Present Simple tense, even though it talks about the future. <br><br><em>(<strong>is</strong> to\'g\'ri. Birinchi shart gapida kelajak haqida gapirilsa ham, "If" qismi Present Simple zamonida bo\'lishi shart.)</em></p>',
        'correct': 'is',
        'choices': ['will be', 'is', 'was', 'be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she invites me, I ___ to the party.</strong></p>',
        'explanation': '<p><strong>will go</strong> is correct. This is a promise or a likely future action based on a condition. <br><br><em>(<strong>will go</strong> to\'g\'ri. Bu shartga asoslangan va\'da yoki kelajakdagi ehtimoli yuqori harakat.)</em></p>',
        'correct': 'will go',
        'choices': ['go', 'will go', 'went', 'am going'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>A snake bites if it ___ scared.</strong></p>',
        'explanation': '<p><strong>is</strong> is correct. This is a general fact about animal behavior (Zero Conditional). <br><br><em>(<strong>is</strong> to\'g\'ri. Bu hayvonlarning xulq-atvori haqidagi umumiy faktdir (Nolinchi shart gapi).)</em></p>',
        'correct': 'is',
        'choices': ['will be', 'is', 'was', 'be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If he doesn\'t call me back, I ___ very angry.</strong></p>',
        'explanation': '<p><strong>will be</strong> is correct. This is a specific reaction to a future possibility (First Conditional). <br><br><em>(<strong>will be</strong> to\'g\'ri. Bu kelajakdagi ehtimolga nisbatan aniq reaksiya (Birinchi shart gapi).)</em></p>',
        'correct': 'will be',
        'choices': ['am', 'was', 'will be', 'be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Wood floats if you ___ it in water.</strong></p>',
        'explanation': '<p><strong>drop</strong> is correct. This is a law of physics (Zero Conditional). Both verbs are in Present Simple. <br><br><em>(<strong>drop</strong> to\'g\'ri. Bu fizika qonuni (Nolinchi shart gapi). Ikkala fe\'l ham Present Simple zamonida.)</em></p>',
        'correct': 'drop',
        'choices': ['will drop', 'dropped', 'drop', 'are dropping'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ me with Python, I will help you with English.</strong></p>',
        'explanation': '<p><strong>help</strong> is correct. This is a deal/promise for the future. The "If" part uses Present Simple. <br><br><em>(<strong>help</strong> to\'g\'ri. Bu kelajak uchun kelishuv/va\'da. "If" qismi Present Simple dan foydalanadi.)</em></p>',
        'correct': 'help',
        'choices': ['will help', 'helped', 'help', 'are helping'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you stand in the rain without an umbrella, you ___ wet.</strong></p>',
        'explanation': '<p><strong>get</strong> is correct. This is a logical fact that is always true (Zero Conditional). <br><br><em>(<strong>get</strong> to\'g\'ri. Bu har doim to\'g\'ri keladigan mantiqiy fakt (Nolinchi shart gapi).)</em></p>',
        'correct': 'get',
        'choices': ['will get', 'get', 'got', 'getting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If they win the match, they ___ the trophy.</strong></p>',
        'explanation': '<p><strong>will get</strong> is correct. This is a possible future result of a specific event (First Conditional). <br><br><em>(<strong>will get</strong> to\'g\'ri. Bu aniq bir voqeaning kelajakdagi ehtimoliy natijasi (Birinchi shart gapi).)</em></p>',
        'correct': 'will get',
        'choices': ['get', 'will get', 'got', 'are getting'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>You get green if you ___ yellow and blue.</strong></p>',
        'explanation': '<p><strong>mix</strong> is correct. Mixing colors is a universal truth, so we use Present Simple in both clauses. <br><br><em>(<strong>mix</strong> to\'g\'ri. Ranglarni aralashtirish umumjahon haqiqatidir, shuning uchun biz ikkala qismda ham Present Simple ishlatamiz.)</em></p>',
        'correct': 'mix',
        'choices': ['will mix', 'mixed', 'mix', 'are mixing'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I don\'t sleep well tonight, I ___ tired tomorrow.</strong></p>',
        'explanation': '<p><strong>will be</strong> is correct. This connects a present condition to a specific future result (First Conditional). <br><br><em>(<strong>will be</strong> to\'g\'ri. Bu hozirgi holatni kelajakdagi aniq natija bilan bog\'laydi (Birinchi shart gapi).)</em></p>',
        'correct': 'will be',
        'choices': ['am', 'was', 'will be', 'be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you put salt in water, it ___.</strong></p>',
        'explanation': '<p><strong>dissolves</strong> is correct. This is a scientific fact. We use Zero Conditional. <br><br><em>(<strong>dissolves</strong> to\'g\'ri. Bu ilmiy fakt. Biz Nolinchi shart gapidan foydalanamiz.)</em></p>',
        'correct': 'dissolves',
        'choices': ['will dissolve', 'dissolves', 'dissolved', 'is dissolving'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If the students do their homework, they ___ faster.</strong></p>',
        'explanation': '<p><strong>will learn</strong> is correct. This is a likely outcome of a specific situation (First Conditional). <br><br><em>(<strong>will learn</strong> to\'g\'ri. Bu aniq vaziyatning ehtimoli yuqori bo\'lgan natijasi (Birinchi shart gapi).)</em></p>',
        'correct': 'will learn',
        'choices': ['learn', 'learned', 'will learn', 'are learning'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I get a headache if I ___ at the screen too long.</strong></p>',
        'explanation': '<p><strong>stare</strong> is correct. This is a personal routine or fact about the speaker (Zero Conditional). <br><br><em>(<strong>stare</strong> to\'g\'ri. Bu so\'zlovchi haqidagi shaxsiy odat yoki fakt (Nolinchi shart gapi).)</em></p>',
        'correct': 'stare',
        'choices': ['will stare', 'stared', 'stare', 'am staring'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If the Django app crashes, I ___ the server logs immediately.</strong></p>',
        'explanation': '<p><strong>will check</strong> is correct. This is an action plan for a possible future event (First Conditional). <br><br><em>(<strong>will check</strong> to\'g\'ri. Bu kelajakdagi ehtimoliy hodisa uchun harakat rejasi (Birinchi shart gapi).)</em></p>',
        'correct': 'will check',
        'choices': ['check', 'will check', 'checked', 'am checking'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ water, it turns into ice.</strong></p>',
        'explanation': '<p><strong>freeze</strong> is correct. This is a factual statement (Zero Conditional). <br><br><em>(<strong>freeze</strong> to\'g\'ri. Bu faktik tasdiq (Nolinchi shart gapi).)</em></p>',
        'correct': 'freeze',
        'choices': ['will freeze', 'freeze', 'froze', 'are freezing'],
    }
]
QUESTIONS_13 = [
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I ___ a million dollars, I would travel to Japan.</strong></p>',
        'explanation': '<p><strong>had</strong> is correct. In the Second Conditional, the "If" clause uses the Past Simple tense. <br><br><em>(<strong>had</strong> to\'g\'ri. Ikkinchi shart gapida "If" (agar) qismi Past Simple (oddiy o\'tgan) zamondan foydalanadi.)</em></p>',
        'correct': 'had',
        'choices': ['have', 'had', 'would have', 'am having'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she practiced every day, she ___ the chess tournament.</strong></p>',
        'explanation': '<p><strong>would win</strong> is correct. The result clause uses "would + verb" to show the imaginary outcome. <br><br><em>(<strong>would win</strong> to\'g\'ri. Natija qismida xayoliy oqibatni ko\'rsatish uchun "would + fe\'l" ishlatiladi.)</em></p>',
        'correct': 'would win',
        'choices': ['will win', 'wins', 'would win', 'won'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I ___ you, I would learn Python and Django.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. In the Second Conditional, we use "were" for all subjects (I, he, she, it) to give advice. <br><br><em>(<strong>were</strong> to\'g\'ri. Ikkinchi shart gapida maslahat berish uchun barcha shaxslarga (I, he, she, it) nisbatan "were" ishlatamiz.)</em></p>',
        'correct': 'were',
        'choices': ['was', 'am', 'were', 'be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We ___ faster if we didn\'t have so many bugs in the code.</strong></p>',
        'explanation': '<p><strong>would deploy</strong> is correct. The "If" clause is in the past (didn\'t have), so the result needs "would + verb". <br><br><em>(<strong>would deploy</strong> to\'g\'ri. "If" qismi o\'tgan zamonda (didn\'t have) turibdi, shuning uchun natija qismi "would + fe\'l" talab qiladi.)</em></p>',
        'correct': 'would deploy',
        'choices': ['will deploy', 'deploy', 'would deploy', 'deployed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If he ___ the answer, he would tell us immediately.</strong></p>',
        'explanation': '<p><strong>knew</strong> is correct. This is an imaginary present situation, so we use the Past Simple form of "know". <br><br><em>(<strong>knew</strong> to\'g\'ri. Bu xayoliy hozirgi vaziyat, shuning uchun biz "know" (bilmoq) fe\'lining Past Simple shaklidan foydalanamiz.)</em></p>',
        'correct': 'knew',
        'choices': ['knows', 'will know', 'would know', 'knew'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I wouldn\'t do that if I ___ in your position!</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. The phrase "If I were..." is the standard grammatical structure for imagining yourself as someone else. <br><br><em>(<strong>were</strong> to\'g\'ri. "If I were..." iborasi o\'zingizni boshqa birovning o\'rnida tasavvur qilish uchun standart grammatik qurilmadir.)</em></p>',
        'correct': 'were',
        'choices': ['was', 'am', 'were', 'had been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ less junk food, you would feel much healthier.</strong></p>',
        'explanation': '<p><strong>ate</strong> is correct. We use the Past Simple (ate) after "if" to describe an unlikely or imaginary habit. <br><br><em>(<strong>ate</strong> to\'g\'ri. Biz sodir bo\'lishi qiyin yoki xayoliy odatni tasvirlash uchun "if" dan keyin Past Simple (ate) ishlatamiz.)</em></p>',
        'correct': 'ate',
        'choices': ['eat', 'will eat', 'would eat', 'ate'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>What ___ if you found a lost wallet on the street?</strong></p>',
        'explanation': '<p><strong>would you do</strong> is correct. This is a question about an imaginary situation, asking for the imaginary result. <br><br><em>(<strong>would you do</strong> to\'g\'ri. Bu xayoliy vaziyat haqidagi savol bo\'lib, unda xayoliy natija so\'ralmoqda.)</em></p>',
        'correct': 'would you do',
        'choices': ['will you do', 'do you do', 'would you do', 'did you do'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If the students ___ more free time, they would play games all day.</strong></p>',
        'explanation': '<p><strong>had</strong> is correct. "Had" is the Past Simple form required in the condition clause. <br><br><em>(<strong>had</strong> to\'g\'ri. "Had" shart ergash gapda talab qilinadigan Past Simple shaklidir.)</em></p>',
        'correct': 'had',
        'choices': ['have', 'had', 'would have', 'will have'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>They ___ a new house if they had enough money.</strong></p>',
        'explanation': '<p><strong>would buy</strong> is correct. The condition (had enough money) is imaginary, so the result must use "would". <br><br><em>(<strong>would buy</strong> to\'g\'ri. Shart (yetarli puli bo\'lishi) xayoliydir, shuning uchun natijada "would" ishlatilishi shart.)</em></p>',
        'correct': 'would buy',
        'choices': ['will buy', 'buy', 'bought', 'would buy'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If it ___ in July, I would be very surprised.</strong></p>',
        'explanation': '<p><strong>snowed</strong> is correct. Snowing in July is highly unlikely, requiring the Second Conditional\'s past tense form. <br><br><em>(<strong>snowed</strong> to\'g\'ri. Iyul oyida qor yog\'ishi ehtimoldan juda yiroq, shuning uchun Ikkinchi shart gapining o\'tgan zamon shakli talab qilinadi.)</em></p>',
        'correct': 'snowed',
        'choices': ['snows', 'will snow', 'snowed', 'would snow'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I would help you with the website if I ___ how to code.</strong></p>',
        'explanation': '<p><strong>knew</strong> is correct. Reality is "I don\'t know", so the imaginary opposite requires Past Simple. <br><br><em>(<strong>knew</strong> to\'g\'ri. Haqiqiy holat "Men bilmayman", shuning uchun xayoliy qarama-qarshi vaziyat Past Simple ni talab qiladi.)</em></p>',
        'correct': 'knew',
        'choices': ['know', 'knew', 'would know', 'am knowing'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she ___ Japanese fluently, she would move to Tokyo today.</strong></p>',
        'explanation': '<p><strong>spoke</strong> is correct. The "If" clause takes the Past Simple for an impossible present situation. <br><br><em>(<strong>spoke</strong> to\'g\'ri. Hozirgi imkonsiz vaziyat uchun "If" qismiga Past Simple qo\'yiladi.)</em></p>',
        'correct': 'spoke',
        'choices': ['speaks', 'spoke', 'would speak', 'will speak'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If we didn\'t have to work today, we ___ to the mountains.</strong></p>',
        'explanation': '<p><strong>would go</strong> is correct. We are imagining the result of an impossible condition (not working today). <br><br><em>(<strong>would go</strong> to\'g\'ri. Biz imkonsiz shartning (bugun ishlamaslikning) natijasini tasavvur qilyapmiz.)</em></p>',
        'correct': 'would go',
        'choices': ['will go', 'go', 'would go', 'went'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Where ___ if you could live anywhere in the world?</strong></p>',
        'explanation': '<p><strong>would you live</strong> is correct. We use "would" to ask about imaginary choices or preferences. <br><br><em>(<strong>would you live</strong> to\'g\'ri. Xayoliy tanlovlar yoki xohishlarni so\'rash uchun biz "would" dan foydalanamiz.)</em></p>',
        'correct': 'would you live',
        'choices': ['will you live', 'would you live', 'do you live', 'did you live'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If my car ___ broken, I would drive you to the education center.</strong></p>',
        'explanation': '<p><strong>weren\'t</strong> is correct. We use "were not" (weren\'t) for all subjects in formal Second Conditional sentences. <br><br><em>(<strong>weren\'t</strong> to\'g\'ri. Rasmiy Ikkinchi shart gaplarida biz barcha shaxslar uchun "were not" (weren\'t) ishlatamiz.)</em></p>',
        'correct': 'weren\'t',
        'choices': ['isn\'t', 'wasn\'t', 'weren\'t', 'wouldn\'t be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He would get the job if he ___ more confident during interviews.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. Even for "he", we use "were" to describe this imaginary state of being. <br><br><em>(<strong>were</strong> to\'g\'ri. Bu xayoliy holatni tasvirlash uchun "he" (u) shaxsi uchun ham "were" ishlatamiz.)</em></p>',
        'correct': 'were',
        'choices': ['is', 'were', 'was', 'would be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I found a great tutorial online, I ___ it with my students.</strong></p>',
        'explanation': '<p><strong>would share</strong> is correct. The "If" part is in the past (found), so the result needs "would". <br><br><em>(<strong>would share</strong> to\'g\'ri. "If" qismi o\'tgan zamonda (found), shuning uchun natijada "would" kerak.)</em></p>',
        'correct': 'would share',
        'choices': ['will share', 'share', 'shared', 'would share'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she ___ so far away, we would visit her every week.</strong></p>',
        'explanation': '<p><strong>didn\'t live</strong> is correct. This is the negative Past Simple form for the condition clause. <br><br><em>(<strong>didn\'t live</strong> to\'g\'ri. Bu shart ergash gap uchun Past Simple dagi inkor shakli.)</em></p>',
        'correct': 'didn\'t live',
        'choices': ['doesn\'t live', 'didn\'t live', 'wouldn\'t live', 'not lived'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The project would finish faster if we ___ more team members.</strong></p>',
        'explanation': '<p><strong>had</strong> is correct. Imagining a different present reality requires the Past Simple. <br><br><em>(<strong>had</strong> to\'g\'ri. Boshqacha hozirgi reallikni tasavvur qilish Past Simple zamonini talab qiladi.)</em></p>',
        'correct': 'had',
        'choices': ['have', 'had', 'would have', 'are having'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ your phone, how would you call your family?</strong></p>',
        'explanation': '<p><strong>lost</strong> is correct. This is an imaginary, unlikely situation, taking the Past Simple form of "lose". <br><br><em>(<strong>lost</strong> to\'g\'ri. Bu xayoliy, sodir bo\'lishi dargumon vaziyat bo\'lib, "lose" (yo\'qotmoq) fe\'lining Past Simple shaklini oladi.)</em></p>',
        'correct': 'lost',
        'choices': ['lose', 'lost', 'will lose', 'would lose'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ that old laptop if it weren\'t so expensive.</strong></p>',
        'explanation': '<p><strong>would buy</strong> is correct. The condition is impossible (it IS expensive), so the result uses "would". <br><br><em>(<strong>would buy</strong> to\'g\'ri. Shart imkonsiz (u qimmat), shuning uchun natijada "would" ishlatiladi.)</em></p>',
        'correct': 'would buy',
        'choices': ['will buy', 'bought', 'would buy', 'buy'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If humans ___ on Mars, they would need special breathing suits.</strong></p>',
        'explanation': '<p><strong>lived</strong> is correct. Imagining an impossible present/future scenario uses Past Simple. <br><br><em>(<strong>lived</strong> to\'g\'ri. Imkonsiz hozirgi/kelajak ssenariysini tasavvur qilishda Past Simple ishlatiladi.)</em></p>',
        'correct': 'lived',
        'choices': ['live', 'lived', 'would live', 'are living'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Would you go to the conference if they ___ you to speak?</strong></p>',
        'explanation': '<p><strong>invited</strong> is correct. The main clause uses "would", meaning the condition clause must be in Past Simple. <br><br><em>(<strong>invited</strong> to\'g\'ri. Asosiy gap "would" dan foydalangan, ya\'ni shart qismi Past Simple da bo\'lishi shart.)</em></p>',
        'correct': 'invited',
        'choices': ['invite', 'will invite', 'invited', 'would invite'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I ___ a bird, I would fly across the world.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. A classic impossible scenario requiring the special "were" form. <br><br><em>(<strong>were</strong> to\'g\'ri. Maxsus "were" shaklini talab qiluvchi klassik imkonsiz ssenariy.)</em></p>',
        'correct': 'were',
        'choices': ['was', 'am', 'were', 'had been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He would be much healthier if he ___ some exercise.</strong></p>',
        'explanation': '<p><strong>did</strong> is correct. This is advice or an imaginary better situation, needing Past Simple. <br><br><em>(<strong>did</strong> to\'g\'ri. Bu maslahat yoki xayoliy yaxshiroq vaziyat bo\'lib, Past Simple zamonini talab qiladi.)</em></p>',
        'correct': 'did',
        'choices': ['does', 'do', 'would do', 'did'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If the weather ___ better, we would go for a walk outside.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. The weather is a single thing (it), but we still use "were" in formal Second Conditional. <br><br><em>(<strong>were</strong> to\'g\'ri. Ob-havo birlikdagi narsa (it), lekin rasmiy Ikkinchi shart gapida baribir "were" ishlatamiz.)</em></p>',
        'correct': 'were',
        'choices': ['was', 'is', 'were', 'would be'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ more English books, your vocabulary would improve fast.</strong></p>',
        'explanation': '<p><strong>read</strong> is correct. We need the past tense of "read" (spelled the same, pronounced "red") after "if". <br><br><em>(<strong>read</strong> to\'g\'ri. "If" dan keyin "read" (o\'qimoq) fe\'lining o\'tgan zamon shakli kerak (yozilishi bir xil, lekin "red" deb o\'qiladi).)</em></p>',
        'correct': 'read',
        'choices': ['read', 'will read', 'would read', 'are reading'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ so stressed if I didn\'t have a big deadline tomorrow.</strong></p>',
        'explanation': '<p><strong>wouldn\'t be</strong> is correct. This is the negative result of an imaginary condition. <br><br><em>(<strong>wouldn\'t be</strong> to\'g\'ri. Bu xayoliy shartning inkor natijasi.)</em></p>',
        'correct': 'wouldn\'t be',
        'choices': ['won\'t be', 'am not', 'wouldn\'t be', 'wasn\'t'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I knew the password, I ___ the system immediately.</strong></p>',
        'explanation': '<p><strong>would unlock</strong> is correct. The imaginary result of knowing the password uses "would". <br><br><em>(<strong>would unlock</strong> to\'g\'ri. Parolni bilishning xayoliy natijasi "would" dan foydalanadi.)</em></p>',
        'correct': 'would unlock',
        'choices': ['will unlock', 'unlocked', 'would unlock', 'unlock'],
    }
]


QUESTIONS_14 = [
    {
        'text': '<p>Choose the correct option.</p><p><strong>The teacher ___ helped me with my English is excellent.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. We use "who" for people. <br><br><em>(<strong>who</strong> to\'g\'ri. Biz insonlar uchun "who" ishlatamiz.)</em></p>',
        'correct': 'who',
        'choices': ['which', 'who', 'what', 'where'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The laptop ___ is on the desk belongs to the manager.</strong></p>',
        'explanation': '<p><strong>which</strong> is correct. We use "which" for things and objects. <br><br><em>(<strong>which</strong> to\'g\'ri. Biz narsa va obyektlar uchun "which" ishlatamiz.)</em></p>',
        'correct': 'which',
        'choices': ['who', 'which', 'whom', 'where'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Here is the book ___ you were looking for.</strong></p>',
        'explanation': '<p><strong>that</strong> is correct. "That" is used for things and is very common in spoken English. <br><br><em>(<strong>that</strong> to\'g\'ri. "That" narsalar uchun ishlatiladi va og\'zaki ingliz tilida juda keng tarqalgan.)</em></p>',
        'correct': 'that',
        'choices': ['who', 'where', 'that', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The students ___ pass the exam will get a certificate.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. "Students" are people, so we must use "who" (or "that"). <br><br><em>(<strong>who</strong> to\'g\'ri. "Students" (O\'quvchilar) insonlar hisoblanadi, shuning uchun biz "who" (yoki "that") ishlatishimiz shart.)</em></p>',
        'correct': 'who',
        'choices': ['which', 'who', 'whom', 'whose'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The restaurant ___ we ate at last night was very expensive.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. The next word is a pronoun ("we"), so you can drop the relative word completely. <br><br><em>(<strong>(no word needed) (so\'z kerak emas)</strong> to\'g\'ri. Keyingi so\'z olmosh ("we") bo\'lganligi sababli, nisbiy so\'zni butunlay tushirib qoldirish mumkin.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['who', 'what', '(no word needed)', 'whose'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The man ___ is talking to Sarah is the new director.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. We use "who" for a person. We cannot omit it because the next word is a verb ("is"). <br><br><em>(<strong>who</strong> to\'g\'ri. Biz insonlar uchun "who" ishlatamiz. Uni tushirib qoldira olmaymiz, chunki keyingi so\'z fe\'l ("is").)</em></p>',
        'correct': 'who',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The bag ___ I bought yesterday is made of genuine leather.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. You can omit the relative word because the next word is a pronoun ("I"). <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Nisbiy so\'zni tushirib qoldirishingiz mumkin, chunki keyingi so\'z olmosh ("I").)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Do you know the boy ___ won the chess tournament?</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. The boy is a person, and the next word is a verb ("won"), so we must use "who". <br><br><em>(<strong>who</strong> to\'g\'ri. Bola inson hisoblanadi va keyingi so\'z fe\'l ("won"), shuning uchun "who" ishlatishimiz shart.)</em></p>',
        'correct': 'who',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The code ___ he wrote has a few minor bugs.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. Since the next word is a pronoun ("he"), we can drop the relative word. <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Keyingi so\'z olmosh ("he") bo\'lgani uchun nisbiy so\'zni tushirib qoldira olamiz.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The course ___ I am taking is very difficult but interesting.</strong></p>',
        'explanation': '<p><strong>that</strong> is correct. "That" is perfect for describing things like a course. <br><br><em>(<strong>that</strong> to\'g\'ri. "That" kurs kabi narsalarni tasvirlash uchun juda mos.)</em></p>',
        'correct': 'that',
        'choices': ['that', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I don\'t like people ___ complain all the time.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. For people, we use "who". We cannot omit it because the next word is a verb ("complain"). <br><br><em>(<strong>who</strong> to\'g\'ri. Insonlar uchun biz "who" ishlatamiz. Keyingi so\'z fe\'l ("complain") bo\'lgani uchun uni tushirib qoldira olmaymiz.)</em></p>',
        'correct': 'who',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The letter ___ arrived today is for you.</strong></p>',
        'explanation': '<p><strong>which</strong> is correct. We use "which" for things (the letter). It cannot be dropped because "arrived" is a verb. <br><br><em>(<strong>which</strong> to\'g\'ri. Biz narsalar (xat) uchun "which" ishlatamiz. "arrived" fe\'l bo\'lgani uchun uni tushirib qoldirib bo\'lmaydi.)</em></p>',
        'correct': 'which',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She is the girl ___ works in the local library.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. We use "who" to refer to people. <br><br><em>(<strong>who</strong> to\'g\'ri. Insonlarga ishora qilish uchun "who" ishlatamiz.)</em></p>',
        'correct': 'who',
        'choices': ['who', 'which', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The phone ___ is ringing belongs to my boss.</strong></p>',
        'explanation': '<p><strong>which</strong> is correct. We use "which" for objects. <br><br><em>(<strong>which</strong> to\'g\'ri. Biz obyektlar uchun "which" ishlatamiz.)</em></p>',
        'correct': 'which',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The woman ___ you saw yesterday is my aunt.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. You can drop the relative word because the next word is a pronoun ("you"). <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Keyingi so\'z olmosh ("you") bo\'lgani uchun nisbiy so\'zni tushirib qoldirishingiz mumkin.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'which', 'what', 'whose'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I found the keys ___ I lost yesterday.</strong></p>',
        'explanation': '<p><strong>that</strong> is correct. "That" is used for things. (You could also omit it here). <br><br><em>(<strong>that</strong> to\'g\'ri. "That" narsalar uchun ishlatiladi. (Bu yerda uni tushirib qoldirishingiz ham mumkin edi).)</em></p>',
        'correct': 'that',
        'choices': ['that', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The doctor ___ treated me is very famous.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. "Doctor" is a person, and the next word is a verb ("treated"). <br><br><em>(<strong>who</strong> to\'g\'ri. "Doktor" inson hisoblanadi, va keyingi so\'z fe\'l ("treated").)</em></p>',
        'correct': 'who',
        'choices': ['who', 'which', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The shoes ___ I am wearing are very comfortable.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. The next word is the pronoun "I", so the relative word can be omitted. <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Keyingi so\'z "I" olmoshi, shuning uchun nisbiy so\'zni tushirib qoldirish mumkin.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The bus ___ goes to the airport leaves every hour.</strong></p>',
        'explanation': '<p><strong>which</strong> is correct. A bus is a thing, and it is followed by a verb ("goes"), so "which" is needed. <br><br><em>(<strong>which</strong> to\'g\'ri. Avtobus narsa, va undan keyin fe\'l ("goes") kelyapti, shuning uchun "which" kerak.)</em></p>',
        'correct': 'which',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Where is the cheese ___ was in the fridge?</strong></p>',
        'explanation': '<p><strong>that</strong> is correct. We use "that" (or "which") for things. We cannot omit it because of the verb "was". <br><br><em>(<strong>that</strong> to\'g\'ri. Biz narsalar uchun "that" (yoki "which") ishlatamiz. "was" fe\'li bo\'lgani sababli uni tushirib qoldira olmaymiz.)</em></p>',
        'correct': 'that',
        'choices': ['that', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>A software developer is someone ___ writes computer code.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. "Someone" refers to a person. <br><br><em>(<strong>who</strong> to\'g\'ri. "Someone" (kimdir) insonga ishora qiladi.)</em></p>',
        'correct': 'who',
        'choices': ['who', 'which', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The video ___ you shared is very funny.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. The word following the blank is a pronoun ("you"). <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Bo\'sh joydan keyingi so\'z olmosh ("you") hisoblanadi.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I need a smartphone ___ has a good camera.</strong></p>',
        'explanation': '<p><strong>that</strong> is correct. Used for things. (Cannot be omitted because the next word is the verb "has"). <br><br><em>(<strong>that</strong> to\'g\'ri. Narsalar uchun ishlatiladi. (Keyingi so\'z "has" fe\'li bo\'lgani uchun tushirib qoldirib bo\'lmaydi).)</em></p>',
        'correct': 'that',
        'choices': ['that', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The friend ___ I was waiting for didn\'t arrive.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. Although it is a person, the next word is a pronoun ("I"), making it optional. <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. U inson bo\'lishiga qaramay, keyingi so\'z olmosh ("I"), bu esa uni ixtiyoriy qiladi.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'which', 'what', 'whose'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The project ___ we are working on is a secret.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. The next word is the pronoun "we". <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Keyingi so\'z "we" olmoshi.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Can you pass me the pen ___ is on the table?</strong></p>',
        'explanation': '<p><strong>which</strong> is correct. Pen is a thing, and the next word is a verb. <br><br><em>(<strong>which</strong> to\'g\'ri. Ruchka narsa hisoblanadi va keyingi so\'z fe\'l.)</em></p>',
        'correct': 'which',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The teacher ___ explains things clearly is the best.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. "Teacher" is a person. <br><br><em>(<strong>who</strong> to\'g\'ri. "O\'qituvchi" inson hisoblanadi.)</em></p>',
        'correct': 'who',
        'choices': ['who', 'which', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The cake ___ she baked was delicious.</strong></p>',
        'explanation': '<p><strong>that</strong> is correct. Used for a thing (cake). It could also be omitted here. <br><br><em>(<strong>that</strong> to\'g\'ri. Narsa (tort) uchun ishlatiladi. Bu yerda uni tushirib qoldirish ham mumkin edi.)</em></p>',
        'correct': 'that',
        'choices': ['that', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>Anyone ___ wants to join the team must apply today.</strong></p>',
        'explanation': '<p><strong>who</strong> is correct. "Anyone" refers to a person, and it is followed by a verb. <br><br><em>(<strong>who</strong> to\'g\'ri. "Anyone" (kimki) insonga ishora qiladi va undan keyin fe\'l keladi.)</em></p>',
        'correct': 'who',
        'choices': ['which', 'who', 'whom', 'what'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>The advice ___ you gave me was very helpful.</strong></p>',
        'explanation': '<p><strong>(no word needed)</strong> is correct. The next word is the pronoun "you", allowing the relative pronoun to be dropped. <br><br><em>(<strong>(no word needed)</strong> to\'g\'ri. Keyingi so\'z "you" olmoshi, bu nisbiy olmoshni tushirib qoldirishga imkon beradi.)</em></p>',
        'correct': '(no word needed)',
        'choices': ['(no word needed)', 'who', 'whom', 'what'],
    }
]

QUESTIONS_15 = [
    {
        'text': '<p>Choose the correct option.</p><p><strong>If it rains tomorrow, we ___ at home.</strong></p>',
        'explanation': '<p><strong>will stay</strong> is correct. This is the First Conditional (real future plan). <br><br><em>(<strong>will stay</strong> to\'g\'ri. Bu Birinchi shart gapi (kelajakdagi haqiqiy reja).)</em></p>',
        'correct': 'will stay',
        'choices': ['stay', 'would stay', 'will stay', 'would have stayed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I ___ a million dollars right now, I would buy a big house.</strong></p>',
        'explanation': '<p><strong>had</strong> is correct. This is the Second Conditional (imaginary present). The "if" part needs Past Simple. <br><br><em>(<strong>had</strong> to\'g\'ri. Bu Ikkinchi shart gapi (xayoliy hozirgi payt). "If" qismi Past Simple zamonini talab qiladi.)</em></p>',
        'correct': 'had',
        'choices': ['have', 'had', 'will have', 'had had'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she had studied harder last year, she ___ the exam.</strong></p>',
        'explanation': '<p><strong>would have passed</strong> is correct. This is the Third Conditional (imaginary past). <br><br><em>(<strong>would have passed</strong> to\'g\'ri. Bu Uchinchi shart gapi (xayoliy o\'tmish).)</em></p>',
        'correct': 'would have passed',
        'choices': ['will pass', 'would pass', 'passed', 'would have passed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ hurry, you will miss the train!</strong></p>',
        'explanation': '<p><strong>don\'t</strong> is correct. First Conditional uses Present Simple in the "if" clause for future possibilities. <br><br><em>(<strong>don\'t</strong> to\'g\'ri. Birinchi shart gapi kelajak ehtimolliklari uchun "if" qismida Present Simple dan foydalanadi.)</em></p>',
        'correct': 'don\'t',
        'choices': ['won\'t', 'wouldn\'t', 'didn\'t', 'don\'t'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ you if I had known you were in the hospital yesterday.</strong></p>',
        'explanation': '<p><strong>would have visited</strong> is correct. Third Conditional. The chance is gone because it happened yesterday. <br><br><em>(<strong>would have visited</strong> to\'g\'ri. Uchinchi shart gapi. Imkoniyat qo\'ldan boy berilgan, chunki bu kecha sodir bo\'lgan.)</em></p>',
        'correct': 'would have visited',
        'choices': ['will visit', 'would visit', 'visited', 'would have visited'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I ___ you, I wouldn\'t text him back.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. Second Conditional for giving advice. We use "were" for all subjects. <br><br><em>(<strong>were</strong> to\'g\'ri. Maslahat berish uchun Ikkinchi shart gapi. Biz barcha shaxslar uchun "were" ishlatamiz.)</em></p>',
        'correct': 'were',
        'choices': ['am', 'was', 'were', 'had been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If we leave now, we ___ there by 5 PM.</strong></p>',
        'explanation': '<p><strong>will be</strong> is correct. First conditional representing a real plan. <br><br><em>(<strong>will be</strong> to\'g\'ri. Haqiqiy rejani ifodalovchi Birinchi shart gapi.)</em></p>',
        'correct': 'will be',
        'choices': ['are', 'will be', 'would be', 'would have been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>He would travel the world if he ___ rich, but he is poor.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. Second Conditional for an imaginary present reality. <br><br><em>(<strong>were</strong> to\'g\'ri. Xayoliy hozirgi reallik uchun Ikkinchi shart gapi.)</em></p>',
        'correct': 'were',
        'choices': ['is', 'was', 'were', 'had been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I had seen the red light, I ___ the car.</strong></p>',
        'explanation': '<p><strong>would have stopped</strong> is correct. Third conditional for a past situation that cannot be changed. <br><br><em>(<strong>would have stopped</strong> to\'g\'ri. O\'zgartirib bo\'lmaydigan o\'tmishdagi vaziyat uchun Uchinchi shart gapi.)</em></p>',
        'correct': 'would have stopped',
        'choices': ['will stop', 'would stop', 'stopped', 'would have stopped'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>We will go to the park if the weather ___ nice.</strong></p>',
        'explanation': '<p><strong>is</strong> is correct. First conditional uses Present Simple in the "if" clause. <br><br><em>(<strong>is</strong> to\'g\'ri. Birinchi shart gapi "if" qismida Present Simple ishlatadi.)</em></p>',
        'correct': 'is',
        'choices': ['will be', 'would be', 'is', 'was'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she ___ Japanese fluently, she would live in Tokyo right now.</strong></p>',
        'explanation': '<p><strong>spoke</strong> is correct. Second Conditional (imagining a different present reality). <br><br><em>(<strong>spoke</strong> to\'g\'ri. Ikkinchi shart gapi (boshqacha hozirgi reallikni tasavvur qilish).)</em></p>',
        'correct': 'spoke',
        'choices': ['speaks', 'spoke', 'would speak', 'had spoken'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>They ___ the match yesterday if their best player hadn\'t been injured.</strong></p>',
        'explanation': '<p><strong>would have won</strong> is correct. Third conditional (imagining a different past outcome). <br><br><em>(<strong>would have won</strong> to\'g\'ri. Uchinchi shart gapi (o\'tmishdagi boshqacha natijani tasavvur qilish).)</em></p>',
        'correct': 'would have won',
        'choices': ['will win', 'would win', 'won', 'would have won'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you eat all that chocolate, you ___ sick later!</strong></p>',
        'explanation': '<p><strong>will feel</strong> is correct. First Conditional (real future warning). <br><br><em>(<strong>will feel</strong> to\'g\'ri. Birinchi shart gapi (kelajakdagi haqiqiy ogohlantirish).)</em></p>',
        'correct': 'will feel',
        'choices': ['feel', 'would feel', 'will feel', 'felt'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I wouldn\'t do that if I ___ you.</strong></p>',
        'explanation': '<p><strong>were</strong> is correct. Second conditional for advice. <br><br><em>(<strong>were</strong> to\'g\'ri. Maslahat uchun Ikkinchi shart gapi.)</em></p>',
        'correct': 'were',
        'choices': ['am', 'was', 'were', 'had been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If we ___ the map, we wouldn\'t have gotten lost in the forest yesterday.</strong></p>',
        'explanation': '<p><strong>had brought</strong> is correct. Third Conditional. The "if" clause needs Past Perfect (had + V3). <br><br><em>(<strong>had brought</strong> to\'g\'ri. Uchinchi shart gapi. "if" qismi Past Perfect (had + V3) talab qiladi.)</em></p>',
        'correct': 'had brought',
        'choices': ['bring', 'brought', 'had brought', 'have brought'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If he calls me tonight, I ___ answer.</strong></p>',
        'explanation': '<p><strong>won\'t</strong> is correct. First conditional for a real future decision. <br><br><em>(<strong>won\'t</strong> to\'g\'ri. Kelajakdagi haqiqiy qaror uchun Birinchi shart gapi.)</em></p>',
        'correct': 'won\'t',
        'choices': ['wouldn\'t', 'don\'t', 'won\'t', 'didn\'t'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>What would you do if you ___ a wallet on the street?</strong></p>',
        'explanation': '<p><strong>found</strong> is correct. Second conditional. Imaginary situation requires Past Simple. <br><br><em>(<strong>found</strong> to\'g\'ri. Ikkinchi shart gapi. Xayoliy vaziyat Past Simple talab qiladi.)</em></p>',
        'correct': 'found',
        'choices': ['find', 'will find', 'found', 'had found'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I ___ the email if my computer hadn\'t crashed.</strong></p>',
        'explanation': '<p><strong>would have sent</strong> is correct. Third Conditional (regret about the past). <br><br><em>(<strong>would have sent</strong> to\'g\'ri. Uchinchi shart gapi (o\'tmish haqidagi afsus).)</em></p>',
        'correct': 'would have sent',
        'choices': ['will send', 'would send', 'sent', 'would have sent'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you ___ more water, you will feel better.</strong></p>',
        'explanation': '<p><strong>drink</strong> is correct. First Conditional. Present Simple is used in the condition. <br><br><em>(<strong>drink</strong> to\'g\'ri. Birinchi shart gapi. Shartda Present Simple ishlatiladi.)</em></p>',
        'correct': 'drink',
        'choices': ['drank', 'will drink', 'drink', 'had drunk'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If she ___ more time, she would learn how to code.</strong></p>',
        'explanation': '<p><strong>had</strong> is correct. Second conditional (imaginary present). Reality: she doesn\'t have time. <br><br><em>(<strong>had</strong> to\'g\'ri. Ikkinchi shart gapi (xayoliy hozirgi payt). Reallik: uning vaqti yo\'q.)</em></p>',
        'correct': 'had',
        'choices': ['has', 'will have', 'had', 'had had'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If they had invited me to the party, I ___.</strong></p>',
        'explanation': '<p><strong>would have gone</strong> is correct. Third conditional. Imaginary past action. <br><br><em>(<strong>would have gone</strong> to\'g\'ri. Uchinchi shart gapi. O\'tmishdagi xayoliy harakat.)</em></p>',
        'correct': 'would have gone',
        'choices': ['will go', 'would go', 'went', 'would have gone'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If the train ___, we will be late for the meeting.</strong></p>',
        'explanation': '<p><strong>is delayed</strong> is correct. First conditional. Present simple for a real future possibility. <br><br><em>(<strong>is delayed</strong> to\'g\'ri. Birinchi shart gapi. Kelajakdagi real ehtimollik uchun Present Simple.)</em></p>',
        'correct': 'is delayed',
        'choices': ['was delayed', 'will be delayed', 'is delayed', 'had been delayed'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>I would buy that laptop if it ___ so expensive.</strong></p>',
        'explanation': '<p><strong>weren\'t</strong> is correct. Second conditional. Imaginary present. We use "weren\'t" formally. <br><br><em>(<strong>weren\'t</strong> to\'g\'ri. Ikkinchi shart gapi. Xayoliy hozirgi payt. Biz rasmiy holatda "weren\'t" ishlatamiz.)</em></p>',
        'correct': 'weren\'t',
        'choices': ['isn\'t', 'won\'t be', 'weren\'t', 'hasn\'t been'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I ___ that the movie was so boring, I wouldn\'t have watched it.</strong></p>',
        'explanation': '<p><strong>had known</strong> is correct. Third conditional. The condition clause takes Past Perfect. <br><br><em>(<strong>had known</strong> to\'g\'ri. Uchinchi shart gapi. Shart ergash gap Past Perfect oladi.)</em></p>',
        'correct': 'had known',
        'choices': ['knew', 'know', 'had known', 'have known'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If you help me with this project, I ___ you for lunch.</strong></p>',
        'explanation': '<p><strong>will pay</strong> is correct. First conditional for a real promise. <br><br><em>(<strong>will pay</strong> to\'g\'ri. Haqiqiy va\'da uchun Birinchi shart gapi.)</em></p>',
        'correct': 'will pay',
        'choices': ['pay', 'would pay', 'will pay', 'paid'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>What would you have done if you ___ the keys yesterday?</strong></p>',
        'explanation': '<p><strong>had lost</strong> is correct. Third conditional question about the past. <br><br><em>(<strong>had lost</strong> to\'g\'ri. O\'tmish haqidagi Uchinchi shart gapi savoli.)</em></p>',
        'correct': 'had lost',
        'choices': ['lose', 'lost', 'had lost', 'would lose'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If we didn\'t have to work today, we ___ to the beach.</strong></p>',
        'explanation': '<p><strong>would go</strong> is correct. Second conditional. Imaginary present situation. <br><br><em>(<strong>would go</strong> to\'g\'ri. Ikkinchi shart gapi. Xayoliy hozirgi vaziyat.)</em></p>',
        'correct': 'would go',
        'choices': ['will go', 'would go', 'went', 'would have gone'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If he ___ the password, he won\'t be able to log in.</strong></p>',
        'explanation': '<p><strong>forgets</strong> is correct. First conditional. Present Simple for future conditions. <br><br><em>(<strong>forgets</strong> to\'g\'ri. Birinchi shart gapi. Kelajak shartlari uchun Present Simple.)</em></p>',
        'correct': 'forgets',
        'choices': ['forgot', 'will forget', 'forgets', 'had forgotten'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>She would have been furious if she ___ the truth.</strong></p>',
        'explanation': '<p><strong>had found out</strong> is correct. Third conditional for a past condition that didn\'t happen. <br><br><em>(<strong>had found out</strong> to\'g\'ri. Sodir bo\'lmagan o\'tmishdagi shart uchun Uchinchi shart gapi.)</em></p>',
        'correct': 'had found out',
        'choices': ['found out', 'finds out', 'had found out', 'would find out'],
    },
    {
        'text': '<p>Choose the correct option.</p><p><strong>If I were a bird, I ___ everywhere.</strong></p>',
        'explanation': '<p><strong>would fly</strong> is correct. Second conditional. Impossible present situation. <br><br><em>(<strong>would fly</strong> to\'g\'ri. Ikkinchi shart gapi. Hozirgi imkonsiz vaziyat.)</em></p>',
        'correct': 'would fly',
        'choices': ['will fly', 'flew', 'would fly', 'would have flown'],
    }
]

